export const _SELECT_LIST_CCA='SELECT_LIST_CCA'; 
export const _CLOSE_LIST_CCA='CLOSE_LIST_CCA'; 
export const _SELECT_PAYMENT_DETAILS='SELECT_PAYMENT_DETAILS'; 
export const _CLOSE_PAYMENT_DETAILS='CLOSE_PAYMENT_DETAILS'; 



export const _CLEAR_FILTER='CLEAR_FILTER'; 
export const _LIST_SUCCESS='LIST_SUCCESS'; 
export const _ONFILTER_CLICK='ONFILTER_CLICK'; 
export const _NO_FILTER_SELECTED='NO_FILTER_SELECTED'; 
export const _INVALID_CUSTOMER='INVALID_CUSTOMER';  




export const _ON_INVOICE_DISPLAY_CHANGE='ON_INVOICE_DISPLAY_CHANGE'; 
export const _CHANGE_INVOICE_FILTER='CHANGE_INVOICE_FILTER'; 
export const _SELECT_INVOICE='SELECT_INVOICE'; 
export const _BILLING_INVOICE_DETAILS_SUCCESS='BILLING_INVOICE_DETAILS_SUCCESS'; 
export const _NAVIGATE_SUCCESS='NAVIGATE_SUCCESS'; 
export const _RESPONSE_SUCCESS = "INFO";
export const _RESPONSE_FAILURE = "ERROR";
