databaseChangeLog:
  - logicalFilePath: ../changelog/IAN-73246_MSM32515.yml
  - changeSet:
       id: 32515
       author: 203168
       preConditions:
         - onFail: MARK_RAN
         - not:
            tableExists:
              tableName: malopsaud
       changes:
         dbms: h2, oracle
         endDelimiter: \nGO
         splitStatements: false
         sql: create table malopsaud (
              cmpcod varchar(6) NOT NULL,
              audseq int4 NOT NULL,
              actn varchar(200),
              adtnam varchar(200),
              adtver jsonb,
              chggrpdet jsonb,
              chggrps varchar(2000),
              stn varchar(4),
              trgpnt varchar(200),
              txnactn varchar(200),
              txntim timestamp,
              txntimstn varchar(200),
              txnzontim varchar(200),
              txntimutc timestamp,
              usr varchar(200),
              addinf varchar(200),
              usrrol varchar(200),
              malidr varchar(29),
              constraint malopsaud_pk primary key (audseq,cmpcod)
              );
             comment on table malopsaud is 'table to keep the audit details while updating mail details';
             comment on column malopsaud.cmpcod is 'company code';
             comment on column malopsaud.audseq is 'key generated using the sequence malopsaud_seq';
             comment on column malopsaud.actn is 'action';
             comment on column malopsaud.adtnam is 'audit name';
             comment on column malopsaud.adtver is 'audit version';
             comment on column malopsaud.chggrpdet is 'change group details';
             comment on column malopsaud.chggrps is 'change groups';
             comment on column malopsaud.stn is 'station';
             comment on column malopsaud.trgpnt is 'trigger point';
             comment on column malopsaud.txnactn is 'transaction action';
             comment on column malopsaud.txntim is 'transaction time';
             comment on column malopsaud.txntimstn is 'station transaction time';
             comment on column malopsaud.txnzontim is 'transaction zone time';
             comment on column malopsaud.txntimutc is 'transaction time in utc';
             comment on column malopsaud.usr is 'user';
             comment on column malopsaud.addinf is 'additional information';
             comment on column malopsaud.usrrol is 'user role group';
             comment on column malopsaud.malidr is 'malidr';