databaseChangeLog:
  - logicalFilePath: ../changelog/IAN-73313_MSM32520.yml
  - changeSet:
       id: 32520
       author: a-10552
       preConditions:
         - onFail: MARK_RAN
         - tableExists:
              tableName: MALFLTCONRTG
       changes:
         dbms: h2, oracle
         endDelimiter: \nGO
         splitStatements: false
         sql: ALTER TABLE  MALFLTCONRTG ADD COLUMN IF NOT EXISTS lstupdtim timestamp(3) NULL;  
              ALTER TABLE MALFLTCONRTG ADD COLUMN IF NOT EXISTS lstupdusr varchar(50) NULL;