databaseChangeLog:
  - include:
      file: changelog/tracking-business-1.0.yaml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-37905_MSM27650.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-39671_MSM27896.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-34181_MSM27867.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-39708_MSM27995.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-41664_MSM28155.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-41664_MSM28181.yml
      relativeToChangelogFile: true