/*
 * CN51SummaryPK.java Created on Dec 29, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.gpabilling;

import java.io.Serializable;

import javax.persistence.Embeddable;


/**
 * @author A-1556
 *
 */
@Embeddable
public class CN51SummaryPK implements Serializable{
	/**
	 * The company Code
	 */
    private String companyCode;

    /**
     * The billing Period
     */
    private String invoiceNumber;

    /**
     * The GPA Code
     */
    private String gpaCode;

    private int invSerialNumber;


    /**
     * Default constructor
     *
     */
    public CN51SummaryPK(){
    }
	/**
	 *
	 * @param companyCode
	 * @param invoiceNumber
	 * @param gpaCode
	 */
    public CN51SummaryPK(String companyCode, String invoiceNumber,
    		int invSerialNumber,String gpaCode) {
    	this.companyCode=companyCode;
    	this.invoiceNumber=invoiceNumber;
    	this.invSerialNumber=invSerialNumber;
    	this.gpaCode=gpaCode;
    }

    /**
     * @param other
     * @return boolean
     */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null){
			isEqual = this.hashCode() == other.hashCode();
		}
		return isEqual;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(invoiceNumber).
				append(invSerialNumber).
				append(gpaCode).
				toString().hashCode();
	}


	/**
	 * 
	 * @param invoiceNumber
	 */
	public void setInvoiceNumber(java.lang.String invoiceNumber) {
		this.invoiceNumber=invoiceNumber;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	/**
	 * 
	 * @param gpaCode
	 */
	public void setGpaCode(java.lang.String gpaCode) {
		this.gpaCode=gpaCode;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getGpaCode() {
		return this.gpaCode;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	
	/**
	 * 	Getter for invSerialNumber 
	 *	Added by : A-6991 on 22-Sep-2017
	 * 	Used for : ICRD-211662
	 */
	public int getInvSerialNumber() {
		return invSerialNumber;
	}
	/**
	 *  @param invSerialNumber the invSerialNumber to set
	 * 	Setter for invSerialNumber 
	 *	Added by : A-6991 on 22-Sep-2017
	 * 	Used for : ICRD-211662
	 */
	public void setInvSerialNumber(int invSerialNumber) {
		this.invSerialNumber = invSerialNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(80);
		sbul.append("CN51SummaryPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', gpaCode '").append(this.gpaCode);
		sbul.append("', invSerialNumber '").append(this.invSerialNumber);
		sbul.append("', invoiceNumber '").append(this.invoiceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
	
}
