/*
 * CN51DetailsPK.java Created on Dec 29, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.gpabilling;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.SequenceKeyGenerator;

/**
 * @author A-1556
 *
 */
@SequenceKeyGenerator(name="ID_GEN",sequence="MALMRAGPAC51DTL_SEQ")
@Embeddable
public class CN51DetailsPK implements Serializable{

	/**
	 * The company Code
	 */
    private String companyCode;

    /**
     * The billing Period
     */
    private String invoiceNumber;

    /**
     * The GPA Code
     */
    private String gpaCode;

    /**
     * The sequence number
     */
    private int sequenceNumber;

    /**
     * Default constructor
     *
     */
    private int invSerialNumber;
    
    public CN51DetailsPK(){
    }

    /**
     *
     * @param companyCode
     * @param invoiceNumber
     * @param gpaCode
     * @param sequenceNumber
     */
    public CN51DetailsPK(String companyCode, String invoiceNumber,
            String gpaCode,int invSerialNumber,int sequenceNumber) {
    	this.companyCode=companyCode;
    	this.invoiceNumber=invoiceNumber;
    	this.gpaCode=gpaCode;
    	this.invSerialNumber=invSerialNumber;
    	this.sequenceNumber=sequenceNumber;
    }

    /**
     * @param other
     * @return boolean
     */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null){
			isEqual = this.hashCode() == other.hashCode();
		}
		return isEqual;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(invoiceNumber).
				append(gpaCode).
				append(invSerialNumber).
				append(sequenceNumber).
				toString().hashCode();
	}

	/**
	 * 
	 * @param invoiceNumber
	 */
	public void setInvoiceNumber(java.lang.String invoiceNumber) {
		this.invoiceNumber=invoiceNumber;
	}

	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "INVNUM")
	public java.lang.String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	/**
	 * 
	 * @param sequenceNumber
	 */
	public void setSequenceNumber(int sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}

	/**
	 * 
	 * @return
	 */
	 @Key(generator = "ID_GEN", startAt = "1" )
	public int getSequenceNumber() {
		return this.sequenceNumber;
	}

	/**
	 * 
	 * @param gpaCode
	 */
	public void setGpaCode(java.lang.String gpaCode) {
		this.gpaCode=gpaCode;
	}

	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "GPACOD")
	public java.lang.String getGpaCode() {
		return this.gpaCode;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(106);
		sbul.append("CN51DetailsPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', gpaCode '").append(this.gpaCode);
		sbul.append("', invoiceNumber '").append(this.invoiceNumber);
		sbul.append("', invSerialNumber '").append(this.invSerialNumber);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}

	/**
	 * 	Getter for invSerialNumber 
	 *	Added by : A-6991 on 22-Sep-2017
	 * 	Used for : ICRD-211662
	 */
	@KeyCondition(column = "INVSERNUM")
	public int getInvSerialNumber() {
		return invSerialNumber;
	}

	/**
	 *  @param invSerialNumber the invSerialNumber to set
	 * 	Setter for invSerialNumber 
	 *	Added by : A-6991 on 22-Sep-2017
	 * 	Used for : ICRD-211662
	 */
	public void setInvSerialNumber(int invSerialNumber) {
		this.invSerialNumber = invSerialNumber;
	}
}
