/**
 * GPABillingSettlementDetailsPK.java Created on Mar 30, 2012
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.gpabilling;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author a-4823
 *
 */
@KeyTable(table = "MALMRAGPASTLDTLKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "MALMRAGPASTLDTLKEY", key = "STL_SERNUM")
@Embeddable
public class GPABillingSettlementDetailsPK implements Serializable{

	private String companyCode;
	private String gpaCode;
	private String settlementReferenceNumber;
	private int settlementSequenceNumber;
	private int serialNumber;
	//default constructor
	public GPABillingSettlementDetailsPK(){
		
	}
	/**
	 * 
	 * @param companyCode
	 * @param gpaCode
	 * @param settlementReferenceNumber
	 * @param settlementSequenceNumber
	 * @param serialNumber
	 */
	public GPABillingSettlementDetailsPK(String companyCode,String gpaCode,
			String settlementReferenceNumber,int  settlementSequenceNumber,int serialNumber){
		this.companyCode = companyCode;
		this.gpaCode = gpaCode;
		this.settlementReferenceNumber = settlementReferenceNumber;
		this.settlementSequenceNumber = settlementSequenceNumber;
		this.serialNumber = serialNumber; 		
	}
	@KeyCondition(column = "CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode the companyCode to set
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	@KeyCondition(column = "GPACOD")
	public String getGpaCode() {
		return gpaCode;
	}
	/**
	 * @param gpaCode the gpaCode to set
	 */
	public void setGpaCode(String gpaCode) {
		this.gpaCode = gpaCode;
	}
	@KeyCondition(column = "STLREFNUM")
	public String getSettlementReferenceNumber() {
		return settlementReferenceNumber;
	}
	/**
	 * @param settlementReferenceNumber the settlementReferenceNumber to set
	 */
	public void setSettlementReferenceNumber(String settlementReferenceNumber) {
		this.settlementReferenceNumber = settlementReferenceNumber;
	}
	@KeyCondition(column = "SEQNUM")
	public int getSettlementSequenceNumber() {
		return settlementSequenceNumber;
	}
	/**
	 * @param settlementSequenceNumber the settlementSequenceNumber to set
	 */
	public void setSettlementSequenceNumber(int settlementSequenceNumber) {
		this.settlementSequenceNumber = settlementSequenceNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public int getSerialNumber() {
		return serialNumber;
	}
	/**
	 * @param serialNumber the serialNumber to set
	 */
	public void setSerialNumber(int serialNumber) {
		this.serialNumber = serialNumber;
	}
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
		//return (hashCode() == other.hashCode());
	}
	/**
	 * 
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).    		
		append(gpaCode).append(settlementReferenceNumber).
		append(settlementSequenceNumber).append(serialNumber).
		toString().hashCode();
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(168);
		sbul.append("GPABillingSettlementDetailsPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', gpaCode '").append(this.gpaCode);
		sbul.append("', serialNumber '").append(this.serialNumber);
		sbul.append("', settlementReferenceNumber '").append(
				this.settlementReferenceNumber);
		sbul.append("', settlementSequenceNumber '").append(
				this.settlementSequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
