/*
 * AccessoriesStockConfigPK.java Created on Aug 1, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.stock;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-1347
 *
 */
@Embeddable
public class AccessoriesStockConfigPK implements Serializable{


	/**
     * companyCode
     */
	private String companyCode;	
    /**
     * accessoryCode
     */
	private String accessoryCode;
    /**
     * stationCode
     */
	private String stationCode;
	/**
     * airlineCode
     */
	private int airlineIdentifier;
	
	

	public AccessoriesStockConfigPK() {

	}

	public AccessoriesStockConfigPK(
	        String companyCode, String accessoryCode,
	        String stationCode, int airlineIdentifier) {
		this.companyCode = companyCode;
		this.accessoryCode = accessoryCode;
		this.stationCode = stationCode;
		this.airlineIdentifier = airlineIdentifier;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(accessoryCode)
				.append(stationCode).append(airlineIdentifier).toString()
				.hashCode();
	}

	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	public void setStationCode(java.lang.String stationCode) {
		this.stationCode=stationCode;
	}

	public java.lang.String getStationCode() {
		return this.stationCode;
	}

	public void setAccessoryCode(java.lang.String accessoryCode) {
		this.accessoryCode=accessoryCode;
	}

	public java.lang.String getAccessoryCode() {
		return this.accessoryCode;
	}

	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier=airlineIdentifier;
	}

	public int getAirlineIdentifier() {
		return this.airlineIdentifier;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:18 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(124);
		sbul.append("AccessoriesStockConfigPK [ ");
		sbul.append("accessoryCode '").append(this.accessoryCode);
		sbul.append("', airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', stationCode '").append(this.stationCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
