package com.ibsplc.neoicargo.mail.model;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;
import com.ibsplc.icargo.business.shared.defaults.onetime.vo.OneTimeVO;
import com.ibsplc.icargo.framework.util.time.LocalDate;
import com.ibsplc.icargo.framework.util.unit.Measure;
import com.ibsplc.icargo.framework.util.unit.UnitConstants;
import com.ibsplc.xibase.server.framework.persistence.query.Page;
import com.ibsplc.xibase.server.framework.vo.AbstractVO;
import lombok.Getter;
import lombok.Setter;
import com.ibsplc.neoicargo.common.modal.BaseModel;

@Setter
@Getter
public class ConsignmentDocumentModel extends BaseModel {
	private String companyCode;
	private String consignmentNumber;
	private String paCode;
	private int consignmentSequenceNumber;
	private LocalDate consignmentDate;
	private String airportCode;
	private boolean isScanned;
	private String type;
	private String subType;
	private String operation;
	private Collection<RoutingInConsignmentModel> routingInConsignmentVOs;
	private Page<MailInConsignmentModel> mailInConsignmentVOs;
	private String lastUpdateUser;
	private LocalDate lastUpdateTime;
	private String remarks;
	private int statedBags;
	private Measure statedWeight;
	private String operationFlag;
	private Collection<MailInConsignmentModel> mailInConsignmentcollVOs;
	private String orgin;
	private String destination;
	private String despatchDate;
	private ArrayList<String> subsequentFlight;
	private String pou;
	private String orginCity;
	private String destinationCity;
	private String orginAirport;
	private String fltDate;
	private String dateOfDept;
	private String flight;
	private String carrierCode;
	private String destPort;
	private String reportType;
	private String mailCategory;
	private String categoryDescription;
	private Collection<MailInConsignmentModel> mailInConsignment;
	private String destinationOfficeOfExchange;
	private String originOfficeOfExchange;
	private int year;
	private String dsnNumber;
	private String uldNumber;
	private String mailSubClass;
	private String mailClass;
	private String operatorOrigin;
	private String operatorDestination;
	private String ooeDescription;
	private String doeDescription;
	private String consignmentPriority;
	private String transportationMeans;
	private String flightDetails;
	private String flightRoute;
	private LocalDate firstFlightDepartureDate;
	private String airlineCode;
	private int totalSacks;
	private Measure totalWeight;
	private Measure totalLetterWeight;
	private Measure totalParcelWeight;
	private String currency;
	private double rate;
	private String isUspsPerformed;
	private String mcaNumber;
	private Collection<ConsignmentScreeningModel> consignementScreeningVOs;
	private String securityStatusParty;
	private String securityStatusCode;
	private String additionalSecurityInfo;
	private LocalDate securityStatusDate;
	private String applicableRegTransportDirection;
	private String applicableRegBorderAgencyAuthority;
	private String applicableRegReferenceID;
	private String countryCode;
	private String applicableRegFlag;
	private String consignmentOrigin;
	private String consigmentDest;
	private Map<String, Collection<OneTimeVO>> oneTimes;
	private String airlineName;
	private String flightDates;
	private int subClassLC;
	private int subClassCP;
	private int subClassEMS;
	private String airportOftransShipment;
	private String paName;
	private boolean priorityMalExists;
	private boolean airMalExists;
	private boolean priority;
	private boolean nonPriority;
	private boolean byAir;
	private boolean bySal;
	private boolean bySurface;
	private boolean priorityByAir;
	private boolean nonPrioritySurface;
	private boolean parcels;
	private boolean ems;
	private String tranAirportName;
	private String pouName;
	private int lineCount;
	private String shipmentPrefix;
	private String masterDocumentNumber;
	private String consignmentIssuerName;
	private String shipperUpuCode;
	private String consigneeUpuCode;
	private String originUpuCode;
	private String destinationUpuCode;
	private String consignmentMasterDocumentNumber;
	private Collection<ConsignmentDocumentModel> existingConsignmentDocumentVOs;
	private Collection<RoutingInConsignmentModel> acceptanceInfo;
	private Collection<RoutingInConsignmentModel> routingInfo;
	private String securityReasonCode;
	private String agentType;
	private String agentID;
	private String expiryDate;
	private String isoCountryCode;
	private String csgIssuerName;
	private String mstAddionalSecurityInfo;
	private String source;
	private String triggerPoint;
	private boolean ignoreWarnings;
}
