package com.ibsplc.neoicargo.mail.model;

import java.util.Collection;
import com.ibsplc.icargo.framework.util.currency.Money;
import com.ibsplc.icargo.framework.util.time.LocalDate;
import com.ibsplc.icargo.framework.util.unit.Measure;
import com.ibsplc.xibase.server.framework.vo.AbstractVO;
import lombok.Getter;
import lombok.Setter;
import com.ibsplc.neoicargo.common.modal.BaseModel;

@Setter
@Getter
public class ContainerModel extends BaseModel {
	private String containerNumber;
	private String type;
	private String finalDestination;
	private LocalDate assignedDate;
	private String assignedUser;
	private String onwardRoute;
	private String onwardFlights;
	private int bags;
	private Measure weight;
	private String remarks;
	private String paBuiltFlag;
	private String operationFlag;
	private int carrierId;
	private String flightNumber;
	private long eventSequenceNumber;
	private long flightSequenceNumber;
	private int segmentSerialNumber;
	private int legSerialNumber;
	private String companyCode;
	private String assignedPort;
	private String assignmentFlag;
	private String lastUpdateUser;
	private String acceptanceFlag;
	private boolean isReassign;
	private String carrierCode;
	private LocalDate flightDate;
	private boolean isOffload;
	private String carditKey;
	private String consignmentDocumentNumber;
	private LocalDate consignmentDate;
	private String carditRecipientId;
	private int resditEventSeqNum;
	private String resditEventPort;
	private String handedOverPartner;
	private boolean isFlightClosureCheckNeeded;
	private String offloadedReason;
	private String offloadedRemarks;
	private String offloadedDescription;
	private String pou;
	private String pol;
	private String warehouseCode;
	private String locationCode;
	private String offloadFlag;
	private String ownAirlineCode;
	private int ownAirlineId;
	private String arrivedStatus;
	private String transferFlag;
	private boolean isPreassignNeeded;
	private String paBuiltOpenedFlag;
	private boolean overrideUMSFlag;
	private LocalDate operationTime;
	private String resditEventString;
	private int resditEventSequenceNumber;
	private String paCode;
	private LocalDate resditEventUTCDate;
	private String eventCode;
	private LocalDate eventTime;
	private String typeCode;
	private String equipmentQualifier;
	private Measure containerWeight;
	private String measurementDimension;
	private String codeListResponsibleAgency;
	private String typeCodeListResponsibleAgency;
	private String containerSealNumber;
	private Measure actualWeight;
	private String fromCarrier;
	private String fromFltNum;
	private LocalDate fromFltDat;
	private String contentId;
	private String transactionCode;
	private boolean oflToRsnFlag;
	private String flightStatus;
	private boolean foundTransfer;
	private String screeningUser;
	private boolean fromDeviationList;
	private LocalDate GHTtime;
	private boolean fromCarditList;
	private boolean fromWSCL;
	private boolean deleteEmptyContainer;
	private String retainFlag;
	private long frmFltSeqNum;
	private int frmSegSerNum;
	private boolean exportTransfer;
	private boolean handoverReceived;
	private boolean remove;
	private boolean mailbagPresent;
	private LocalDate firstAssignDate;
	private String plannedFlightCarrierCode;
	private int plannedFlightNum;
	private LocalDate plannedFlightDate;
	private String plannedFlightAndDate;
	private double expectedOrProvisionalCharge;
	private String position;
	private String messageVersion;
	private String weighingDeviceName;
	private LocalDate weighingTime;
	private String transactionLevel;
	private Money provosionalCharge;
	private String baseCurrency;
	private String rateAvailforallMailbags;
	private String acceptedPort;
	private int receivedBags;
	private Measure receivedWeight;
	private LocalDate lastUpdateTime;
	private LocalDate uldLastUpdateTime;
	private String uldLastUpdateUser;
	private String deliveredStatus;
	private Collection<OnwardRoutingModel> onwardRoutings;
	private Collection<BookingTimeModel> bookingTimeVOs;
	private String containerJnyID;
	private String shipperBuiltCode;
	private String intact;
	private String transitFlag;
	private String releasedFlag;
	private LocalDate scannedDate;
	private Collection<String> offloadedInfo;
	private String subclassGroup;
	private int noOfDaysInCurrentLoc;
	private String mailSource;
	private String actualWeightUnit;
	private boolean uldTobarrow;
	private boolean barrowToUld;
	private boolean transferAudit;
	private String prevFlightPou;
	private String uldFulIndFlag;
	private long uldReferenceNo;
	private String expClsflg;
	private String hbaMarked;
	private String planStatus;
	private int offloadCount;
	private String source;
	private boolean isContainerDestChanged;
	private boolean transStatus;
	private String triggerPoint;
	private boolean ignoreWarnings;
}
