package com.ibsplc.neoicargo.mail.model;

import java.util.Collection;
import com.ibsplc.icargo.framework.util.time.LocalDate;
import com.ibsplc.icargo.framework.util.unit.Measure;
import com.ibsplc.xibase.server.framework.vo.AbstractVO;
import lombok.Getter;
import lombok.Setter;
import com.ibsplc.neoicargo.common.modal.BaseModel;

@Setter
@Getter
public class DespatchDetailsModel extends BaseModel {
	private String companyCode;
	private String dsn;
	private int acceptedBags;
	private Measure acceptedWeight;
	private String mailClass;
	private String mailCategoryCode;
	private String containerType;
	private String mailSubclass;
	private String acceptanceFlag;
	private String containerNumber;
	private String uldNumber;
	private String pou;
	private String destination;
	private boolean isOffload;
	private String ownAirlineCode;
	private int legSerialNumber;
	private LocalDate acceptedDate;
	private String acceptedUser;
	private String pltEnabledFlag;
	private int carrierId;
	private String flightNumber;
	private long flightSequenceNumber;
	private int segmentSerialNumber;
	private String operationalFlag;
	private String consignmentNumber;
	private LocalDate consignmentDate;
	private String originOfficeOfExchange;
	private String destinationOfficeOfExchange;
	private int statedBags;
	private Measure statedWeight;
	private int year;
	private int prevAcceptedBags;
	private Measure prevAcceptedWeight;
	private String containerForInventory;
	private String containerTypeAtAirport;
	private int prevStatedBags;
	private Measure prevStatedWeight;
	private LocalDate receivedDate;
	private String offloadedReason;
	private String offloadedRemarks;
	private String offloadedDescription;
	private String airportCode;
	private String carrierCode;
	private LocalDate flightDate;
	private String paCode;
	private int consignmentSequenceNumber;
	private int deliveredBags;
	private Measure deliveredWeight;
	private int receivedBags;
	private Measure receivedWeight;
	private int prevDeliveredBags;
	private Measure prevDeliveredWeight;
	private int prevReceivedBags;
	private Measure prevReceivedWeight;
	private String offloadFlag;
	private String operationType;
	private String transferFlag;
	private String paBuiltFlag;
	private Collection<String> containers;
	private Measure statedVolume;
	private String capNotAcceptedStatus;
	private String latestStatus;
	private int offloadedBags;
	private Measure offloadedWeight;
	private boolean delivered;
	private Measure acceptedVolume;
	private String transactionCode;
	private int acceptedPcsToDisplay;
	private Measure acceptedWgtToDisplay;
	private boolean isNewInbound;
	private String ubrNumber;
	private LocalDate bookingLastUpdateTime;
	private LocalDate bookingFlightDetailLastUpdTime;
	private String errorType;
	private String errorDescription;
	private String acknowledge;
	private String displayLabel;
	private int transferredPieces;
	private Measure transferredWeight;
	private boolean istransfermail;
	private int alreadyTransferredPieces;
	private Measure alreadyTransferredWeight;
	private boolean isDomesticTransfer;
	private String remarks;
	private String csgOrigin;
	private String csgDestination;
	private String operationFlag;
	private String triggerPoint;
	private boolean ignoreWarnings;
}
