package com.ibsplc.neoicargo.mail.model;

import com.ibsplc.icargo.framework.util.time.LocalDate;
import com.ibsplc.xibase.server.framework.vo.AbstractVO;
import java.util.Collection;
import com.ibsplc.icargo.business.flight.operation.vo.FlightValidationVO;
import com.ibsplc.icargo.framework.util.unit.Measure;
import lombok.Getter;
import lombok.Setter;
import com.ibsplc.neoicargo.common.modal.BaseModel;

@Setter
@Getter
public class MailUploadModel extends BaseModel {
	private String mailSource;
	private String messageVersion;
	private String scanType;
	private String companyCode;
	private String mailCompanyCode;
	private String carrierCode;
	private String flightNumber;
	private LocalDate flightDate;
	private String containerPOU;
	private String containerNumber;
	private String containerType;
	private String containeDescription;
	private String containerPol;
	private String fromCarrierCode;
	private String remarks;
	private String mailTag;
	private String dateTime;
	private String damageCode;
	private String damageRemarks;
	private String offloadReason;
	private String returnCode;
	private String toContainer;
	private String toCarrierCode;
	private String toFlightNumber;
	private LocalDate toFlightDate;
	private String toPOU;
	private String toDestination;
	private String orginOE;
	private String destinationOE;
	private String category;
	private String subClass;
	private int year;
	private int carrierId;
	private String processPoint;
	private String scanUser;
	private boolean isArrived;
	private boolean isAccepted;
	private LocalDate scannedDate;
	private String mailKeyforDisplay;
	private boolean expRsn;
	private String fromPol;
	private String pols;
	private String overrideValidation;
	private String transferFrmFlightNum;
	private long transferFrmFlightSeqNum;
	private LocalDate transferFrmFlightDate;
	private String operationType;
	private String deliverFlag;
	private String warningFlag;
	private String androidFlag;
	private String screeningUser;
	private Collection<MailAttachmentModel> attachments;
	private String containerJourneyId;
	private String uldFullIndicator;
	private String messageSenderIdentifier;
	private String messageRecipientIdentifier;
	private boolean arrivalException;
	private boolean fromErrorHandling;
	private String processPointBeforeArrival;
	private boolean restrictErrorLogging;
	private String rawMessageBlob;
	private String overrideULDVal;
	private String resolveFlagAndroid;
	private boolean rdtProcessing;
	private boolean resolveFromErrorHandling;
	private String storageUnit;
	private LocalDate deviceDateAndTime;
	private String errorCode;
	private boolean forceAccepted;
	private String errorDescription;
	private boolean fromErrorHandlingForForceAcp;
	private Collection<FlightValidationVO> flightValidationVOS;
	private String dsn;
	private String rsn;
	private String scannedPort;
	private String destination;
	private String transactionLevel;
	private String orgin;
	private String highestnumberIndicator;
	private String registeredIndicator;
	private String consignmentDocumentNumber;
	private String paCode;
	private int totalBag;
	private Measure totalWeight;
	private int bags;
	private Measure weight;
	private boolean isIntact;
	private int serialNumber;
	private boolean isFromGHAService;
	private long mailSequenceNumber;
	private String messageType;
	private String eventCode;
	private String totalEventCodes;
	private String nodeName;
	private long msgSequenceNumber;
	private Measure uldActualWeight;
	private long flightSequenceNumber;
	private String cirCode;
	private boolean isDeliverd;
	private String securityMethods;
	private String issuedBy;
	private String operationFlag;
	private String triggerPoint;
	private boolean ignoreWarnings;
}
