/*
 * CustomerGroupLoyaltyProgrammePK.java Created on Aug 1, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.customermanagement.defaults.profile;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-2048
 *
 *
 */
@Embeddable
@KeyTable(table = "CUSGRPLTYPRGKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "CUSGRPLTYPRGKEY", key = "SEQNUM")
public class CustomerGroupLoyaltyProgrammePK implements Serializable  {

	 /**
	  * @param String
	  */

    private String companyCode;
 /**
  * @param String
  */

     private String groupCode;
  /**
   * @param String
   */

    private String loyaltyProgramCode;
 
 /**
  * @param int
  */

    private int sequenceNumber;

    /**
     * Default constructor
     */
	public CustomerGroupLoyaltyProgrammePK() {
	}

	/**
	 * Contructor
	 *
	 * @param companyCode
	 * @param groupCode 
	 * @param loyaltyProgramCode 
	 * @param sequenceNumber 
	 */
    public CustomerGroupLoyaltyProgrammePK(String companyCode, String groupCode,
    		String loyaltyProgramCode,int sequenceNumber) {
    	this.companyCode = companyCode;
    	this.groupCode = groupCode;
    	this.loyaltyProgramCode = loyaltyProgramCode;
    	this.sequenceNumber = sequenceNumber;
    	
	}
/**
 * @param other
 * @return boolean
 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
/**
 * @param 
 * @return int
 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(groupCode).
				append(loyaltyProgramCode).
				append(sequenceNumber).
				toString().hashCode();
	}



	public void setLoyaltyProgramCode(java.lang.String loyaltyProgramCode) {
		this.loyaltyProgramCode=loyaltyProgramCode;
	}
   @KeyCondition(column = "LTYPRGCOD")
	public java.lang.String getLoyaltyProgramCode() {
		return this.loyaltyProgramCode;
	}

	public void setSequenceNumber(int sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
 @Key(generator = "ID_GEN", startAt = "1")
	public int getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setGroupCode(java.lang.String groupCode) {
		this.groupCode=groupCode;
	}
  @KeyCondition(column = "GRPCOD")
	public java.lang.String getGroupCode() {
		return this.groupCode;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
 @KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

/**
 * generated by xibase.tostring plugin at 1 October, 2014 1:13:49 PM IST
 */
@Override
public String toString() {
	StringBuilder sbul = new StringBuilder(131);
	sbul.append("CustomerGroupLoyaltyProgrammePK [ ");
	sbul.append("companyCode '").append(this.companyCode);
	sbul.append("', groupCode '").append(this.groupCode);
	sbul.append("', loyaltyProgramCode '").append(this.loyaltyProgramCode);
	sbul.append("', sequenceNumber '").append(this.sequenceNumber);
	sbul.append("' ]");
	return sbul.toString();
}
}
