/*
 * ExceptionsInFlownSegmentPK.java Created on Dec 28, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.flown;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-2401
 *
 */
@Embeddable
public class ExceptionsInFlownSegmentPK implements Serializable{

	private String billingBasis;

	private String flightNumber;

	private int carrierId;

	private long flightSequenceNumber;

	private int segmentSerialNumber;

	private String exceptionCode;

	private long serialNumber;

	private String companyCode;

	public ExceptionsInFlownSegmentPK(){
	}

	 /**
     *
     * @param companyCode
     * @param carrierId
     * @param flightNumber
     * @param flightSequenceNumber
     * @param segmentSerialNumber
     * @param serialNumber
     * @param billingBasis
     * @param exceptionCode
     *
     */
	public ExceptionsInFlownSegmentPK(String companyCode, int carrierId,
            String flightNumber, long flightSequenceNumber,
            int segmentSerialNumber,long serialNumber,
            String billingBasis,String exceptionCode){

		this.companyCode = companyCode;
        this.carrierId = carrierId;
        this.flightNumber = flightNumber;
        this.flightSequenceNumber = flightSequenceNumber;
        this.segmentSerialNumber = segmentSerialNumber;
        this.billingBasis = billingBasis;
        this.exceptionCode = exceptionCode;
        this.serialNumber = serialNumber;
	}

	/**
     * @param other
     * @return boolean
     */
    public boolean equals(Object other) {
    	boolean isEqual = false;
		if(other != null){
			isEqual = this.hashCode() == other.hashCode();
		}
		return isEqual;
	}

    /**
	 * @return int
	 */
	public int hashCode() {

 		return new StringBuffer(billingBasis).
 				append(flightNumber).
 				append(carrierId).
 				append(exceptionCode).
 				append(flightSequenceNumber).
 				append(segmentSerialNumber).
 				append(serialNumber).
 				append(companyCode).
 				toString().hashCode();
 	}



	/**
	 * 
	 * @param serialNumber
	 */
	public void setSerialNumber(long serialNumber) {
		this.serialNumber=serialNumber;
	}

	/**
	 * 
	 * @return
	 */
	public long getSerialNumber() {
		return this.serialNumber;
	}

	/**
	 * 
	 * @param billingBasis
	 */
	public void setBillingBasis(java.lang.String billingBasis) {
		this.billingBasis=billingBasis;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getBillingBasis() {
		return this.billingBasis;
	}

	/**
	 * 
	 * @param carrierId
	 */
	public void setCarrierId(int carrierId) {
		this.carrierId=carrierId;
	}

	/**
	 * 
	 * @return
	 */
	public int getCarrierId() {
		return this.carrierId;
	}

	/**
	 * 
	 * @param flightNumber
	 */
	public void setFlightNumber(java.lang.String flightNumber) {
		this.flightNumber=flightNumber;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getFlightNumber() {
		return this.flightNumber;
	}

	/**
	 * 
	 * @param exceptionCode
	 */
	public void setExceptionCode(java.lang.String exceptionCode) {
		this.exceptionCode=exceptionCode;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getExceptionCode() {
		return this.exceptionCode;
	}

	/**
	 * 
	 * @param segmentSerialNumber
	 */
	public void setSegmentSerialNumber(int segmentSerialNumber) {
		this.segmentSerialNumber=segmentSerialNumber;
	}

	/**
	 * 
	 * @return
	 */
	public int getSegmentSerialNumber() {
		return this.segmentSerialNumber;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * 
	 * @param flightSequenceNumber
	 */
	public void setFlightSequenceNumber(long flightSequenceNumber) {
		this.flightSequenceNumber=flightSequenceNumber;
	}

	/**
	 * 
	 * @return
	 */
	public long getFlightSequenceNumber() {
		return this.flightSequenceNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(230);
		sbul.append("ExceptionsInFlownSegmentPK [ ");
		sbul.append("billingBasis '").append(this.billingBasis);
		sbul.append("', carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', exceptionCode '").append(this.exceptionCode);
		sbul.append("', flightNumber '").append(this.flightNumber);
		sbul.append("', flightSequenceNumber '").append(
				this.flightSequenceNumber);
		sbul.append("', segmentSerialNumber '")
				.append(this.segmentSerialNumber);
		sbul.append("', serialNumber '").append(this.serialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
