/*
 * FlownSegmentPK.java Created on Dec 29, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.flown;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-1556
 *
 */
@Embeddable
public class FlownSegmentPK implements Serializable {

    /**
     * companyCode
     */
    private String companyCode;
    /**
     * carrierId
     */
    private int carrierId;
    /**
     * flightNumber
     */
    private String flightNumber;
    /**
     * flightSequenceNumber
     */
    private long flightSequenceNumber;
    /**
     * segmentSerialNumber
     */
    private int segmentSerialNumber;

    /**
     *
     */
    public FlownSegmentPK() {
    }

    /**
     *
     * @param companyCode
     * @param carrierId
     * @param flightNumber
     * @param flightSequenceNumber
     * @param segmentSerialNumber
     */
    public FlownSegmentPK(String companyCode, int carrierId,
            String flightNumber, long flightSequenceNumber,
            int segmentSerialNumber) {
        this.companyCode = companyCode;
        this.carrierId = carrierId;
        this.flightNumber = flightNumber;
        this.flightSequenceNumber = flightSequenceNumber;
        this.segmentSerialNumber = segmentSerialNumber;
    }
    /**
     * @param other
     * @return boolean
     */
    public boolean equals(Object other) {
    	boolean isEqual = false;
		if(other != null){
			isEqual = this.hashCode() == other.hashCode();
		}
		return isEqual;
	}

	/**
	 * @return int
	 */
	public int hashCode() {

		return new StringBuffer(companyCode).
				append(carrierId).
				append(flightNumber).
				append(flightSequenceNumber).
				append(segmentSerialNumber).
				toString().hashCode();
	}


	/**
	 * 
	 * @param flightNumber
	 */
	public void setFlightNumber(java.lang.String flightNumber) {
		this.flightNumber=flightNumber;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getFlightNumber() {
		return this.flightNumber;
	}
	
	/**
	 * 
	 * @param carrierId
	 */
	public void setCarrierId(int carrierId) {
		this.carrierId=carrierId;
	}

	/**
	 * 
	 * @return
	 */
	public int getCarrierId() {
		return this.carrierId;
	}

	/**
	 * 
	 * @param segmentSerialNumber
	 */
	public void setSegmentSerialNumber(int segmentSerialNumber) {
		this.segmentSerialNumber=segmentSerialNumber;
	}

	/**
	 * 
	 * @return
	 */
	public int getSegmentSerialNumber() {
		return this.segmentSerialNumber;
	}

	/**
	 * 
	 * @param flightSequenceNumber
	 */
	public void setFlightSequenceNumber(long flightSequenceNumber) {
		this.flightSequenceNumber=flightSequenceNumber;
	}

	/**
	 * 
	 * @return
	 */
	public long getFlightSequenceNumber() {
		return this.flightSequenceNumber;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(145);
		sbul.append("FlownSegmentPK [ ");
		sbul.append("carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', flightNumber '").append(this.flightNumber);
		sbul.append("', flightSequenceNumber '").append(
				this.flightSequenceNumber);
		sbul.append("', segmentSerialNumber '")
				.append(this.segmentSerialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
