spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
    show-sql: true
  datasource:
    platform: postgres
    password: 'postgres'
    username: 'postgres'
    url: "jdbc:postgresql://192.168.2.4:32543/postgres?currentSchema=rman"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      max-lifetime: 30000
      idle-timeout: 20000
      connection-timeout: 5000
      pool-name: 'release-manager-db-pool'
cxf:
  path: '/rest'
neo:
  logging:
    appenders: console
bitbucket:
  repositoryUrl: "http://bitbucket.ibsplc.com"
  user: "icargo-release"
  password: "Icargo-release"
logging:
  level:
    com.ibsplc.neoicargo.relmgr: DEBUG