#!/usr/bin/env bash

#
# Script to run standalone outside k8s env for testing purpose
#

export DEPCTRL_HOSTED_TENANTS="AV"
export DEPCTRL_DEPLOYMENT_DEFN='eyJhcnRpZmFjdElkIjoiYXV0aC1zZXJ2aWNlLWJ1c2luZXNzIiwiYXJ0aWZhY3RWZXJzaW9uIjoiMWU4NjUwYyIsImJyYW5jaCI6Im1hc3RlciIsImNvbnRleHRQYXRoIjoiL2F1dGgiLCJkZXNjcmlwdGlvbiI6IkRvbWFpbiA6IHNlY3VyaXR5IC0gQXV0aGVudGljYXRpb24gU2VydmljZSAtIFNoYXJpa2EgTiAtIFB1bGwgcmVxdWVzdCAjNjogRmVhdHVyZS9JQU4tMjM0MlxuXG5NZXJnZSBpbiBJQ05FTy9pY2FyZ28tbmVvLWF1dGgtc2VydmljZSBmcm9tIGZlYXR1cmUvSUFOLTIzNDIgdG8gbWFzdGVyXG5cbiogY29tbWl0ICdkNjQzMzUyMzU1MWM1NGJlNzBhNWQxNzE0NGVjNTgzOTI1ODE2NjczJzpcbiAgSUFOLTIzNDItQ1JROiBtb2RpZmllZCBwb20geG1sXG4gIElBTi0yMzQyLUNSUTpSZW1vdmVkIGZyYW1ld29yayBmcm9tIGNvbXBvbmUiLCJoZWFsdGhFbmRwb2ludCI6Ii9hdXRoL3dlYi9hY3R1YXRvci9oZWFsdGgiLCJob3N0c0VudGVycHJpc2VBcGkiOmZhbHNlLCJob3N0c1ByaXZhdGVBcGkiOnRydWUsImhvc3RzUHVibGljQXBpIjpmYWxzZSwiaW1hZ2UiOiJzaW1wbGUtc3ByaW5nOmxhdGVzdCIsInBvcnQiOjgwODAsInByb2Nlc3NUeXBlIjoiSkFWQSIsInJlbGVhc2VUaW1lIjoiMjAyMS0wMi0wNFQwNzoxODo0OS42NDA3NjFaIiwic2VydmljZU5hbWUiOiJhdXRoLXNlcnZpY2UtYnVzaW5lc3MiLCJzZXJ2aWNlVHlwZSI6IkRPTUFJTl9TRVJWSUNFIn0='
export DEPCTRL_APPLICATION_PROFILE="nfr"
export DEPCTRL_APPLICATION_NAMESPACE="nfr"
export DEPCTRL_CONFIG_SERVER_URL="http://neo-config-server/config-service"
export DEPCTRL_INIT_DEPENDENCIES="neo-admin-business"
export DEPCTRL_CONFIG_SERVER_ARTIFACT_ID="neo-config-server"

java -jar target/icargo-neo-init-controller-1.1.0.jar --depctrl.action=init-container
