---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "logstash-configmap-%s" .Values.environmentProfile | lower | quote }}
  namespace: {{ .Values.namespace | quote }}
data:
  applogs.conf: |
    input {
    udp {
      port => {{ .Values.logstash.udpPort }}
      id => "icargo-neo-udp-logger-service"
      codec => "json"
      queue_size => 16384
      workers => 2
      enable_metric => false
    }      
    }
{{- if and $.Values.awsElasticSearch.useAmazonLogstashPlugin }}
    output {  
      amazon_es {
        index => "{{ get (get $.Values.environment .Values.environmentProfile) "elasticsearchIndexPrefix"  | default "icargo_log_index" }}-%{+yyyyMMdd}"
        hosts => [ {{ $.Values.awsElasticSearch.vpcEndpoint | quote }}  ]
        region => [ {{ $.Values.awsElasticSearch.region | quote }} ]
        {{- if not $.Values.awsElasticSearch.awsAccessKeyId  }}
        aws_access_key_id  => {{ $.Values.awsElasticSearch.awsAccessKeyId }}
        aws_secret_access_key => {{ $.Values.awsElasticSearch.awsSecretAccessKey }}
        {{- end }}
      }
    }
{{- else }}    
    output {
      elasticsearch {
        hosts => [{{ printf "%s:443" .Values.awsElasticSearch.vpcEndpoint | quote }}]
        ssl => true
        index => "{{ get (get .Values.environment .Values.environmentProfile) "elasticsearchIndexPrefix"  | default "icargo_log_index" }}-%{+yyyyMMdd}"
        ilm_enabled => false
        template =>  '/usr/share/logstash/config/template.json'
        #template_name => 'icargo_logstash'
        #ilm_rollover_alias => "{{ get (get $.Values.environment .Values.environmentProfile) "elasticsearchIndexPrefix"  | default "icargo_log" }}"
      }
    }
{{- end }}
  accesslogs.conf: |
    input {
    udp {
      port => {{ .Values.logstash.accesslog.udpPort }}
      id => "icargo-neo-udp-access-logger-service"
      codec => "json"
      queue_size => 16384
      workers => 2
      enable_metric => false
    }      
    }
{{- if and $.Values.awsElasticSearch.useAmazonLogstashPlugin }}
    output {  
      amazon_es {
        index => "{{ get (get $.Values.environment .Values.environmentProfile) "elasticsearchAccessIndexPrefix"  | default "icargo_acces_log_index" }}-%{+yyyyMMdd}"
        hosts => [ {{ $.Values.awsElasticSearch.vpcEndpoint | quote }}  ]
        region => [ {{ $.Values.awsElasticSearch.region | quote }} ]
        {{- if not $.Values.awsElasticSearch.awsAccessKeyId  }}
        aws_access_key_id  => {{ $.Values.awsElasticSearch.awsAccessKeyId }}
        aws_secret_access_key => {{ $.Values.awsElasticSearch.awsSecretAccessKey }}
        {{- end }}
      }
    }
{{- else }}    
    output {
      elasticsearch {
        hosts => [{{ printf "%s:443" .Values.awsElasticSearch.vpcEndpoint | quote }}]
        ssl => true
        index => "{{ get (get .Values.environment .Values.environmentProfile) "elasticsearchAccessIndexPrefix"  | default "icargo_acces_log_index" }}-%{+yyyyMMdd}"
        ilm_enabled => false
        template =>  '/usr/share/logstash/config/template.json'
        #template_name => 'icargo_logstash'
        #ilm_rollover_alias => "{{ get (get $.Values.environment .Values.environmentProfile) "elasticsearchIndexPrefix"  | default "icargo_log" }}"
      }
    }
{{- end }}
  pipelines.yml: |
   - pipeline.id: app-logs
     path.config: "/usr/share/logstash/pipeline/applogs.conf"    
   - pipeline.id: access-logs
     path.config: "/usr/share/logstash/pipeline/accesslogs.conf"      
  logstash.yml: |
    http.host: "0.0.0.0"
    #path.config: /usr/share/logstash/pipeline
    pipeline.ordered: auto
  jvm.options: |
    ## JVM configuration

    # Xms represents the initial size of total heap space
    # Xmx represents the maximum size of total heap space

    -Xms1g
    -Xmx1g    
  template.json: |
    {
      "template" : "{{ get (get $.Values.environment .Values.environmentProfile) "elasticsearchIndexPrefix"  | default "icargo_log_index" }}-*",
      "version" : 70001,
      "settings" : {
        "number_of_shards" : "1",
        "number_of_replicas" : "0",
        "refresh_interval" : "5s"
      }
    }   
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "curator-configmap-%s" .Values.environmentProfile | lower | quote }}
  namespace: {{ .Values.namespace | quote }}
data:
  curator-cfg.yml: |
    client:
      hosts:
        - elasticsearch
      port: 80
  curator-actions.yml: |
    actions:
      1:
        action: delete_indices
        description: Delete TxProbe Indices
        options:
          ignore_empty_list: True
          timeout_override: 180
          continue_if_exception: True
          disable_action: False
        filters:
          - filtertype: pattern
            kind: prefix
            value: icargo_txprobe_index
          - filtertype: age
            source: name
            direction: older
            timestring: '-%Y%m%d%H'
            unit: hours
            unit_count: ${TXP_INDEX_RETENTION_HRS:25}
      2:
        action: delete_indices
        description: Delete Log Indices
        options:
          ignore_empty_list: True
          timeout_override: 180
          continue_if_exception: True
          disable_action: False
        filters:
          - filtertype: pattern
            kind: prefix
            value: {{ get (get .Values.environment .Values.environmentProfile) "elasticsearchIndexPrefix"  | default "icargo_log_index" }}
          - filtertype: age
            source: name
            direction: older
            timestring: '-%Y%m%d'
            unit: days
            unit_count: ${LOG_INDEX_RETENTION_DAYS:8}
      3:
        action: delete_access_indices
        description: Delete Log Indices
        options:
          ignore_empty_list: True
          timeout_override: 180
          continue_if_exception: True
          disable_action: False
        filters:
          - filtertype: pattern
            kind: prefix
            value: {{ get (get .Values.environment .Values.environmentProfile) "elasticsearchAccessIndexPrefix"  | default "icargo_acces_log_index" }}
          - filtertype: age
            source: name
            direction: older
            timestring: '-%Y%m%d'
            unit: days
            unit_count: ${LOG_INDEX_RETENTION_DAYS:8}            
      4:
        action: forcemerge
        description: Force Merging of indices for perf and space considerations
        options:
          max_num_segments: 5
          delay: 5
          ignore_empty_list: True
          timeout_override: 600
          continue_if_exception: True
          disable_action: ${FORCE_MERGE_DISABLED:False}
        filters:
          - filtertype: pattern
            kind: prefix
            value: {{ get (get .Values.environment .Values.environmentProfile) "elasticsearchIndexPrefix"  | default "icargo_log_index" }}
          - filtertype: age
            source: name
            direction: older
            timestring: '-%Y%m%d'
            unit: days
            unit_count: 2
      5:
        action: forcemerge
        description: Force Merging of indices for perf and space considerations
        options:
          max_num_segments: 5
          delay: 5
          ignore_empty_list: True
          timeout_override: 600
          continue_if_exception: True
          disable_action: ${FORCE_MERGE_DISABLED:False}
        filters:
          - filtertype: pattern
            kind: prefix
            value: icargo_txprobe_index
          - filtertype: age
            source: name
            direction: older
            timestring: '-%Y%m%d%H'
            unit: hours
            unit_count: 2
      6:
        action: forcemerge
        description: Force Merging of indices for perf and space considerations
        options:
          max_num_segments: 5
          delay: 5
          ignore_empty_list: True
          timeout_override: 600
          continue_if_exception: True
          disable_action: ${FORCE_MERGE_DISABLED:False}
        filters:
          - filtertype: pattern
            kind: prefix
            value: {{ get (get .Values.environment .Values.environmentProfile) "elasticsearchAccessIndexPrefix"  | default "icargo_acces_log_index" }}
          - filtertype: age
            source: name
            direction: older
            timestring: '-%Y%m%d'
            unit: days
            unit_count: 2            
   
    
    
