/*
 * AirlineCN51SummaryPK.java Created on Feb 15, 2006
 *
 * Copyright 2006 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */

package com.ibsplc.icargo.business.mail.mra.airlinebilling;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-1946
 *
 */
/*
 * Revision History
 * -------------------------------------------------------------------------
 * Revision 		Date 					Author 		Description
 * ------------------------------------------------------------------------- 
 * 0.1			  feb 14, 2007			    A-1946		Created	
 */
@Embeddable
public class AirlineCN51SummaryPK implements Serializable {
    /**
     * companycode
     */
    private String companyCode;

    /**
     * airlineIdentifier
     */
    private int airlineIdentifier;

    /**
     * interlinebillingtype
     */
    private String interlinebillingtype;
    
    /**
     * invoicenumber
     */
    private String invoicenumber;
    
    /**
     * clearance period
     */
    private String clearancePeriod;

   
	/**
     *
     * @return
     */
    public int hashCode() {
        return new StringBuilder().append(companyCode).append(airlineIdentifier)
                .append(interlinebillingtype).append(invoicenumber)
                .append(clearancePeriod).toString().hashCode();
    }

    /**
     *
     * @param obj
     * @return
     */
    public boolean equals(Object obj) {
    	if(obj != null) {
    		return this.hashCode() == obj.hashCode();
    	}else{
    		return false;
    	}
    }


	/**
     * 
     * @param companyCode
     * @param airlineIdentifier
     * @param interlinebillingtype
     * @param invoicenumber
     * @param clearancePeriod
     */
    public AirlineCN51SummaryPK(String companyCode, int airlineIdentifier,
    		String interlinebillingtype, String invoicenumber, String clearancePeriod ) {
        this.companyCode = companyCode;
        this.airlineIdentifier = airlineIdentifier;
        this.interlinebillingtype = interlinebillingtype;
        this.invoicenumber = invoicenumber;
        this.clearancePeriod = clearancePeriod;
    }

    /**
     * default constructor
     */
    public AirlineCN51SummaryPK() {
    }

    /**
     * 
     * @param interlinebillingtype
     */
	public void setInterlinebillingtype(java.lang.String interlinebillingtype) {
		this.interlinebillingtype=interlinebillingtype;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getInterlinebillingtype() {
		return this.interlinebillingtype;
	}

	/**
	 * 
	 * @param clearancePeriod
	 */
	public void setClearancePeriod(java.lang.String clearancePeriod) {
		this.clearancePeriod=clearancePeriod;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getClearancePeriod() {
		return this.clearancePeriod;
	}

	/**
	 * 
	 * @param invoicenumber
	 */
	public void setInvoicenumber(java.lang.String invoicenumber) {
		this.invoicenumber=invoicenumber;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getInvoicenumber() {
		return this.invoicenumber;
	}

	/**
	 * 
	 * @param airlineIdentifier
	 */
	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier=airlineIdentifier;
	}

	/**
	 * 
	 * @return
	 */
	public int getAirlineIdentifier() {
		return this.airlineIdentifier;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(156);
		sbul.append("AirlineCN51SummaryPK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', clearancePeriod '").append(this.clearancePeriod);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', interlinebillingtype '").append(
				this.interlinebillingtype);
		sbul.append("', invoicenumber '").append(this.invoicenumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
