/*

 * MRAAirlineForBillingPK.java Created on July 15, 2008

 *

 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.

 *

 * This software is the proprietary information of IBS Software Services (P) Ltd.

 * Use is subject to license terms.

 */

package com.ibsplc.icargo.business.mail.mra.airlinebilling;


import java.io.Serializable;




import javax.persistence.Embeddable;



/**
 * @author 
 * MRAAirlineForBillingPK
 * Revision History
 * Version      Date           Author          		    Description
 */

@Embeddable

public class MRAAirlineForBillingPK implements Serializable {



	private String companyCode;



	private int airlineIdentifier;



	private String clearancePeriod;



	/**
	 * Default Constructor
	 *
	 */
	public MRAAirlineForBillingPK() {



	}



	/**
	 * Overloaded Constructor
	 * 
	 * @param companyCode
	 * @param airlineIdentifier
	 * @param clearancePeriod
	 */
	public MRAAirlineForBillingPK(String companyCode,int airlineIdentifier,String clearancePeriod) {

		this.companyCode = companyCode;

		this.airlineIdentifier = airlineIdentifier;

		this.clearancePeriod = clearancePeriod;

	}


	/**
	 * 
	 * @param obj
	 * @return boolean
	 */
	@Override

	public boolean equals(Object obj) {

		boolean isEqual = false;

		if(obj != null ){

			isEqual = this.hashCode() == obj.hashCode();

		}

		return isEqual;

	}


	/**
	 * 
	 * @return int
	 */
	
	@Override
	
	public int hashCode() {

		return this.toString().hashCode();

	}


	/**
	 * @param clearancePeriod The clearancePeriod to set.
	 */
	public void setClearancePeriod(java.lang.String clearancePeriod) {
		this.clearancePeriod=clearancePeriod;
	}

	/**
	 * @return Returns the clearancePeriod.
	 */
	public java.lang.String getClearancePeriod() {
		return this.clearancePeriod;
	}

	/**
	 * @param airlineIdentifier The airlineIdentifier to set.
	 */
	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier=airlineIdentifier;
	}

	/**
	 * @return Returns the airlineIdentifier.
	 */
	public int getAirlineIdentifier() {
		return this.airlineIdentifier;
	}
	
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 * @return Returns the companyCode.
	 */
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}



	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(101);
		sbul.append("MRAAirlineForBillingPK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', clearancePeriod '").append(this.clearancePeriod);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("' ]");
		return sbul.toString();
	}

}
