/*
 * MRAAirlineBillingAuditPK.java Created on 13 July, 2007
 *
 * Copyright 2007 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.airlinebilling;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;
/**
 * @author A-2391 
 */
@KeyTable(table = "MALMRAARLAUDKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "AUDSEQ_GEN", table = "MALMRAARLAUDKEY", key = "FLTAUD_SEQNUM")
@Embeddable
public class MRAAirlineBillingAuditPK implements Serializable {
	/**
	 * Company Code
	 */

	private String companyCode;

	/**
	 * The airlineIdentifier
	 */

	private int airlineIdentifier;

	/**
	 * The serialNumber
	 */

	private int serialNumber;

	/**
	 * @param other
	 * @return
	 */

	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null ){
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;		
	}

	/**
	 * @return
	 */
	public int hashCode() {

		return new StringBuffer(companyCode)
		          .append(airlineIdentifier)
		          .append(serialNumber)
		          .toString()
				  .hashCode();
	}


	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * 
	 * @param serialNumber
	 */
	public void setSerialNumber(int serialNumber) {
		this.serialNumber=serialNumber;
	}
	/**
	 * 
	 * @return
	 */
	@Key(generator = "AUDSEQ_GEN", startAt = "1")
	public int getSerialNumber() {
		return this.serialNumber;
	}

	/**
	 * 
	 * @param airlineIdentifier
	 */
	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier=airlineIdentifier;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "ARLIDR")
	public int getAirlineIdentifier() {
		return this.airlineIdentifier;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(100);
		sbul.append("MRAAirlineBillingAuditPK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', serialNumber '").append(this.serialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
