/*
 * MRAFormOnePK.java Created on Jul 28,2008
 *
 * Copyright 2008 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.airlinebilling;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 *
 *
 * @author A-2391
 *
 */
@Embeddable
public class MRAFormOnePK implements Serializable{
	/**
	 * CompanyCode
	 */

	private String companyCode;

	/**
	 * airline Identifier
	 */

	private int airlineIdentifier;

	/**
	 * clearancePeriod
	 */

	private String clearancePeriod;
	/**
	 * 
	 */
	private String intBillingType;
	/**
	 * 
	 */
	private String classType;
	 /**
     * @param
     * @return int
     */
	@Override
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(airlineIdentifier)
				.append(clearancePeriod).append(intBillingType)
				.append(classType).toString().hashCode();
	}
    /**
     * @param other
     * @return
     */
	@Override
	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null ){
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;
	}
	/**
	    *
	    * @param companyCode
	    * @param airlineIdentifier
	    * @param clearancePeriod
	    * @param intBillingType
	    * @param classTyp
	    */
	   public MRAFormOnePK(String companyCode, int airlineIdentifier,
	                 String clearancePeriod,String intBillingType,String classTyp) {
	       this.companyCode = companyCode;
	       this.airlineIdentifier = airlineIdentifier;
	       this.clearancePeriod = clearancePeriod;
	       this.intBillingType = intBillingType;
	       this.classType=classTyp;
	   }

	   /**
	    *
	    */
	   public MRAFormOnePK() {
	   }


	public void setClearancePeriod(String clearancePeriod) {
		this.clearancePeriod=clearancePeriod;
	}

	/**
	 * 
	 * @return
	 */
	public String getClearancePeriod() {
		return this.clearancePeriod;
	}

	/**
	 * 
	 * @param airlineIdentifier
	 */
	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier=airlineIdentifier;
	}

	/**
	 * 
	 * @return
	 */
	public int getAirlineIdentifier() {
		return this.airlineIdentifier;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 * 
	 * @return
	 */
	public String getCompanyCode() {
		return this.companyCode;
	}
	/**
	 * @return Returns the intBillingType.
	 */
	public String getIntBillingType() {
		return intBillingType;
	}
	/**
	 * @param intBillingType The intBillingType to set.
	 */
	public void setIntBillingType(String intBillingType) {
		this.intBillingType = intBillingType;
	}
	/**
	 * @return Returns the classType.
	 */
	public String getClassType() {
		return classType;
	}
	/**
	 * @param classType The classType to set.
	 */
	public void setClassType(String classType) {
		this.classType = classType;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(138);
		sbul.append("MRAFormOnePK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', classType '").append(this.classType);
		sbul.append("', clearancePeriod '").append(this.clearancePeriod);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', intBillingType '").append(this.intBillingType);
		sbul.append("' ]");
		return sbul.toString();
	}
}
