/*

 * MRAFormThreeTempPK.java Created on July 29,2008

 *

 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.

 *

 * This software is the proprietary information of IBS Software Services (P) Ltd.

 * Use is subject to license terms.

 */
package com.ibsplc.icargo.business.mail.mra.airlinebilling;

import java.io.Serializable;
import javax.persistence.Embeddable;

	/**

	 * @author a-3108

	 */



	@Embeddable

	public class MRAFormThreeTempPK implements Serializable {



		private String companyCode;



		private int airlineIdentifier;



		private String clearancePeriod;



		private int serialNumber;



		/**

		 * Default Constructor

		 *

		 */

		public MRAFormThreeTempPK() {

		}



		public MRAFormThreeTempPK(String companyCode,

								int airlineIdentifier, String clearancePeriod,

												int serialNumber) {



			this.companyCode = companyCode;

			this.airlineIdentifier = airlineIdentifier;

			this.clearancePeriod = clearancePeriod;

			this.serialNumber = serialNumber;

		}



		/**
		 * @param other
		 * @return boolean
		 */
		public boolean equals(Object other) {

			if(other!=null){

				return (hashCode() == other.hashCode());

			}

			return false;

		}



		/**
		 * @return int
		 */
		public int hashCode() {

			return new StringBuffer(companyCode).append(airlineIdentifier)

												.append(clearancePeriod).append(serialNumber)

												.toString().hashCode();

		}




		/**
		 * @param serialNumber The serialNumber to set.
		 */
		public void setSerialNumber(int serialNumber) {
			this.serialNumber=serialNumber;
		}

		/**
		 * @return Returns the serialNumber.
		 */
		public int getSerialNumber() {
			return this.serialNumber;
		}

		/**
		 * @param clearancePeriod The clearancePeriod to set.
		 */
		public void setClearancePeriod(java.lang.String clearancePeriod) {
			this.clearancePeriod=clearancePeriod;
		}
		
		/**
		 * @return Returns the clearancePeriod.
		 */
		public java.lang.String getClearancePeriod() {
			return this.clearancePeriod;
		}

		/**
		 * @param airlineIdentifier The airlineIdentifier to set.
		 */
		public void setAirlineIdentifier(int airlineIdentifier) {
			this.airlineIdentifier=airlineIdentifier;
		}

		/**
		 * @return Returns the airlineIdentifier.
		 */
		public int getAirlineIdentifier() {
			return this.airlineIdentifier;
		}

		/**
		 * @param companyCode The companyCode to set.
		 */
		public void setCompanyCode(java.lang.String companyCode) {
			this.companyCode=companyCode;
		}

		/**
		 * @return Returns the companyCode.
		 */
		public java.lang.String getCompanyCode() {
			return this.companyCode;
		}



		/**
		 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
		 */
		@Override
		public String toString() {
			StringBuilder sbul = new StringBuilder(121);
			sbul.append("MRAFormThreeTempPK [ ");
			sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
			sbul.append("', clearancePeriod '").append(this.clearancePeriod);
			sbul.append("', companyCode '").append(this.companyCode);
			sbul.append("', serialNumber '").append(this.serialNumber);
			sbul.append("' ]");
			return sbul.toString();
		}
	}



