/*
 * MRASisSupportingDocumentPK created on October 29, 2018 
 * Copyright 2007 IBS Software Services (P) Ltd. All Rights Reserved.
 * 
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms. 
 */
package com.ibsplc.icargo.business.mail.mra.airlinebilling;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * PK class for SIS-Supporting documents.
 * 
 * @author a-8061
 *
 */

/*
 * Revision History
 * -------------------------------------------------------------------------
 * Revision 		Date 					Author 		Description
 * ------------------------------------------------------------------------- 
 * 0.1     		  October 29, 2018				A-8061 		 Created
 */
@Embeddable
public class MRASisSupportingDocumentPK implements Serializable{
	
	private String companyCode;	
	private int billedAirline;
	private String clearancePeriod;
	private String invoiceNumber;
	private int invoiceSerialNumber;
	private String billingType;
	private int docSerNumber;
	private String fileName;
	
	private long mailSequenceNumber;
	

	public MRASisSupportingDocumentPK(String companyCode, int billedAirline,
			String clearancePeriod, String invoiceNumber,
			int invoiceSerialNumber, String billingType, int docSerNumber,
			String fileName,long mailseqNumber) {

		this.companyCode = companyCode;
		this.billedAirline = billedAirline;
		this.clearancePeriod = clearancePeriod;
		this.invoiceNumber = invoiceNumber;
		this.invoiceSerialNumber = invoiceSerialNumber;
		this.billingType = billingType;
		this.docSerNumber = docSerNumber;
		this.fileName = fileName;
		this.mailSequenceNumber=mailseqNumber;
	}
	/** 
	* Default constructor 
	*/
	public MRASisSupportingDocumentPK() {
	}
	/**
	 *
	 * @param o
	 * @return
	 */
	public boolean equals(Object obj) {
		if (obj != null) {
			return this.hashCode() == obj.hashCode();
		}
		return false;
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuffer().append(companyCode).append(fileName)
				.append(billedAirline).append(clearancePeriod)
				.append(invoiceNumber).append(invoiceSerialNumber)
				.append(billingType).append(docSerNumber).append(fileName).append(mailSequenceNumber)
				.toString().hashCode();
	}

	/**
	 * @return the companyCode
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * @param companyCode the companyCode to set
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	

	/**
	 * @return the billedAirline
	 */
	public int getBilledAirline() {
		return billedAirline;
	}

	/**
	 * @param billedAirline the billedAirline to set
	 */
	public void setBilledAirline(int billedAirline) {
		this.billedAirline = billedAirline;
	}

	/**
	 * @return the clearancePeriod
	 */
	public String getClearancePeriod() {
		return clearancePeriod;
	}

	/**
	 * @param clearancePeriod the clearancePeriod to set
	 */
	public void setClearancePeriod(String clearancePeriod) {
		this.clearancePeriod = clearancePeriod;
	}

	/**
	 * @return the invoiceNumber
	 */
	public String getInvoiceNumber() {
		return invoiceNumber;
	}

	/**
	 * @param invoiceNumber the invoiceNumber to set
	 */
	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	/**
	 * @return the invoiceSerialNumber
	 */
	public int getInvoiceSerialNumber() {
		return invoiceSerialNumber;
	}

	/**
	 * @param invoiceSerialNumber the invoiceSerialNumber to set
	 */
	public void setInvoiceSerialNumber(int invoiceSerialNumber) {
		this.invoiceSerialNumber = invoiceSerialNumber;
	}

	/**
	 * @return the billingType
	 */
	public String getBillingType() {
		return billingType;
	}

	/**
	 * @param billingType the billingType to set
	 */
	public void setBillingType(String billingType) {
		this.billingType = billingType;
	}

	/**
	 * @return the docSerNumber
	 */
	public int getDocSerNumber() {
		return docSerNumber;
	}

	/**
	 * @param docSerNumber the docSerNumber to set
	 */
	public void setDocSerNumber(int docSerNumber) {
		this.docSerNumber = docSerNumber;
	}

	/**
	 * @return the fileName
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * @param fileName the fileName to set
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:46 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(221);
		sbul.append("SisSupportingDocumentPK [ ");
		sbul.append("billedAirline '").append(this.billedAirline);
		sbul.append("', billingType '").append(this.billingType);
		sbul.append("', clearancePeriod '").append(this.clearancePeriod);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', docSerNumber '").append(this.docSerNumber);
		sbul.append("', fileName '").append(this.fileName);
		sbul.append("', invoiceNumber '").append(this.invoiceNumber);
		sbul.append("', invoiceSerialNumber '")
				.append(this.invoiceSerialNumber);
		sbul.append("', mailSequenceNumber '")
		.append(this.mailSequenceNumber);
		
		sbul.append("' ]");
		return sbul.toString();
	}
	/**
	 * 	Getter for mailSequenceNumber 
	 *	Added by : a-8061 on 01-Nov-2018
	 * 	Used for :
	 */
	public long getMailSequenceNumber() {
		return mailSequenceNumber;
	}
	/**
	 *  @param mailSequenceNumber the mailSequenceNumber to set
	 * 	Setter for mailSequenceNumber 
	 *	Added by : a-8061 on 01-Nov-2018
	 * 	Used for :
	 */
	public void setMailSequenceNumber(long mailSequenceNumber) {
		this.mailSequenceNumber = mailSequenceNumber;
	}

}
