/*
 * RejectionMemoPK.java Created on May 18, 2007
 *
 * Copyright 2006 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.airlinebilling;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 *
 *
 * @author A-2391
 *
 */
@Embeddable
public class RejectionMemoPK implements Serializable{
	/**
	 * CompanyCode
	 */

	private String companyCode;

	/**
	 * airline Identifier
	 */

	private int airlineIdentifier;

	/**
	 * memo Code
	 */

	private String memoCode;
	 /**
     * @param
     * @return int
     */
	@Override
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(airlineIdentifier)
				.append(memoCode).toString().hashCode();
	}
    /**
     * @param other
     * @return
     */
	@Override
	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null ){
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;
	}
	/**
	    *
	    * @param companyCode
	    * @param airlineIdentifier
	    * @param memoCode
	    */
	   public RejectionMemoPK(String companyCode, int airlineIdentifier,
	                 String memoCode) {
	       this.companyCode = companyCode;
	       this.airlineIdentifier = airlineIdentifier;
	       this.memoCode = memoCode;
	   }

	   /**
	    *
	    */
	   public RejectionMemoPK() {
	   }


	public void setMemoCode(java.lang.String memoCode) {
		this.memoCode=memoCode;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getMemoCode() {
		return this.memoCode;
	}

	/**
	 * 
	 * @param airlineIdentifier
	 */
	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier=airlineIdentifier;
	}

	/**
	 * 
	 * @return
	 */
	public int getAirlineIdentifier() {
		return this.airlineIdentifier;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(87);
		sbul.append("RejectionMemoPK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', memoCode '").append(this.memoCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
