databaseChangeLog:
  - logicalFilePath: classpath:/config/changelog/tracking-business-1.0.yaml
  - changeSet:
      id: TRK_0001
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            tableExists:
              tableName: TRKAWBMST
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE TABLE TRKAWBMST (
          TRKAWBSERNUM INTEGER NOT NULL,
          CMPCOD VARCHAR(6) NOT NULL,
          SHPPFX VARCHAR(4) NOT NULL,
          MSTDOCNUM VARCHAR(20) NOT NULL,
          SHPSEQNUM INTEGER NOT NULL,
          ORGCOD VARCHAR(4),
          DSTCOD VARCHAR(4),
          STDPCS NUMERIC(6, 0),
          DISSTDWGT NUMERIC(16,4),
          STDWGT NUMERIC(16,4),
          STDWGTUNT VARCHAR(1),
          DISSTDVOL NUMERIC(16,4),
          STDVOL NUMERIC(16,4),
          STDVOLUNT VARCHAR(1),
          PRDNAM VARCHAR(30),
          SHC VARCHAR(200),
          SHPDES VARCHAR(1000),
          LSTUPDTIM TIMESTAMP(3) NOT NULL,
          LSTUPDUSR VARCHAR(50) NOT NULL,
          TAGIDX NUMERIC(1,0) DEFAULT 0 NOT NULL,
          CONSTRAINT  "TRKAWBMST_pkey" PRIMARY KEY (TRKAWBSERNUM));

          COMMENT ON TABLE TRKAWBMST IS 'Tracking AWB Master Table';
          COMMENT ON COLUMN TRKAWBMST.TRKAWBSERNUM IS 'AWB serial number';
          COMMENT ON COLUMN TRKAWBMST.CMPCOD IS 'The code that uniquely identifies the company for which the application is hosted';
          COMMENT ON COLUMN TRKAWBMST.SHPPFX IS 'Airline Prefix of the AWB';
          COMMENT ON COLUMN TRKAWBMST.MSTDOCNUM IS 'Master Document Number for the AWB';
          COMMENT ON COLUMN TRKAWBMST.SHPSEQNUM IS 'Shipment Sequence number for uniquely identifying the AWB across the services. Generated by common shipment microservices.';
          COMMENT ON COLUMN TRKAWBMST.ORGCOD IS 'Origin Code of the AWB';
          COMMENT ON COLUMN TRKAWBMST.DSTCOD IS 'Destination code of the AWB';
          COMMENT ON COLUMN TRKAWBMST.STDPCS IS 'Stated Pieces for the AWB';
          COMMENT ON COLUMN TRKAWBMST.DISSTDWGT IS 'Display Stated Weight';
          COMMENT ON COLUMN TRKAWBMST.STDWGT IS 'Stated Weight for the AWB';
          COMMENT ON COLUMN TRKAWBMST.STDWGTUNT IS 'Stated weight unit';
          COMMENT ON COLUMN TRKAWBMST.DISSTDVOL IS 'Display Stated Volume';
          COMMENT ON COLUMN TRKAWBMST.STDVOL IS 'Stated Volume for the AWB';
          COMMENT ON COLUMN TRKAWBMST.STDVOLUNT IS 'Stated volume unit';
          COMMENT ON COLUMN TRKAWBMST.PRDNAM IS 'Product name of AWB';
          COMMENT ON COLUMN TRKAWBMST.SHC IS 'Special handling code for AWB';
          COMMENT ON COLUMN TRKAWBMST.SHPDES IS 'Shipment Description';
          COMMENT ON COLUMN TRKAWBMST.LSTUPDTIM IS 'The date and time at which record was last updated';
          COMMENT ON COLUMN TRKAWBMST.LSTUPDUSR IS 'Last Update User.The application user code who performed the operation on the record';
          COMMENT ON COLUMN TRKAWBMST.TAGIDX IS 'This column will be used as workaround for the tag setting feature of CDC in its low cost replacement. The value 1 indicate that the records are tagged and will not transferred to the target in a CDC environment';

  - changeSet:
      id: TRK_0002
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            sequenceExists:
              sequenceName: TRKAWBMST_SEQ
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE SEQUENCE TRKAWBMST_SEQ
          START WITH 1
          INCREMENT BY 1
          MINVALUE 1
          MAXVALUE 9223372036854775807
          CACHE 1;

  - changeSet:
      id: TRK_0003
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            tableExists:
              tableName: TRKBKGMST
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE TABLE TRKBKGMST (
          TRKBKGSERNUM INTEGER NOT NULL,
          CMPCOD VARCHAR(6) NOT NULL,
          UBRNUM VARCHAR(50) NOT NULL,
          SHPPFX VARCHAR(4),
          MSTDOCNUM VARCHAR(20),
          BKGSTA VARCHAR(1),
          BKGDAT DATE,
          BKDPCS NUMERIC(6, 0),
          DISBKDWGT NUMERIC(16,4),
          BKDWGT NUMERIC(16,4),
          BKDWGTUNT VARCHAR(1),
          DISBKDVOL NUMERIC(16,4),
          BKDVOL NUMERIC(16,4),
          BKDVOLUNT VARCHAR(1),
          ISSSPLBKG VARCHAR(1),
          CONSTRAINT  "TRKBKGMST_pkey" PRIMARY KEY (TRKBKGSERNUM));

          COMMENT ON TABLE TRKBKGMST IS 'Tracking Booking master Table';
          COMMENT ON COLUMN TRKBKGMST.TRKBKGSERNUM IS 'Tracking booking serial number';
          COMMENT ON COLUMN TRKBKGMST.CMPCOD IS 'Company Code';
          COMMENT ON COLUMN TRKBKGMST.UBRNUM IS 'uniq booking ref number';
          COMMENT ON COLUMN TRKBKGMST.SHPPFX IS 'Shipment prefix';
          COMMENT ON COLUMN TRKBKGMST.MSTDOCNUM IS 'Master doc number ';
          COMMENT ON COLUMN TRKBKGMST.BKGSTA IS 'Booking Status';
          COMMENT ON COLUMN TRKBKGMST.BKGDAT IS 'Booking date';
          COMMENT ON COLUMN TRKBKGMST.BKDPCS IS 'Booked of Pieces';
          COMMENT ON COLUMN TRKBKGMST.DISBKDWGT IS 'Display Booked Weight';
          COMMENT ON COLUMN TRKBKGMST.BKDWGT IS 'Booked Weight';
          COMMENT ON COLUMN TRKBKGMST.BKDWGTUNT IS 'Booked weight unit';
          COMMENT ON COLUMN TRKBKGMST.DISBKDVOL IS 'Display Booked Volume';
          COMMENT ON COLUMN TRKBKGMST.BKDVOL IS 'Booked volume';
          COMMENT ON COLUMN TRKBKGMST.BKDVOLUNT IS 'Booked volume unit';
          COMMENT ON COLUMN TRKBKGMST.ISSSPLBKG IS 'Special Booking';

  - changeSet:
      id: TRK_0004
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            sequenceExists:
              sequenceName: TRKBKGMST_SEQ
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE SEQUENCE TRKBKGMST_SEQ
          START WITH 1
          INCREMENT BY 1
          MINVALUE 1
          MAXVALUE 9223372036854775807
          CACHE 1;

  - changeSet:
      id: TRK_0005
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            tableExists:
              tableName: TRKBKGFLTDTL
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE TABLE TRKBKGFLTDTL (
          TRKBKGSERNUM INTEGER NOT NULL,
          TRKBKGFLTSERNUM INTEGER NOT NULL,
          CMPCOD VARCHAR(6) NOT NULL,
          FLTNUM VARCHAR(15),
          FLTCARCOD VARCHAR(10),
          FLTDAT DATE,
          FLTORG VARCHAR(4),
          PCS NUMERIC(6, 0),
          WGT NUMERIC(16,4),
          VOL NUMERIC(16,4),
          FLTBKGSTA VARCHAR(1),
          ARRTIM TIMESTAMP WITHOUT TIME ZONE,
          DEPTIM TIMESTAMP WITHOUT TIME ZONE,
          ARRTIMUTC TIMESTAMP WITHOUT TIME ZONE,
          DEPTIMUTC TIMESTAMP WITHOUT TIME ZONE,
          CONSTRAINT  "TRKBKGFLTDTL_pkey" PRIMARY KEY (TRKBKGSERNUM, TRKBKGFLTSERNUM));

          COMMENT ON TABLE TRKBKGFLTDTL IS 'Booking flight Table';
          COMMENT ON COLUMN TRKBKGFLTDTL.TRKBKGSERNUM IS 'Tracking booking serial number';
          COMMENT ON COLUMN TRKBKGFLTDTL.TRKBKGFLTSERNUM IS 'Tracking booking flight number';
          COMMENT ON COLUMN TRKBKGFLTDTL.CMPCOD IS 'Company Code';
          COMMENT ON COLUMN TRKBKGFLTDTL.FLTNUM IS 'Flight Number ';
          COMMENT ON COLUMN TRKBKGFLTDTL.FLTCARCOD IS 'Flight Carrier code';
          COMMENT ON COLUMN TRKBKGFLTDTL.FLTDAT IS 'Flight Date (UTC)';
          COMMENT ON COLUMN TRKBKGFLTDTL.FLTORG IS 'Flight origin';
          COMMENT ON COLUMN TRKBKGFLTDTL.PCS IS 'Pieces';
          COMMENT ON COLUMN TRKBKGFLTDTL.WGT IS 'Weight';
          COMMENT ON COLUMN TRKBKGFLTDTL.VOL IS 'volume';
          COMMENT ON COLUMN TRKBKGFLTDTL.FLTBKGSTA IS 'Flight Booking status';
          COMMENT ON COLUMN TRKBKGFLTDTL.ARRTIM IS 'Arrival time local';
          COMMENT ON COLUMN TRKBKGFLTDTL.DEPTIM IS 'Departure time local';
          COMMENT ON COLUMN TRKBKGFLTDTL.ARRTIMUTC IS 'Arrival time UTC';
          COMMENT ON COLUMN TRKBKGFLTDTL.DEPTIMUTC IS 'Departure time UTC';

  - changeSet:
      id: TRK_0006
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            sequenceExists:
              sequenceName: TRKBKGFLTDTL_SEQ
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE SEQUENCE TRKBKGFLTDTL_SEQ
          START WITH 1
          INCREMENT BY 1
          MINVALUE 1
          MAXVALUE 9223372036854775807
          CACHE 1;

  - changeSet:
      id: TRK_0007
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            tableExists:
              tableName: TRKSHPMILSTNPLN
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE TABLE TRKSHPMILSTNPLN (
          TRKSHPMILSTNPLNSERNUM INTEGER NOT NULL,
          CMPCOD VARCHAR(6) NOT NULL,
          SHPKEY VARCHAR(25),
          SHPTYP VARCHAR(1),
          SHPSEQNUM INTEGER NOT NULL,
          ARPCOD VARCHAR(4),
          MILSTNCOD VARCHAR(10),
          PCS NUMERIC(6, 0),
          MILSTNTIM TIMESTAMP WITHOUT TIME ZONE,
          MILSTNTIMUTC TIMESTAMP WITHOUT TIME ZONE,
          SRC VARCHAR(10),
          OPRTYP VARCHAR(1),
          FLTNUM VARCHAR(15),
          FLTCARCOD VARCHAR(10),
          FLTDAT DATE,
          TAGIDX NUMERIC(1,0) DEFAULT 0 NOT NULL,
          CONSTRAINT  "TRKSHPMILSTNPLN_pkey" PRIMARY KEY (TRKSHPMILSTNPLNSERNUM));

          COMMENT ON TABLE TRKSHPMILSTNPLN IS 'Tracking Shipment Milestone Plan Table';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.TRKSHPMILSTNPLNSERNUM IS 'Tracking Shipment Milestone Plan Serial Number';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.CMPCOD IS 'Company Code';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.SHPKEY IS 'Shipment Key';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.SHPTYP IS 'Shipment Type';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.SHPSEQNUM IS 'Shipment sequence Number';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.ARPCOD IS 'Airport Code';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.MILSTNCOD IS 'Milestone Code';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.PCS IS 'Pieces';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.MILSTNTIM IS 'Milestone Time (Airport local time)';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.MILSTNTIMUTC IS 'Milestone Time UTC';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.SRC IS 'Source of milestone creation';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.OPRTYP IS 'Operation Type';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.FLTNUM IS 'Flight Number ';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.FLTCARCOD IS 'Flight Carrier code';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.FLTDAT IS 'Flight Date (UTC)';
          COMMENT ON COLUMN TRKSHPMILSTNPLN.TAGIDX IS 'Tag Id index';

  - changeSet:
      id: TRK_0008
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            sequenceExists:
              sequenceName: TRKSHPMILSTNPLN_SEQ
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE SEQUENCE TRKSHPMILSTNPLN_SEQ
          START WITH 1
          INCREMENT BY 1
          MINVALUE 1
          MAXVALUE 9223372036854775807
          CACHE 1;

  - changeSet:
      id: TRK_0009
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            tableExists:
              tableName: TRKMILSTNMST
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE TABLE TRKMILSTNMST (
          TRKMILSTNSERNUM INTEGER NOT NULL,
          CMPCOD VARCHAR(6) NOT NULL,
          MILSTNCOD VARCHAR(10),
          MILSTNDES VARCHAR(50),
          MILSTNTYP VARCHAR(1),
          MILSTNSTA VARCHAR(1),
          MILSTNSHPTYP VARCHAR(1),
          MILSTNUSRRST VARCHAR(1000),
          TAGIDX NUMERIC(1,0) DEFAULT 0 NOT NULL,
          CONSTRAINT  "TRKMILSTNMST_pkey" PRIMARY KEY (TRKMILSTNSERNUM));

          COMMENT ON TABLE TRKMILSTNMST IS 'Tracking Milestone Master Table';
          COMMENT ON COLUMN TRKMILSTNMST.TRKMILSTNSERNUM IS 'Tracking milestone Serial Number';
          COMMENT ON COLUMN TRKMILSTNMST.CMPCOD IS 'Company Code';
          COMMENT ON COLUMN TRKMILSTNMST.MILSTNCOD IS 'Milestone code';
          COMMENT ON COLUMN TRKMILSTNMST.MILSTNDES IS 'Milestone description';
          COMMENT ON COLUMN TRKMILSTNMST.MILSTNTYP IS 'Milestone type (export, import, Transfer)';
          COMMENT ON COLUMN TRKMILSTNMST.MILSTNSTA IS 'Milestone status';
          COMMENT ON COLUMN TRKMILSTNMST.MILSTNSHPTYP IS 'Milestone Shipment type';
          COMMENT ON COLUMN TRKMILSTNMST.MILSTNUSRRST IS 'Milestone User Result (User spesific message)';
          COMMENT ON COLUMN TRKMILSTNMST.TAGIDX IS 'Tag Id index (tech column)';

  - changeSet:
      id: TRK_0010
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            sequenceExists:
              sequenceName: TRKMILSTNMST_SEQ
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE SEQUENCE TRKMILSTNMST_SEQ
          START WITH 1
          INCREMENT BY 1
          MINVALUE 1
          MAXVALUE 9223372036854775807
          CACHE 1;

  - changeSet:
      id: TRK_0011
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            tableExists:
              tableName: TRKSHPMILSTNEVT
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE TABLE TRKSHPMILSTNEVT (
          TRKSHPMILSTNEVTSERNUM INTEGER NOT NULL,
          CMPCOD VARCHAR(6) NOT NULL,
          SHPKEY VARCHAR(25),
          SHPTYP VARCHAR(1),
          SHPSEQNUM INTEGER NOT NULL,
          ARPCOD VARCHAR(4),
          MILSTNCOD VARCHAR(10),
          MILSTNTIM TIMESTAMP WITHOUT TIME ZONE,
          MILSTNTIMUTC TIMESTAMP WITHOUT TIME ZONE,
          PCS NUMERIC(6, 0),
          MILSTNDTL JSON,
          LSTUPDTIM TIMESTAMP WITHOUT TIME ZONE,
          LSTUPDUSR VARCHAR(50),
          TAGIDX NUMERIC(1,0) DEFAULT 0 NOT NULL,
          CONSTRAINT  "TRKSHPMILSTNEVT_pkey" PRIMARY KEY (TRKSHPMILSTNEVTSERNUM));

          COMMENT ON TABLE TRKSHPMILSTNEVT IS 'Tracking shipment milestone Event Table';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.TRKSHPMILSTNEVTSERNUM IS 'Tracking Shipment Milestone event number';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.CMPCOD IS 'Company Code';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.SHPKEY IS 'Shipment Key';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.SHPTYP IS 'Shipment Type';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.SHPSEQNUM IS 'Shipment sequence Number';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.ARPCOD IS 'Airport Code';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.MILSTNCOD IS 'Milestone Code';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.MILSTNTIM IS 'Milestone Time';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.MILSTNTIMUTC IS 'Milestone Time UTC';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.PCS IS 'Pieces';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.MILSTNDTL IS 'Milestone Detail';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.LSTUPDTIM IS 'Last update time';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.LSTUPDUSR IS 'Last update User';
          COMMENT ON COLUMN TRKSHPMILSTNEVT.TAGIDX IS 'Tag Id index';

  - changeSet:
      id: TRK_0012
      author: T-2909
      preConditions:
        - onFail: MARK_RAN
        - not:
            sequenceExists:
              sequenceName: TRKSHPMILSTNEVT_SEQ
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE SEQUENCE TRKSHPMILSTNEVT_SEQ
          START WITH 1
          INCREMENT BY 1
          MINVALUE 1
          MAXVALUE 9223372036854775807
          CACHE 1;

  - changeSet:
      id: TRK_0013
      author: 201132
      preConditions:
        - onFail: MARK_RAN
        - not:
            tableExists:
              tableName: TRKAWBPII
      changes:
        dbms: postgresql
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE TABLE TRKAWBPII (
          TRKAWBSERNUM INTEGER NOT NULL,
          CMPCOD VARCHAR(6) NOT NULL,
          SHPCOD VARCHAR(15) NOT NULL,
          SHPDTL JSON,
          CNSCOD VARCHAR(15) NOT NULL,
          CNSDTL JSON,
          LSTUPDTIM TIMESTAMP(3) NOT NULL,
          LSTUPDUSR VARCHAR(50) NOT NULL,
          TAGIDX NUMERIC(1,0) DEFAULT 0 NOT NULL,
          CONSTRAINT  "TRKAWBPII_pkey" PRIMARY KEY (TRKAWBSERNUM));

          COMMENT ON TABLE TRKAWBPII IS 'Tracking AWB Master Table';
          COMMENT ON COLUMN TRKAWBPII.TRKAWBSERNUM IS 'AWB serial number';
          COMMENT ON COLUMN TRKAWBPII.CMPCOD IS 'The code that uniquely identifies the company for which the application is hosted';
          COMMENT ON COLUMN TRKAWBPII.SHPCOD IS 'Shipper code';
          COMMENT ON COLUMN TRKAWBPII.SHPDTL IS 'Shipper deails';
          COMMENT ON COLUMN TRKAWBPII.CNSCOD IS 'Consignee code';
          COMMENT ON COLUMN TRKAWBPII.CNSDTL IS 'Consignee details';
          COMMENT ON COLUMN TRKAWBPII.LSTUPDTIM IS 'The date and time at which record was last updated';
          COMMENT ON COLUMN TRKAWBPII.LSTUPDUSR IS 'Last Update User.The application user code who performed the operation on the record';
          COMMENT ON COLUMN TRKAWBPII.TAGIDX IS 'This column will be used as workaround for the tag setting feature of CDC in its low cost replacement. The value 1 indicate that the records are tagged and will not transferred to the target in a CDC environment';