/*
 * AssignedFlightPK.java Created on June 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-3109
 * 
 */
@Embeddable
public class AssignedFlightPK implements Serializable {

	/**
	 * The companyCode
	 */
	private String companyCode;
	/**
	 * The airportCode
	 */
	private String airportCode;
	/**
	 * The carrierId
	 */
	private int carrierId;
	/**
	 * The flightNumber
	 */
	private String flightNumber;
	/**
	 * The legSerialNumber
	 */
	private int legSerialNumber;
	/**
	 * The flightSequenceNumber
	 */
	private long flightSequenceNumber;

	/**
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if (other != null) {
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;
	}

	/**
	 * @return
	 */
	public int hashCode() {

		return new StringBuffer(companyCode).append(airportCode)
				.append(carrierId).append(flightNumber).append(legSerialNumber)
				.append(flightSequenceNumber).toString().hashCode();
	}

	public void setFlightNumber(java.lang.String flightNumber) {
		this.flightNumber = flightNumber;
	}

	public java.lang.String getFlightNumber() {
		return this.flightNumber;
	}

	public void setCarrierId(int carrierId) {
		this.carrierId = carrierId;
	}

	public int getCarrierId() {
		return this.carrierId;
	}

	public void setAirportCode(java.lang.String airportCode) {
		this.airportCode = airportCode;
	}

	public java.lang.String getAirportCode() {
		return this.airportCode;
	}

	public void setLegSerialNumber(int legSerialNumber) {
		this.legSerialNumber = legSerialNumber;
	}

	public int getLegSerialNumber() {
		return this.legSerialNumber;
	}

	public void setFlightSequenceNumber(long flightSequenceNumber) {
		this.flightSequenceNumber = flightSequenceNumber;
	}

	public long getFlightSequenceNumber() {
		return this.flightSequenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(166);
		sbul.append("AssignedFlightPK [ ");
		sbul.append("airportCode '").append(this.airportCode);
		sbul.append("', carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', flightNumber '").append(this.flightNumber);
		sbul.append("', flightSequenceNumber '").append(
				this.flightSequenceNumber);
		sbul.append("', legSerialNumber '").append(this.legSerialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
