/*
 * AssignedFlightSegmentPK.java Created on June 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-3109
 * 
 */
@Embeddable
public class AssignedFlightSegmentPK implements Serializable {
	/**
	 * The companyCode
	 */
	private String companyCode;

	/**
	 * The carrierId
	 */
	private int carrierId;

	/**
	 * The flightNumber
	 */
	private String flightNumber;

	/**
	 * The flightSequenceNumber
	 */
	private long flightSequenceNumber;

	/**
	 * The segmentSerialNumber
	 */
	private int segmentSerialNumber;

	/**
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if (other != null) {
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;
	}

	/**
	 * @return
	 */
	public int hashCode() {

		return new StringBuffer(companyCode).append(carrierId)
				.append(flightNumber).append(flightSequenceNumber)
				.append(segmentSerialNumber).toString().hashCode();
	}

	public void setFlightNumber(java.lang.String flightNumber) {
		this.flightNumber = flightNumber;
	}

	public java.lang.String getFlightNumber() {
		return this.flightNumber;
	}

	public void setCarrierId(int carrierId) {
		this.carrierId = carrierId;
	}

	public int getCarrierId() {
		return this.carrierId;
	}

	public void setSegmentSerialNumber(int segmentSerialNumber) {
		this.segmentSerialNumber = segmentSerialNumber;
	}

	public int getSegmentSerialNumber() {
		return this.segmentSerialNumber;
	}

	public void setFlightSequenceNumber(long flightSequenceNumber) {
		this.flightSequenceNumber = flightSequenceNumber;
	}

	public long getFlightSequenceNumber() {
		return this.flightSequenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(154);
		sbul.append("AssignedFlightSegmentPK [ ");
		sbul.append("carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', flightNumber '").append(this.flightNumber);
		sbul.append("', flightSequenceNumber '").append(
				this.flightSequenceNumber);
		sbul.append("', segmentSerialNumber '")
				.append(this.segmentSerialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
