/*
 * CarditTransportationPK.java Created on Jun 7, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * TODO Add the purpose of this class
 * 
 * @author A-1739
 * 
 */
/*
 * Revision History
 * --------------------------------------------------------------------------
 * Revision Date Author Description
 * ------------------------------------------------------------------------- 0.1
 * Jun 7, 2006 A-1739 First Draft
 *  		  July 16, 2007			A-1739		EJB3Final changes
 */
@Embeddable
@KeyTable(table = "MALCDTTRTKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "MALCDTTRTKEY", key = "TRTSEQNUM_GEN")
public class CarditTransportationPK implements Serializable {
	/**
	 * The CompanyCode
	 */

	private String companyCode;

	/**
	 * This field is the unique key identifying a CARDIT cardit key is a
	 * combination of sender ID, consignment-document-number, despatch year
	 */

	private String carditKey;

	/**
	 * Arrival place of flight
	 */

	private String arrivalPort;

	/**
	 * The SequenceNumber
	 */

	private long sequenceNumber;

	/**
	 * @return The HashCode Implementation of the PK Class
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(carditKey)
				.append(arrivalPort).append(sequenceNumber).toString()
				.hashCode();
	}

	/**
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null ){
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;		
	}


	public void setArrivalPort(java.lang.String arrivalPort) {
		this.arrivalPort=arrivalPort;
	}
	@KeyCondition(column = "DSTCOD")
	public java.lang.String getArrivalPort() {
		return this.arrivalPort;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setCarditKey(java.lang.String carditKey) {
		this.carditKey=carditKey;
	}
	@KeyCondition(column = "CDTKEY")
	public java.lang.String getCarditKey() {
		return this.carditKey;
	}

	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public long getSequenceNumber() {
		return this.sequenceNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(115);
		sbul.append("CarditTransportationPK [ ");
		sbul.append("arrivalPort '").append(this.arrivalPort);
		sbul.append("', carditKey '").append(this.carditKey);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
