/*
 * CarditContainerPK.java Created on Jun 7, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * TODO Add the purpose of this class
 * 
 * @author A-1739
 * 
 */
/*
 * Revision History
 * --------------------------------------------------------------------------
 * Revision Date Author Description
 * ------------------------------------------------------------------------- 0.1
 * Jun 7, 2006 A-1739 First Draft
 *  		  July 16, 2007			A-1739		EJB3 Final changes
 */
@Embeddable
public class CarditContainerPK implements Serializable {

	/**
	 * CompanyCode
	 */
	private String companyCode;

	/**
	 * Cardit Key
	 */
	private String carditKey;

	/**
	 * Equipment identification number
	 */
	private String containerNumber;

	/**
	 * The Hashcode Implementation
	 * @return
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(carditKey)
				.append(containerNumber).toString().hashCode();
	}

	/**
	 * The Equals Method
	 * @param other
	 * @return 
	 */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null ){
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;		
	}


	public void setContainerNumber(java.lang.String containerNumber) {
		this.containerNumber=containerNumber;
	}

	public java.lang.String getContainerNumber() {
		return this.containerNumber;
	}

	public void setCarditKey(java.lang.String carditKey) {
		this.carditKey=carditKey;
	}

	public java.lang.String getCarditKey() {
		return this.carditKey;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(88);
		sbul.append("CarditContainerPK [ ");
		sbul.append("carditKey '").append(this.carditKey);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', containerNumber '").append(this.containerNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
