/*
 * ConsignmentDocumentPK.java Created on Jul 14, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author a-5991
 */
@KeyTable(table = "MALCSGMSTKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "MALCSGMSTKEY", key = "CSG_SEQ_NUM")
@Embeddable
public class ConsignmentDocumentPK implements Serializable {
	/**
	 * Company Code
	 */

	private String companyCode;

	/**
	 * Consignment Number
	 */

	private String consignmentNumber;

	/**
	 * paCode
	 */

	private String paCode;

	/**
	 * consignmentSequenceNumber
	 */

	private int consignmentSequenceNumber;

	/**
	 * Default Constructor
	 */
	public ConsignmentDocumentPK() {

	}

	/**
	 * @author A-1883
	 * @param companyCode
	 * @param consignmentNumber
	 * @param paCode
	 * @param consignmentSequenceNumber
	 */
	public ConsignmentDocumentPK(String companyCode, String consignmentNumber,
			String paCode, int consignmentSequenceNumber) {
		this.companyCode = companyCode;
		this.consignmentNumber = consignmentNumber;
		this.consignmentSequenceNumber = consignmentSequenceNumber;
		this.paCode = paCode;
	}

	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null ){
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;		
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).append(consignmentNumber).append(
				paCode).append(consignmentSequenceNumber).toString().hashCode();
	}


	public void setPaCode(java.lang.String paCode) {
		this.paCode=paCode;
	}
	@KeyCondition(column = "POACOD")
	public java.lang.String getPaCode() {
		return this.paCode;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setConsignmentSequenceNumber(int consignmentSequenceNumber) {
		this.consignmentSequenceNumber=consignmentSequenceNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public int getConsignmentSequenceNumber() {
		return this.consignmentSequenceNumber;
	}

	public void setConsignmentNumber(java.lang.String consignmentNumber) {
		this.consignmentNumber=consignmentNumber;
	}
	@KeyCondition(column = "CSGDOCNUM")
	public java.lang.String getConsignmentNumber() {
		return this.consignmentNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(128);
		sbul.append("ConsignmentDocumentPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', consignmentNumber '").append(this.consignmentNumber);
		sbul.append("', consignmentSequenceNumber '").append(
				this.consignmentSequenceNumber);
		sbul.append("', paCode '").append(this.paCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
