/*
 * ContainerAuditPK.java Created on May 26, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */

package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-3109 The ContainerAuditPK class for the ContainerAudit
 */

@KeyTable(table = "MALFLTCONAUDKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "AUDSEQ_GEN", table = "MALFLTCONAUDKEY", key = "CONAUD_SEQNUM")
@Embeddable
public class ContainerAuditPK implements Serializable {

	/**
	 * Company Code
	 */

	private String companyCode;

	/**
	 * The ContainerNumber
	 */

	private String containerNumber;

	/**
	 * The assignedPort
	 */

	private String assignmentPort;
	/**
	 * The carrierId
	 */

	private int carrierId;

	/**
	 * The FlightNumber
	 */

	private String flightNumber;

	/**
	 * The FlightSequenceNumber
	 */

	private long flightSequenceNumber;

	/**
	 * The LegsequenceNumber
	 */

	private int legSerialNumber;

	/**
	 * The key generated SequenceNumber
	 */

	private long sequenceNumber;

	/**
	 * @author a-3109 The Equals Method
	 * @param other
	 * @return
	 */

	public boolean equals(Object other) {
		boolean isEqual = false;
		if (other != null) {
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;
	}

	/**
	 * hashCode method
	 * 
	 * @return int
	 */
	public int hashCode() {

		return new StringBuffer(companyCode).append(containerNumber)
				.append(assignmentPort).append(carrierId).append(flightNumber)
				.append(flightSequenceNumber).append(legSerialNumber)
				.append(sequenceNumber).toString().hashCode();
	}

	public void setContainerNumber(java.lang.String containerNumber) {
		this.containerNumber = containerNumber;
	}

	@KeyCondition(column = "CONNUM")
	public java.lang.String getContainerNumber() {
		return this.containerNumber;
	}

	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	@Key(generator = "AUDSEQ_GEN", startAt = "1")
	public long getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setFlightNumber(java.lang.String flightNumber) {
		this.flightNumber = flightNumber;
	}

	@KeyCondition(column = "FLTNUM")
	public java.lang.String getFlightNumber() {
		return this.flightNumber;
	}

	public void setLegSerialNumber(int legSerialNumber) {
		this.legSerialNumber = legSerialNumber;
	}

	@KeyCondition(column = "LEGSERNUM")
	public int getLegSerialNumber() {
		return this.legSerialNumber;
	}

	public void setFlightSequenceNumber(long flightSequenceNumber) {
		this.flightSequenceNumber = flightSequenceNumber;
	}

	@KeyCondition(column = "FLTSEQNUM")
	public long getFlightSequenceNumber() {
		return this.flightSequenceNumber;
	}

	public void setAssignmentPort(java.lang.String assignmentPort) {
		this.assignmentPort = assignmentPort;
	}

	@KeyCondition(column = "ASGPRT")
	public java.lang.String getAssignmentPort() {
		return this.assignmentPort;
	}

	public void setCarrierId(int carrierId) {
		this.carrierId = carrierId;
	}

	@KeyCondition(column = "FLTCARIDR")
	public int getCarrierId() {
		return this.carrierId;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(222);
		sbul.append("ContainerAuditPK [ ");
		sbul.append("assignmentPort '").append(this.assignmentPort);
		sbul.append("', carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', containerNumber '").append(this.containerNumber);
		sbul.append("', flightNumber '").append(this.flightNumber);
		sbul.append("', flightSequenceNumber '").append(
				this.flightSequenceNumber);
		sbul.append("', legSerialNumber '").append(this.legSerialNumber);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
