/*
 * ContainerPK.java Created on June 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author a-3109
 * 
 */
@Embeddable
public class ContainerPK implements Serializable {
	/**
	 * The companyCode
	 */
	private String companyCode;

	/**
	 * The containerNumber
	 */
	private String containerNumber;

	/**
	 * The assignmentPort
	 */
	private String assignmentPort;

	/**
	 * The carrierId
	 */
	private int carrierId;

	/**
	 * The flightNumber
	 */
	private String flightNumber;

	/**
	 * The flightSequenceNumber
	 */
	private long flightSequenceNumber;

	/**
	 * The legSerialNumber
	 */
	private int legSerialNumber;

	/**
	 * The equals method
	 * 
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * The hashCode method
	 * 
	 * @return
	 */
	public int hashCode() {

		return new StringBuffer(companyCode).append(containerNumber)
				.append(assignmentPort).append(carrierId).append(flightNumber)
				.append(flightSequenceNumber).append(legSerialNumber)
				.toString().hashCode();
	}

	public void setContainerNumber(java.lang.String containerNumber) {
		this.containerNumber = containerNumber;
	}

	public java.lang.String getContainerNumber() {
		return this.containerNumber;
	}

	public void setFlightNumber(java.lang.String flightNumber) {
		this.flightNumber = flightNumber;
	}

	public java.lang.String getFlightNumber() {
		return this.flightNumber;
	}

	public void setCarrierId(int carrierId) {
		this.carrierId = carrierId;
	}

	public int getCarrierId() {
		return this.carrierId;
	}

	public void setLegSerialNumber(int legSerialNumber) {
		this.legSerialNumber = legSerialNumber;
	}

	public int getLegSerialNumber() {
		return this.legSerialNumber;
	}

	public void setFlightSequenceNumber(long flightSequenceNumber) {
		this.flightSequenceNumber = flightSequenceNumber;
	}

	public long getFlightSequenceNumber() {
		return this.flightSequenceNumber;
	}

	public void setAssignmentPort(java.lang.String assignmentPort) {
		this.assignmentPort = assignmentPort;
	}

	public java.lang.String getAssignmentPort() {
		return this.assignmentPort;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(191);
		sbul.append("ContainerPK [ ");
		sbul.append("assignmentPort '").append(this.assignmentPort);
		sbul.append("', carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', containerNumber '").append(this.containerNumber);
		sbul.append("', flightNumber '").append(this.flightNumber);
		sbul.append("', flightSequenceNumber '").append(
				this.flightSequenceNumber);
		sbul.append("', legSerialNumber '").append(this.legSerialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
