/*
 * DamagedDSNDetailPK.java Created on Jul 24, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * 
 * 
 * @author A-1739
 * 
 */
/*
 * Revision History
 * --------------------------------------------------------------------------
 * Revision Date Author Description
 * ------------------------------------------------------------------------- 0.1
 * Jul 24, 2006 A-1739 First Draft
 */
@Embeddable
public class DamagedDSNDetailPK implements Serializable {
	/**
	 * The Company code
	 */
	private String companyCode;

	/**
	 * The dsn
	 */
	private String dsn;

	/**
	 * The originExchangeOffice
	 */
	private String originExchangeOffice;

	/**
	 * The destinationExchangeOffice
	 */
	private String destinationExchangeOffice;

	/**
	 * The mailClass
	 */
	private String mailSubclass;

	/**
	 * The year
	 */
	private int year;

	/**
	 * The Company code
	 */
	private String consignmentNumber;

	/**
	 * The consignmentSequenceNumber
	 */
	private int consignmentSequenceNumber;

	/**
	 * The paCode
	 */
	private String paCode;

	/**
	 * The damageSequenceNumber
	 */
	private int damageSequenceNumber;

	/**
	 * The airportCode
	 */
	private String airportCode;

	/**
	 * The damageCode
	 */
	private String damageCode;
	
	private String mailCategoryCode;

	/**
	 * @param other
	 * @return
	 */
	@Override
	public boolean equals(Object other) {
		return (other != null) && (this.hashCode() == other.hashCode());
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(dsn).append(
				originExchangeOffice).append(destinationExchangeOffice).append(
				mailSubclass).append(year).append(consignmentNumber).append(
				consignmentSequenceNumber).append(paCode).append(
				damageSequenceNumber).append(airportCode).append(damageCode).
				append(mailCategoryCode)
				.toString().hashCode();
	}

	public void setConsignmentSequenceNumber(int consignmentSequenceNumber) {
		this.consignmentSequenceNumber=consignmentSequenceNumber;
	}

	public int getConsignmentSequenceNumber() {
		return this.consignmentSequenceNumber;
	}

	public void setConsignmentNumber(java.lang.String consignmentNumber) {
		this.consignmentNumber=consignmentNumber;
	}

	public java.lang.String getConsignmentNumber() {
		return this.consignmentNumber;
	}

	public void setYear(int year) {
		this.year=year;
	}

	public int getYear() {
		return this.year;
	}

	public void setMailSubclass(java.lang.String mailSubclass) {
		this.mailSubclass=mailSubclass;
	}

	public java.lang.String getMailSubclass() {
		return this.mailSubclass;
	}

	public void setAirportCode(java.lang.String airportCode) {
		this.airportCode=airportCode;
	}

	public java.lang.String getAirportCode() {
		return this.airportCode;
	}

	public void setOriginExchangeOffice(java.lang.String originExchangeOffice) {
		this.originExchangeOffice=originExchangeOffice;
	}

	public java.lang.String getOriginExchangeOffice() {
		return this.originExchangeOffice;
	}

	public void setMailCategoryCode(java.lang.String mailCategoryCode) {
		this.mailCategoryCode=mailCategoryCode;
	}

	public java.lang.String getMailCategoryCode() {
		return this.mailCategoryCode;
	}

	public void setDestinationExchangeOffice(java.lang.String destinationExchangeOffice) {
		this.destinationExchangeOffice=destinationExchangeOffice;
	}

	public java.lang.String getDestinationExchangeOffice() {
		return this.destinationExchangeOffice;
	}

	public void setPaCode(java.lang.String paCode) {
		this.paCode=paCode;
	}

	public java.lang.String getPaCode() {
		return this.paCode;
	}

	public void setDamageCode(java.lang.String damageCode) {
		this.damageCode=damageCode;
	}

	public java.lang.String getDamageCode() {
		return this.damageCode;
	}

	public void setDsn(java.lang.String dsn) {
		this.dsn=dsn;
	}

	public java.lang.String getDsn() {
		return this.dsn;
	}

	public void setDamageSequenceNumber(int damageSequenceNumber) {
		this.damageSequenceNumber=damageSequenceNumber;
	}

	public int getDamageSequenceNumber() {
		return this.damageSequenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(354);
		sbul.append("DamagedDSNDetailPK [ ");
		sbul.append("airportCode '").append(this.airportCode);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', consignmentNumber '").append(this.consignmentNumber);
		sbul.append("', consignmentSequenceNumber '").append(
				this.consignmentSequenceNumber);
		sbul.append("', damageCode '").append(this.damageCode);
		sbul.append("', damageSequenceNumber '").append(
				this.damageSequenceNumber);
		sbul.append("', destinationExchangeOffice '").append(
				this.destinationExchangeOffice);
		sbul.append("', dsn '").append(this.dsn);
		sbul.append("', mailCategoryCode '").append(this.mailCategoryCode);
		sbul.append("', mailSubclass '").append(this.mailSubclass);
		sbul.append("', originExchangeOffice '").append(
				this.originExchangeOffice);
		sbul.append("', paCode '").append(this.paCode);
		sbul.append("', year '").append(this.year);
		sbul.append("' ]");
		return sbul.toString();
	}
}
