/*
 * DamagedMailbagPK.java Created on Jul 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author a-5991
 */
@Embeddable
public class DamagedMailbagPK implements Serializable {

	/**
	 * The companyCode
	 */

	private String companyCode;

	/**
	 * The dsn
	 */
	//private String dsn;

	/**
	 * The originExchangeOffice
	 */
	//private String originExchangeOffice;

	/**
	 * The destinationExchangeOffice
	 */
	//private String destinationExchangeOffice;

	/**
     * The mailSubclass
     */
  //  private String mailSubclass;
    /**
     * The mailCategoryCode
     */
  //  private String mailCategoryCode;
	/**
	 * The year
	 */
	//private int year;

	/**
	 * The mailbagId
	 */
	//private String mailbagId;

	/**
	 * The damageCode
	 */
	private String damageCode;

	/**
	 * The airportCode
	 */
	private String airportCode;
	
	/**
	 * mailIdr
	 */
	//private String mailIdr;
	/**
	 * mailSequenceNumber
	 */
	private long mailSequenceNumber;
	/**
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {

		return new StringBuffer(companyCode).append(damageCode)
				.append(airportCode).toString().hashCode();
	}

	

	public void setAirportCode(java.lang.String airportCode) {
		this.airportCode=airportCode;
	}

	public java.lang.String getAirportCode() {
		return this.airportCode;
	}

	

	public void setDamageCode(java.lang.String damageCode) {
		this.damageCode=damageCode;
	}

	public java.lang.String getDamageCode() {
		return this.damageCode;
	}



	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	



	public long getMailSequenceNumber() {
		return mailSequenceNumber;
	}

	public void setMailSequenceNumber(long mailSequenceNumber) {
		this.mailSequenceNumber = mailSequenceNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(257);
		sbul.append("DamagedMailbagPK [ ");
		sbul.append("airportCode '").append(this.airportCode);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', damageCode '").append(this.damageCode);
		sbul.append("', mailSequenceNumber '").append(this.mailSequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
