/*
 * MailInConsignmentPK.java Created on Jun 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;



/**
 * @author a-5991
 */

@Embeddable
public class MailInConsignmentPK implements Serializable {
	/**
	 * companyCode
	 */

	private String companyCode;

	/**
	 * consignmentNumber
	 */

	private String consignmentNumber;

	/**
	 * paCode
	 */

	private String paCode;

	/**
	 * consignmentSequenceNumber
	 */

	private int consignmentSequenceNumber;

	/**
	 * dsn
	 */

	//private String dsn;

	/**
	 * originExchangeOffice
	 */

	//private String originExchangeOffice;

	/**
	 * destinationExchangeOffice
	 */

	//private String destinationExchangeOffice;

	/**
	 * mailClass
	 */

//	private String mailSubclass;

	/**
	 * mailCategoryCode
	 */

	//private String mailCategoryCode;
	
	/**
	 * year
	 */

	//private int year;

	/**
	 * mailSequenceNumber
	 */

	private long mailSequenceNumber;

	/**
	 * mailIdr
	 */
//	private String mailIdr;
	
	/**
	 * Default Constructor
	 */
	public MailInConsignmentPK() {
	}

	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return int
	 */
	public int hashCode() {

		return new StringBuffer(companyCode).append(consignmentNumber).append(
				paCode).append(consignmentSequenceNumber).
				append(mailSequenceNumber).toString().hashCode();
	}

	public void setPaCode(java.lang.String paCode) {
		this.paCode=paCode;
	}

	public java.lang.String getPaCode() {
		return this.paCode;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	
	public void setConsignmentNumber(java.lang.String consignmentNumber) {
		this.consignmentNumber=consignmentNumber;
	}

	public java.lang.String getConsignmentNumber() {
		return this.consignmentNumber;
	}

	public void setConsignmentSequenceNumber(int consignmentSequenceNumber) {
		this.consignmentSequenceNumber=consignmentSequenceNumber;
	}

	public int getConsignmentSequenceNumber() {
		return this.consignmentSequenceNumber;
	}

	



	public long getMailSequenceNumber() {
		return mailSequenceNumber;
	}

	public void setMailSequenceNumber(long mailSequenceNumber) {
		this.mailSequenceNumber = mailSequenceNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(308);
		sbul.append("MailInConsignmentPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', consignmentNumber '").append(this.consignmentNumber);
		sbul.append("', consignmentSequenceNumber '").append(
				this.consignmentSequenceNumber);
	
		sbul.append("', paCode '").append(this.paCode);
		sbul.append("', mailIdr '").append(this.mailSequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
