/*
 * MailResditFileLogPK.java Created on Oct 04, 2010
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * TODO Add the purpose of this class
 * 
 * @author A-2135
 * 
 */
/*
 * Revision History
 * --------------------------------------------------------------------------
 * Revision Date 			Author 				Description
 * ------------------------------------------------------------------------- 
 * 0.1      Sep 05, 2010 	A-2135				First Draft
 */

@Embeddable
public class MailResditFileLogPK implements Serializable {
	
	/**
	 * The companyCode
	 */
	private String companyCode;
	
	/**
	 * The interchangeControlReference
	 */
	private String interchangeControlReference;
	
	/**
	 * The recipientID
	 */
	private String recipientID;

	

	/**
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((this.hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(interchangeControlReference).append(
				recipientID).hashCode();
	}

	/**
	 * @return the companyCode
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * @param companyCode the companyCode to set
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * @return the interchangeControlReference
	 */
	public String getInterchangeControlReference() {
		return interchangeControlReference;
	}

	/**
	 * @param interchangeControlReference the interchangeControlReference to set
	 */
	public void setInterchangeControlReference(String interchangeControlReference) {
		this.interchangeControlReference = interchangeControlReference;
	}

	/**
	 * @return the recipientID
	 */
	public String getRecipientID() {
		return recipientID;
	}

	/**
	 * @param recipientID the recipientID to set
	 */
	public void setRecipientID(String recipientID) {
		this.recipientID = recipientID;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(104);
		sbul.append("MailResditFileLogPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', interchangeControlReference '").append(
				this.interchangeControlReference);
		sbul.append("', recipientID '").append(this.recipientID);
		sbul.append("' ]");
		return sbul.toString();
	}

	
	
	

	
}
