/*
 * MailbagPK.java Created on Jun 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.SequenceKeyGenerator;

/**
 * @author A-5991
 *
 */
@SequenceKeyGenerator(name="ID_GEN",sequence="MALMST_SEQ")
@Embeddable
public class MailbagPK implements Serializable {
    /**
     * 
     */
	private String companyCode;    
    
	/**
     * The mailSequenceNumber
     */
	private long mailSequenceNumber;
	
    /**
     * @param other
     * @return
     */
    public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
    /**
     * @return
     */
	public int hashCode() {

		return new StringBuffer(companyCode).
				
				append(mailSequenceNumber).
				toString().hashCode();
	}

	
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	
	@KeyCondition(column = "CMPCOD")
	public String getCompanyCode() {
		return this.companyCode;
	}
	
	
	 @Key(generator = "ID_GEN", startAt = "1" )
	public long getMailSequenceNumber() {
		return mailSequenceNumber;
	}
	public void setMailSequenceNumber(long mailSequenceNumber) {
		this.mailSequenceNumber = mailSequenceNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(205);
		sbul.append("MailbagPK [ ");
		sbul.append("companyCode '").append(this.companyCode);

		sbul.append("mailSequenceNumber '").append(this.mailSequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
