/*
 * MailActivityDetailPK.java Created on June 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;
import javax.persistence.Embeddable;

/**
 * 
 * @author a-3109
 * 
 */
@Embeddable
public class MailActivityDetailPK implements Serializable {
	/**
	 * Company code
	 */
	private String companyCode;

	/**
	 * Mail bag number
	 */
	private String mailBagNumber;

	/**
	 * Service level activity
	 */
	private String slaActivity;

	/**
	 * 
	 * @param companycode
	 * @param mailBagNumber
	 * @param slaActivity
	 */
	public MailActivityDetailPK(String companycode, String mailBagNumber,
			String slaActivity) {
		this.companyCode = companycode;
		this.mailBagNumber = mailBagNumber;
		this.slaActivity = slaActivity;
	}

	/**
	 * Instantiates a new mail activity detail pk.
	 */
	public MailActivityDetailPK() {

	}

	/**
	 * @param other
	 * @return
	 * 
	 */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if (other != null) {
			if (hashCode() == other.hashCode()) {
				isEqual = true;
			}
		}
		return isEqual;
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).append(mailBagNumber)
				.append(slaActivity).toString().hashCode();
	}

	public void setMailBagNumber(java.lang.String mailBagNumber) {
		this.mailBagNumber = mailBagNumber;
	}

	public java.lang.String getMailBagNumber() {
		return this.mailBagNumber;
	}

	public void setSlaActivity(java.lang.String slaActivity) {
		this.slaActivity = slaActivity;
	}

	public java.lang.String getSlaActivity() {
		return this.slaActivity;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(91);
		sbul.append("MailActivityDetailPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', mailBagNumber '").append(this.mailBagNumber);
		sbul.append("', slaActivity '").append(this.slaActivity);
		sbul.append("' ]");
		return sbul.toString();
	}

}
