/*
 * MailbagHistoryPK.java Created on Jun 28, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-5991
 *

 */

@KeyTable(table = "MALHISKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "MALHISKEY", key = "HIS_SER_NUM")
@Embeddable 
public class MailbagHistoryPK implements Serializable {
    /**
     * The companyCode 
     */
     private String companyCode;
    /**
     * The dsn
     */
 //   private String dsn;
    /**
     * The originExchangeOffice
     */
 //   private String originExchangeOffice;
    /**
     * The destinationExchangeOffice
     */
  //  private String destinationExchangeOffice;
   
    /**
     * The mailSubclass
     */
 //   private String mailSubclass;
    /**
     * The mailCategoryCode
     */
  //  private String mailCategoryCode;
    /**
      * The year
      */   
 //   private int year;
    

    /**
     * The mailStatus  
     */
  //  private String mailStatus;
    
    /**
     * The historySequenceNumber
     */
    private int historySequenceNumber;
    
    /**
     * mailSequenceNumber
     */
    private long mailSequenceNumber;
    /**
     * @param other
     *  @return 
     *      
     */
    public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
    /**
     * @return
     */
	public int hashCode() {

		return new StringBuffer(companyCode).
				append(mailSequenceNumber).
				append(historySequenceNumber).
				toString().hashCode();
	}
    

	public void setHistorySequenceNumber(int historySequenceNumber) {
		this.historySequenceNumber=historySequenceNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public int getHistorySequenceNumber() {
		return this.historySequenceNumber;
	}


	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	
	
	@KeyCondition(column = "MALSEQNUM")
	public long getMailSequenceNumber() {
		return mailSequenceNumber;
	}
	public void setMailSequenceNumber(long mailSequenceNumber) {
		this.mailSequenceNumber = mailSequenceNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(267);
		sbul.append("MailbagHistoryPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("mailIdr '").append(this.mailSequenceNumber);
		sbul.append("', historySequenceNumber '").append(
				this.historySequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
