/*
 * MailbagAuditPK.java Created on Jun 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author a-5991
 *
 */
@KeyTable(table="MALAUDKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="AUDSEQ_GEN",table="MALAUDKEY",key="MALAUD_SEQNUM")
@Embeddable
public class MailbagAuditPK implements Serializable {
     /**
      * The companyCode
      */

    private String companyCode;
    /**
     * The Dsn
     */

    //private String dsn;
    /**
     * The originExchangeOffice
     */

    //private String originExchangeOffice;
    /**
     * The destinationExchangeOffice
     */

   // private String destinationExchangeOffice;
    /**
     * The mailSubClass
     */

    //private String mailSubclass;

    /**
     * The mailCategory
     */

   // private String mailCategoryCode;

    /**
     * The year
     */

    //private int year;
    /**
     * The mailbagId
     */

    //private String mailbagId;
    /**
     * The key generated SequenceNumber
     */

    private long sequenceNumber;
    private long mailSequenceNumber;
    /**
     * @param other
     * @return
     */
    public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
    /**
     * @return
     */
	public int hashCode() {

		return new StringBuffer(companyCode).
			/*append(dsn).
			append(originExchangeOffice).
			append(destinationExchangeOffice).
			append(mailSubclass).
			append(mailCategoryCode).
			append(year).*/
			//append(mailbagId).
			append(mailSequenceNumber).
			append(sequenceNumber).
				toString().hashCode();
	}

	/*public void setYear(int year) {
		this.year=year;
	}
    @KeyCondition(column="YER")
	public int getYear() {
		return this.year;
	}

	public void setOriginExchangeOffice(java.lang.String originExchangeOffice) {
		this.originExchangeOffice=originExchangeOffice;
	}
    @KeyCondition(column="ORGEXGOFC")
	public java.lang.String getOriginExchangeOffice() {
		return this.originExchangeOffice;
	}*/

	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
    @Key(generator="AUDSEQ_GEN",startAt="1")
	public long getSequenceNumber() {
		return this.sequenceNumber;
	}

	/*public void setDsn(java.lang.String dsn) {
		this.dsn=dsn;
	}
    @KeyCondition(column="DSN")
	public java.lang.String getDsn() {
		return this.dsn;
	}
*/
	/*public void setMailbagId(java.lang.String mailbagId) {
		this.mailbagId=mailbagId;
	}
    @KeyCondition(column="MALIDR")
	public java.lang.String getMailbagId() {
		return this.mailbagId;
	}
*/
	/*public void setDestinationExchangeOffice(java.lang.String destinationExchangeOffice) {
		this.destinationExchangeOffice=destinationExchangeOffice;
	}
    @KeyCondition(column="DSTEXGOFC")
	public java.lang.String getDestinationExchangeOffice() {
		return this.destinationExchangeOffice;
	}*/

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
     @KeyCondition(column="CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * @param mailSequenceNumber the mailSequenceNumber to set
	 */
	public void setMailSequenceNumber(long mailSequenceNumber) {
		this.mailSequenceNumber = mailSequenceNumber;
	}
	@KeyCondition(column="MALSEQNUM")
	public long getMailSequenceNumber() {
		return mailSequenceNumber;
	}
	/*public void setMailCategoryCode(java.lang.String mailCategoryCode) {
		this.mailCategoryCode=mailCategoryCode;
	}
    @KeyCondition(column="MALCTGCOD")
	public java.lang.String getMailCategoryCode() {
		return this.mailCategoryCode;
	}

	public void setMailSubclass(java.lang.String mailSubclass) {
		this.mailSubclass=mailSubclass;
	}
    @KeyCondition(column="MALSUBCLS")
	public java.lang.String getMailSubclass() {
		return this.mailSubclass;
	}*/
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(236);
		sbul.append("MailbagAuditPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("mailSequenceNumber '" ).append(this.mailSequenceNumber);
		/*sbul.append("', destinationExchangeOffice '").append(
				this.destinationExchangeOffice);
		sbul.append("', dsn '").append(this.dsn);
		sbul.append("', mailCategoryCode '").append(this.mailCategoryCode);
		sbul.append("', mailSubclass '").append(this.mailSubclass);*/
		//sbul.append("', mailbagId '").append(this.mailbagId);
		/*sbul.append("', originExchangeOffice '").append(
				this.originExchangeOffice);*/
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		//sbul.append("', year '").append(this.year);
		sbul.append("' ]");
		return sbul.toString();
	}
}
