/*
 * MailbagInULDAtAirportPK.java Created on Jun 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author a-5991
 *
 */
@Embeddable
public class MailbagInULDAtAirportPK implements Serializable {
    /**
     * The companyCode
     */ 
	private String companyCode; 
	
	/**
	 * The carrierId
	 */
    private int carrierId;  
    /**
     * The uldNumber 
     */
    private String uldNumber;
    /**
     * The airportCode
     */
    private String airportCode;
    
    /**
     * mailIdr
     */
 //   private String mailIdr;
    
    /**
     * mailSequenceNumber
     * 
     */
    private long mailSequenceNumber;
    /**
     * The dsn
     */
  //  private String dsn;
    /**
     * The originExchangeOffice
     */
  //  private String originExchangeOffice;
    /**
     * The destinationExchangeOffice
     */
  //  private String destinationExchangeOffice;
    /**
     * The mailSubclass
     */
  //  private String mailSubclass;
    
    /**
     * The mailSubclass
     */
  //  private String mailCategoryCode;
    
    /**
     * The year
     */
  //  private int year;
    /**
     * The MailID
     */
 //   private String mailId;
    /**
     * @param other
     * @return
     */
    public boolean equals(Object other) {
 		return (other != null) && ((hashCode() == other.hashCode()));
 	}
    /**
     *@return
     */
 	public int hashCode() {
 	    
 		return new StringBuffer(companyCode). 			
 				append(carrierId).
 				append(uldNumber). 
 				append(airportCode).
 				append(mailSequenceNumber)	.
 				toString().hashCode();
 	}    

	

	public void setAirportCode(java.lang.String airportCode) {
		this.airportCode=airportCode;
	}

	public java.lang.String getAirportCode() {
		return this.airportCode;
	}

	public void setCarrierId(int carrierId) {
		this.carrierId=carrierId;
	}

	public int getCarrierId() {
		return this.carrierId;
	}

	
	public void setUldNumber(java.lang.String uldNumber) {
		this.uldNumber=uldNumber;
	}

	public java.lang.String getUldNumber() {
		return this.uldNumber;
	}

	
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	

	public long getMailSequenceNumber() {
		return mailSequenceNumber;
	}
	public void setMailSequenceNumber(long mailSequenceNumber) {
		this.mailSequenceNumber = mailSequenceNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:52 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(281);
		sbul.append("MailbagInULDAtAirportPK [ ");
		sbul.append("airportCode '").append(this.airportCode);
		sbul.append("', carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', mailSequenceNumber '").append(this.mailSequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
