/*
 * OnwardRouteForSegmentPK.java Created on Jun 7, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author a-1303
 * 
 */
@Embeddable
@KeyTable(table = "MALONWRTGSEGKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "MALONWRTGSEGKEY", key = "RTG_SER_NUM")
public class OnwardRouteForSegmentPK implements Serializable {
	/**
	 * The companyCode
	 */

	private String companyCode;

	/**
	 * The uldNumber
	 */

	private String uldNumber;

	/**
	 * The carrierId
	 */

	private int carrierId;

	/**
	 * The flightNumber
	 */

	private String flightNumber;

	/**
	 * The flightSequenceNumber
	 */

	private long flightSequenceNumber;

	/**
	 * The segmentSerialNumber
	 */

	private int segmentSerialNumber;

	/**
	 * The routingSerialNumber
	 */

	private int routingSerialNumber;


	/**
	 * @author A-1936
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {

		return new StringBuffer(companyCode).append(uldNumber)
				.append(carrierId).append(flightNumber).append(
						flightSequenceNumber).append(segmentSerialNumber)
				.append(routingSerialNumber).toString().hashCode();
	}


	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setSegmentSerialNumber(int segmentSerialNumber) {
		this.segmentSerialNumber=segmentSerialNumber;
	}
	@KeyCondition(column = "SEGSERNUM")
	public int getSegmentSerialNumber() {
		return this.segmentSerialNumber;
	}

	public void setUldNumber(java.lang.String uldNumber) {
		this.uldNumber=uldNumber;
	}
	@KeyCondition(column = "ULDNUM")
	public java.lang.String getUldNumber() {
		return this.uldNumber;
	}

	public void setFlightSequenceNumber(long flightSequenceNumber) {
		this.flightSequenceNumber=flightSequenceNumber;
	}
	@KeyCondition(column = "FLTSEQNUM")
	public long getFlightSequenceNumber() {
		return this.flightSequenceNumber;
	}

	public void setFlightNumber(java.lang.String flightNumber) {
		this.flightNumber=flightNumber;
	}
	@KeyCondition(column = "FLTNUM")
	public java.lang.String getFlightNumber() {
		return this.flightNumber;
	}

	public void setCarrierId(int carrierId) {
		this.carrierId=carrierId;
	}
	@KeyCondition(column = "FLTCARIDR")
	public int getCarrierId() {
		return this.carrierId;
	}

	public void setRoutingSerialNumber(int routingSerialNumber) {
		this.routingSerialNumber=routingSerialNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public int getRoutingSerialNumber() {
		return this.routingSerialNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(206);
		sbul.append("OnwardRouteForSegmentPK [ ");
		sbul.append("carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', flightNumber '").append(this.flightNumber);
		sbul.append("', flightSequenceNumber '").append(
				this.flightSequenceNumber);
		sbul.append("', routingSerialNumber '")
				.append(this.routingSerialNumber);
		sbul.append("', segmentSerialNumber '")
				.append(this.segmentSerialNumber);
		sbul.append("', uldNumber '").append(this.uldNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
