/*
 * PartnerCarrierPK.java Created on Aug 10, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;


/**
 * @author a-1303
 
 */
@Embeddable
public class PartnerCarrierPK implements Serializable {
    
	/**
	 * The CompanyCode
	 */
	
	private String companyCode;    
    /**
     * The OwnCarrierCode
     */
	private String ownCarrierCode;    
    /**
     * The PartnerCarrierCode
     */
	private String partnerCarrierCode;    
    /**
     * The AirportCode
     */
	private String airportCode;
    /**
     * The Equals Method .. 
     * @param other 
     * @return
     */
    public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
    /**
     * The hashCode implementation..
     * @return
     */
	public int hashCode() {

		return new StringBuffer(companyCode).
			append(ownCarrierCode).
			append(partnerCarrierCode).
			append(airportCode).
			toString().hashCode();
	}

	public void setPartnerCarrierCode(java.lang.String partnerCarrierCode) {
		this.partnerCarrierCode=partnerCarrierCode;
	}

	public java.lang.String getPartnerCarrierCode() {
		return this.partnerCarrierCode;
	}

	public void setOwnCarrierCode(java.lang.String ownCarrierCode) {
		this.ownCarrierCode=ownCarrierCode;
	}

	public java.lang.String getOwnCarrierCode() {
		return this.ownCarrierCode;
	}

	public void setAirportCode(java.lang.String airportCode) {
		this.airportCode=airportCode;
	}

	public java.lang.String getAirportCode() {
		return this.airportCode;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(118);
		sbul.append("PartnerCarrierPK [ ");
		sbul.append("airportCode '").append(this.airportCode);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', ownCarrierCode '").append(this.ownCarrierCode);
		sbul.append("', partnerCarrierCode '").append(this.partnerCarrierCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
