/*
 * PostalAdministrationDetailsPK.java Created on June 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-3108
 *
 */
@Embeddable
public class PostalAdministrationDetailsPK implements Serializable {
	
	/**
	 * companyCode
	 */	
	private String companyCode;
	
	/**
	 * poacod
	 */	
	private String poacod;
	
	/**
	 * parcod
	 */	
	private String parcod;
	
	/**
	 * profInv
	 */	
	private String sernum;
	
	
	public String getCompanyCode() {
		return companyCode;
	}
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	
	public String getPoacod() {
		return poacod;
	}
	public void setPoacod(String poacod) {
		this.poacod = poacod;
	}
	
	public String getParcod() {
		return parcod;
	}
	public void setParcod(String parcod) {
		this.parcod = parcod;
	}
	
	public String getSernum() {
		return sernum;
	}
	public void setSernum(String sernum) {
		this.sernum = sernum;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(106);
		sbul.append("PostalAdministrationDetailsPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', parcod '").append(this.parcod);
		sbul.append("', poacod '").append(this.poacod);
		sbul.append("', sernum '").append(this.sernum);
		sbul.append("' ]");
		return sbul.toString();
	}
	
	/**
	 * @param other
	 * @param boolean
	 */
	 public boolean equals(Object other) {
	        return (other != null)&& (other instanceof PostalAdministrationDetailsPK) && (hashCode() == other.hashCode());
	    }
	 /**
	  * @return int
	  */
	 public int hashCode() {

	        return new StringBuffer(companyCode).append(poacod).append(parcod).append(
	        		sernum).toString().hashCode();
	    }
	

}
