/*
 * PostalAdministrationPK.java Created on June 27, 2016
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author a-3109
 */
@Embeddable
public class PostalAdministrationPK implements Serializable {
	 
	  /**
	   * The companyCode
	   */

    private String companyCode;
	/**
	 * The paCode
	 */

    private String paCode;
    
	  /**
	   * @param other
	   * @return
	   */
	  public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
    /**
     *@return 
     * 
     */
	public int hashCode() {
		return new StringBuffer(companyCode).    		
			append(paCode).
			toString().hashCode();
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setPaCode(java.lang.String paCode) {
		this.paCode=paCode;
	}

	public java.lang.String getPaCode() {
		return this.paCode;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(63);
		sbul.append("PostalAdministrationPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', paCode '").append(this.paCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
