/*
 * ResditEventPK.java Created on Sep 22, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 *  
 * @author A-1883
 * 
 */
/*
 * Revision History
 * -------------------------------------------------------------------------
 * Revision 		Date 					Author 		Description
 * ------------------------------------------------------------------------- 
 * 0.1     		  Sep 22, 2006			    a-1883		Created
 */
@Embeddable
public class ResditEventPK implements Serializable {

    /**
     * Company Code
     */
    private String companyCode;
    /**
     *  Consignment Documen tNumber
     */
    private String consignmentDocumentNumber; 
    /**
     * Event Code
     */
    private String eventCode;
    /**
     * Event Port
     */
    private String eventPort;
    /**
     * Message Sequence Number
     */
    private long messageSequenceNumber;
    
    /**
     * @param other
     * @return boolean
     */
    public boolean equals(Object other) {
        return (other != null) && ((hashCode() == other.hashCode()));
    }
   /**
    * @return int
    */
    public int hashCode() {
        
        return new StringBuffer().
                append(companyCode).
                append(consignmentDocumentNumber).
                append(eventCode).
                append(eventPort).
                append(messageSequenceNumber).
                toString().hashCode();
    }    

	public void setConsignmentDocumentNumber(java.lang.String consignmentDocumentNumber) {
		this.consignmentDocumentNumber=consignmentDocumentNumber;
	}

	public java.lang.String getConsignmentDocumentNumber() {
		return this.consignmentDocumentNumber;
	}

	public void setMessageSequenceNumber(long messageSequenceNumber) {
		this.messageSequenceNumber=messageSequenceNumber;
	}

	public long getMessageSequenceNumber() {
		return this.messageSequenceNumber;
	}

	public void setEventCode(java.lang.String eventCode) {
		this.eventCode=eventCode;
	}

	public java.lang.String getEventCode() {
		return this.eventCode;
	}

	public void setEventPort(java.lang.String eventPort) {
		this.eventPort=eventPort;
	}

	public java.lang.String getEventPort() {
		return this.eventPort;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(148);
		sbul.append("ResditEventPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', consignmentDocumentNumber '").append(
				this.consignmentDocumentNumber);
		sbul.append("', eventCode '").append(this.eventCode);
		sbul.append("', eventPort '").append(this.eventPort);
		sbul.append("', messageSequenceNumber '").append(
				this.messageSequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
