/*
 * ResditConfigurationPK.java Created on Feb 1, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 *  
 * @author A-1739
 * 
 */
/*
 * Revision History
 * -------------------------------------------------------------------------
 * Revision 		Date 					Author 		Description
 * ------------------------------------------------------------------------- 
 * 0.1     		  Feb 1, 2007			A-1739		Created
 */
@Embeddable
public class ResditConfigurationPK implements Serializable {
	
	private String companyCode;
	
	private int carrierId;
	
	private String transactionId;

	@Override
	public int hashCode() {
		return new StringBuilder(companyCode).
						append(carrierId).
						append(transactionId).
						toString().hashCode();
	}
	
	@Override
	public boolean equals(Object other) {
		return (other != null) && (this.hashCode() == other.hashCode());
	}

	public void setCarrierId(int carrierId) {
		this.carrierId=carrierId;
	}

	public int getCarrierId() {
		return this.carrierId;
	}

	public void setTransactionId(java.lang.String transactionId) {
		this.transactionId=transactionId;
	}

	public java.lang.String getTransactionId() {
		return this.transactionId;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(90);
		sbul.append("ResditConfigurationPK [ ");
		sbul.append("carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', transactionId '").append(this.transactionId);
		sbul.append("' ]");
		return sbul.toString();
	}
}
