/*
 * RoutingInConsignmentPK.java Created on Jun 27 , 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author a-5991
 */
@KeyTable(table = "MALCSGRTGKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "MALCSGRTGKEY", key = "RTG_SER_NUM")
@Embeddable
public class RoutingInConsignmentPK implements Serializable {
	/**
	 * companyCode
	 */

	private  String companyCode;
	/**
	 * consignmentNumber
	 */

	private String consignmentNumber;
	/**
	 * paCode
	 */

	private String paCode;
	/**
	 * consignmentSequenceNumber
	 */

	private int consignmentSequenceNumber;
	/**
	 * routingSerialNumber - key based generation 
	 */

	private int routingSerialNumber;
	/**
	 * @param other
	 * @return boolean
	 */ 
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 *  Default constructor
	 */
	public RoutingInConsignmentPK (){
	}
	/**
	 * @return int 
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
		append(consignmentNumber).
		append(paCode).
		append(consignmentSequenceNumber). 		
		append(routingSerialNumber).
		toString().hashCode();
	}  

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column="CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setPaCode(java.lang.String paCode) {
		this.paCode=paCode;
	}
	 @KeyCondition(column="POACOD")
	public java.lang.String getPaCode() {
		return this.paCode;
	}

	public void setRoutingSerialNumber(int routingSerialNumber) {
		this.routingSerialNumber=routingSerialNumber;
	}
	 @Key(generator="ID_GEN",startAt="1")
	public int getRoutingSerialNumber() {
		return this.routingSerialNumber;
	}

	public void setConsignmentNumber(java.lang.String consignmentNumber) {
		this.consignmentNumber=consignmentNumber;
	}
	 @KeyCondition(column="CSGDOCNUM")
	public java.lang.String getConsignmentNumber() {
		return this.consignmentNumber;
	}

	public void setConsignmentSequenceNumber(int consignmentSequenceNumber) {
		this.consignmentSequenceNumber=consignmentSequenceNumber;
	}
	 @KeyCondition(column="CSGSEQNUM")
	public int getConsignmentSequenceNumber() {
		return this.consignmentSequenceNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(160);
		sbul.append("RoutingInConsignmentPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', consignmentNumber '").append(this.consignmentNumber);
		sbul.append("', consignmentSequenceNumber '").append(
				this.consignmentSequenceNumber);
		sbul.append("', paCode '").append(this.paCode);
		sbul.append("', routingSerialNumber '")
				.append(this.routingSerialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
