/*
 * TransferManifestDSNPK.java Created on June 27, 2016
 *
 * Copyright 2008 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-3109
 * 
 */
@Embeddable
public class TransferManifestDSNPK implements Serializable {

	/**
	 * The companyCode
	 */
	private String companyCode;
	/**
	 * The transferManifestId
	 */
	private String transferManifestId;
    /**
     * The mailSequenceNumber
     */
    private long mailSequenceNumber;
/*	*//**
	 * The dsn
	 *//*
	private String dsn;
	*//**
	 * The originExchangeOffice
	 *//*
	private String originExchangeOffice;
	*//**
	 * The destinationExchangeOffice
	 *//*
	private String destinationExchangeOffice;

	*//**
	 * category code
	 *//*
	private String mailCategoryCode;

	*//**
	 * The mailClass
	 *//*
	private String mailSubclass;

	*//**
	 * The year
	 * *//*
	private int year;*/

	/**
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if (other != null) {
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;
	}

	/**
	 * @return
	 */
	public int hashCode() {

		return new StringBuffer(companyCode).append(transferManifestId).
				append(mailSequenceNumber).toString().hashCode();
	}

	public String getCompanyCode() {
		return companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getTransferManifestId() {
		return transferManifestId;
	}

	public void setTransferManifestId(String transferManifestId) {
		this.transferManifestId = transferManifestId;
	}
	
	

/*	public String getDestinationExchangeOffice() {
		return destinationExchangeOffice;
	}

	public void setDestinationExchangeOffice(String destinationExchangeOffice) {
		this.destinationExchangeOffice = destinationExchangeOffice;
	}

	public String getDsn() {
		return dsn;
	}

	public void setDsn(String dsn) {
		this.dsn = dsn;
	}

	public String getMailCategoryCode() {
		return mailCategoryCode;
	}

	public void setMailCategoryCode(String mailCategoryCode) {
		this.mailCategoryCode = mailCategoryCode;
	}

	public String getMailSubclass() {
		return mailSubclass;
	}

	public void setMailSubclass(String mailSubclass) {
		this.mailSubclass = mailSubclass;
	}

	public String getOriginExchangeOffice() {
		return originExchangeOffice;
	}

	public void setOriginExchangeOffice(String originExchangeOffice) {
		this.originExchangeOffice = originExchangeOffice;
	}

	public int getYear() {
		return year;
	}

	public void setYear(int year) {
		this.year = year;
	}*/

	public long getMailSequenceNumber() {
		return mailSequenceNumber;
	}

	public void setMailSequenceNumber(long mailSequenceNumber) {
		this.mailSequenceNumber = mailSequenceNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(226);
		sbul.append("TransferManifestDSNPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', transferManifestId '").append(this.transferManifestId);
		sbul.append("', mailSequenceNumber '").append(this.mailSequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}

}
