/*
 * TransferManifestPK.java Created on Jun 27, 2016
 *
 * Copyright 2008 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-5991
 *
 */
@Embeddable
public class TransferManifestPK implements Serializable {
    
	/**
	 *The  companyCode
	 */
	private String companyCode;
	/**
	 * The transferManifestId
	 */
    private String transferManifestId;
   
    
    /**
     * @param other
     * @return 
     */
    public boolean equals(Object other) {
    	boolean isEqual = false;
		if(other != null ){
			isEqual = hashCode() == other.hashCode();
		}
		return isEqual;		
	}
    /**
     * @return 
     */
	public int hashCode() {
	    
		return new StringBuffer(companyCode).
				append(transferManifestId).
				toString().hashCode();
	}
	public String getCompanyCode() {
		return companyCode;
	}
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	public String getTransferManifestId() {
		return transferManifestId;
	}
	public void setTransferManifestId(String transferManifestId) {
		this.transferManifestId = transferManifestId;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(71);
		sbul.append("TransferManifestPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', transferManifestId '").append(this.transferManifestId);
		sbul.append("' ]");
		return sbul.toString();
	}      

}
