/*
 * ULDAtAirportPK.java Created on June 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author a-3109
 * 
 */
@Embeddable
public class ULDAtAirportPK implements Serializable {
	/**
	 * The companycode
	 */
	private String companyCode;

	/**
	 * The uldNumber
	 */
	private String uldNumber;

	/**
	 * The airportCode
	 */
	private String airportCode;

	/**
	 * The carrierId
	 */
	private int carrierId;
	
	

	/**
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).append(carrierId)
				.append(uldNumber).append(airportCode).toString().hashCode();
	}

	public void setCarrierId(int carrierId) {
		this.carrierId = carrierId;
	}

	public int getCarrierId() {
		return this.carrierId;
	}

	public void setAirportCode(java.lang.String airportCode) {
		this.airportCode = airportCode;
	}

	public java.lang.String getAirportCode() {
		return this.airportCode;
	}

	public void setUldNumber(java.lang.String uldNumber) {
		this.uldNumber = uldNumber;
	}

	public java.lang.String getUldNumber() {
		return this.uldNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(102);
		sbul.append("ULDAtAirportPK [ ");
		sbul.append("airportCode '").append(this.airportCode);
		sbul.append("', carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', uldNumber '").append(this.uldNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
