/*
 * UldResditPK.java Created on June 27, 2016
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.operations;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * 
 * 
 * @author A-3109
 * 
 */

@KeyTable(table = "MALULDRDTKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "MALULDRDTKEY", key = "RDT_SEQNUM")
@Embeddable
/**
 * @author A-1936
 * 
 */
public class UldResditPK implements Serializable {

	/**
	 * The CompanyCode
	 */

	private String companyCode;

	/**
	 * The UldNumber
	 */

	private String uldNumber;

	/**
	 * The EventCode
	 */

	private String eventCode;

	/**
	 * The SequenceNumber
	 */

	private long sequenceNumber;

	/**
	 * @author A-1936 The Equals Method for the Entity
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {

		return (other != null) && ((this.hashCode() == other.hashCode()));
	}

	/**
	 * The HashCode Implementation of the Class.
	 * 
	 * @return
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(uldNumber)
				.append(eventCode).append(sequenceNumber).toString().hashCode();
	}

	public void setEventCode(java.lang.String eventCode) {
		this.eventCode = eventCode;
	}

	@KeyCondition(column = "EVTCOD")
	public java.lang.String getEventCode() {
		return this.eventCode;
	}

	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	@Key(generator = "ID_GEN", startAt = "1")
	public long getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setUldNumber(java.lang.String uldNumber) {
		this.uldNumber = uldNumber;
	}

	@KeyCondition(column = "ULDNUM")
	public java.lang.String getUldNumber() {
		return this.uldNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:53 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(102);
		sbul.append("UldResditPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', eventCode '").append(this.eventCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("', uldNumber '").append(this.uldNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
