snow:
  type-mappings:
    #Altername in Promethues (As defined in the Prom Rule) to Type name as to be mapped in SNOW
    TargetDown : 'Availability'
    JDBCPoolConnectionsPending: 'Hikari-JDBC-Pool'
    KafkaConsumerLagRecords: 'Kafka-Consumer'
    default: 'Availability'

#notify:
#  snow:
#    enabled: true
#    instanceName:
#    basic-auth:
#      userId:
#      password:
#  aws:
#    sns:
#      enabled: true
#      email:
#        active:
#          default:
#          #<alert-name>:<emails as csv>
#        inactive:
#        # - <alert-name>
#        # - <alert-name>