/*
 * BillingLineParameterPK.java Created on Feb 23, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.audit.Audit;




/**
 * @author a-1556
 *
 */


@Embeddable
public class BillingLineParameterPK implements Serializable {
    
    /**
     * Company Code
     */
    private String companyCode;
    /**
     * Billing Matrix ID
     */
    private String billingMatrixID;
    /**
     * Billing Line Sequence Number
     */
    private int billingLineSequenceNumber;
    /**
     * Parameter Code
     */
    private String parameterCode;
/*    *//**
     * Partameter Value
     *//*
    private String parameterValue;*/
    
    
  
    /**
     * 
     */
    public BillingLineParameterPK() { 
    }
	/**
	 * 
	 * @param companyCode
	 * @param billingMatrixID
	 * @param billingLineSequenceNumber
	 * @param parameterCode
	 * @param parameterValue
	 */
    public BillingLineParameterPK(String companyCode, String billingMatrixID,
			int billingLineSequenceNumber,String parameterCode) {
		this.companyCode = companyCode;
		this.billingMatrixID = billingMatrixID;
		this.billingLineSequenceNumber = billingLineSequenceNumber;
		this.parameterCode = parameterCode;
		//this.parameterValue = parameterValue;	
	}
	
	/**
	* @param other
	* @return boolean
	*/
	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null){
			isEqual = this.hashCode() == other.hashCode();
		}
		return isEqual;
	}
	
	/**
	* @return int
	*/
	public int hashCode() {
	return new StringBuffer(companyCode).
		append(billingMatrixID).
		append(billingLineSequenceNumber).
		append(parameterCode).
		//append(parameterValue).	
		toString().hashCode();
	}	
	
	
	

	/**
	 * 
	 * @param billingMatrixID
	 */
	public void setBillingMatrixID(java.lang.String billingMatrixID) {
		this.billingMatrixID=billingMatrixID;
	}

	/**
	 * 
	 * @return
	 */
	@KeyCondition(column="BLGMTXCOD")
	public java.lang.String getBillingMatrixID() {
		return this.billingMatrixID;
	}

	/**
	 * 
	 * @param parameterCode
	 */
	public void setParameterCode(java.lang.String parameterCode) {
		this.parameterCode=parameterCode;
	}

	/**
	 * 
	 * @return
	 */
	@Audit(name="Parameter Code")
	@KeyCondition(column="PARCOD")
	public java.lang.String getParameterCode() {
		return this.parameterCode;
	}

/*	*//**
	 * 
	 * @param parameterValue
	 *//*
	public void setParameterValue(java.lang.String parameterValue) {
		this.parameterValue=parameterValue;
	}

	*//**
	 * 
	 * @return
	 *//*
	public java.lang.String getParameterValue() {
		return this.parameterValue;
	}*/

	/**
	 * 
	 * @param billingLineSequenceNumber
	 */
	public void setBillingLineSequenceNumber(int billingLineSequenceNumber) {
		this.billingLineSequenceNumber=billingLineSequenceNumber;
	}

	/**
	 * 
	 * @return
	 */
	@KeyCondition(column="BLGLINSEQNUM")
	public int getBillingLineSequenceNumber() {
		return this.billingLineSequenceNumber;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 * 
	 * @return
	 */
	@KeyCondition(column="CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(160);
		sbul.append("BillingLineParameterPK [ ");
		sbul.append("billingLineSequenceNumber '").append(
				this.billingLineSequenceNumber);
		sbul.append("', billingMatrixID '").append(this.billingMatrixID);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', parameterCode '").append(this.parameterCode);
		//sbul.append("', parameterValue '").append(this.parameterValue);
		sbul.append("' ]");
		return sbul.toString();
	}
}
