/*
 * BillingLinePK.java Created on Feb 23, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;


/**
 * @author a-1556
 *
 */

@KeyTable(table="MALMRABLGMTXLINKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="ID_GEN",table="MALMRABLGMTXLINKEY",key="BLGLINSEQNUM")
@Embeddable
public class BillingLinePK implements Serializable {
	
	
	
	/**
	 * 
	 */

	private String companyCode;
	

	private String billingMatrixID;
	

    private int billingLineSequenceNumber;
    /**
     * 
     */
    public BillingLinePK() { 

    }

    /**
     * 
     * @param companyCode
     * @param billingMatrixID
     */
    public BillingLinePK(String companyCode, String billingMatrixID){
            					
        
        this.companyCode = companyCode;
        this.billingMatrixID = billingMatrixID;
       //log.log(1,"PK are..."+this.companyCode+this.billingMatrixID);
    }
    /**
     * 
     * @param companyCode
     * @param billingMatrixID
     * @param billingSequenceNumber
     */
    public BillingLinePK(String companyCode, String billingMatrixID,int billingSequenceNumber){
            					
        
        this.companyCode = companyCode;
        this.billingMatrixID = billingMatrixID;
        this.billingLineSequenceNumber = billingSequenceNumber;
       //log.log(1,"PK are..."+this.companyCode+this.billingMatrixID);
    }
    /**
     * @param other
     * @return boolean
     */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null){
			isEqual = this.hashCode() == other.hashCode();
		}
		return isEqual;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(billingMatrixID).
				append(billingLineSequenceNumber).
				toString().hashCode();
	}	

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * 
	 * @param billingLineSequenceNumber
	 */
	public void setBillingLineSequenceNumber(int billingLineSequenceNumber) {
		this.billingLineSequenceNumber=billingLineSequenceNumber;
	}
	/**
	 * 
	 * @return
	 */
	@Key(generator = "ID_GEN", startAt = "1")
	public int getBillingLineSequenceNumber() {
		return this.billingLineSequenceNumber;
	}

	/**
	 * 
	 * @param billingMatrixID
	 */
	public void setBillingMatrixID(java.lang.String billingMatrixID) {
		this.billingMatrixID=billingMatrixID;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "BLGMTXCOD")
	public java.lang.String getBillingMatrixID() {
		return this.billingMatrixID;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(100);
		sbul.append("BillingLinePK [ ");
		sbul.append("billingLineSequenceNumber '").append(
				this.billingLineSequenceNumber);
		sbul.append("', billingMatrixID '").append(this.billingMatrixID);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
