package com.ibsplc.icargo.business.mail.mra.defaults;

/**
 * DispatchRoutingCarrierPK
 * 
 * @author A-4452
 * 
 */
import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.SequenceKeyGenerator;


@SequenceKeyGenerator(name="ID_GEN",sequence="MALMRARTGCFG_SEQ")
@Embeddable
public class DispatchRoutingCarrierPK implements Serializable{

	private String companyCode;
	private int sequenceNumber;
	
	
	public DispatchRoutingCarrierPK(){}
	
	
	
	public DispatchRoutingCarrierPK(String companyCode,int sequenceNumber) {
		
		
		this.companyCode=companyCode;
		this.sequenceNumber=sequenceNumber;
		
	}
	/**
	 * @param object
	 * @return boolean
	 */
	public boolean equals(Object object) {
		if (object != null) {
			return (hashCode() == object.hashCode());
		}
		return false;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode)
				.append(sequenceNumber).toString().hashCode();
	}

	
	@KeyCondition(column = "CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	
	@Key(generator = "ID_GEN", startAt = "1" )
	public int getSequenceNumber() {
		return sequenceNumber;
	}
	public void setSequenceNumber(int sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}
	
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(209);
		sbul.append("DispatchRoutingCarrierPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
	
	
}
