/*
 * MailContractHistoryPK.java Created on March 30, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * 
 * @author a-2518
 * 
 */
@Embeddable
public class MailContractHistoryPK implements Serializable {

	/**
	 * Company code
	 */
	private String companyCode;

	/**
	 * Mail contract reference number
	 */
	private String contractReferenceNumber;

	/**
	 * Version number
	 */
	private String versionNumber;

	/**
	 * Default constructor
	 */
	public MailContractHistoryPK() {
	}

	/**
	 * 
	 * @param companyCode
	 * @param contractReferenceNumber
	 * @param versionNumber
	 */
	public MailContractHistoryPK(String companyCode,
			String contractReferenceNumber, String versionNumber) {

		this.companyCode = companyCode;
		this.contractReferenceNumber = contractReferenceNumber;
		this.versionNumber = versionNumber;
	}

	/**
	 * @param object
	 * @return boolean
	 */
	public boolean equals(Object object) {
		boolean isEqual = false;
		if (object != null) {
			isEqual = this.hashCode() == object.hashCode();
		}
		return isEqual;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).append(contractReferenceNumber)
				.append(versionNumber).toString().hashCode();
	}

	/**
	 * 
	 * @param contractReferenceNumber
	 */
	public void setContractReferenceNumber(java.lang.String contractReferenceNumber) {
		this.contractReferenceNumber=contractReferenceNumber;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getContractReferenceNumber() {
		return this.contractReferenceNumber;
	}

	/**
	 * 
	 * @param versionNumber
	 */
	public void setVersionNumber(java.lang.String versionNumber) {
		this.versionNumber=versionNumber;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getVersionNumber() {
		return this.versionNumber;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(104);
		sbul.append("MailContractHistoryPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', contractReferenceNumber '").append(
				this.contractReferenceNumber);
		sbul.append("', versionNumber '").append(this.versionNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
