/*
 * MailInvoicDupRecepPK.java Created on Sep 17, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-2408
 *
 */
@Embeddable
public class MailInvoicDupRecepPK implements Serializable {
	
	
	private String companyCode;
	
	private String recepticleIdentifier;
	
	private String sectorOrigin;
	
	private String sectorDestination;
	
	public MailInvoicDupRecepPK(){
	
	}
	
 
/**
 * @param companyCode
 * @param recepticleIdentifier
 * @param sectorOrigin
 * @param sectorDestination
 */
public MailInvoicDupRecepPK(String companyCode, String recepticleIdentifier,String sectorOrigin,String sectorDestination) {
       super();
       this.companyCode = companyCode;
       this.recepticleIdentifier = recepticleIdentifier;
       this.sectorOrigin=sectorOrigin;
       this.sectorDestination=sectorDestination;
   }

   /**
    * @param other
    * @return boolean
    */
	public boolean equals(Object other) {
		if(other != null ){
			return (hashCode() == other.hashCode());
		}else {
			return false;
		}
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(recepticleIdentifier).
				append(sectorOrigin).
				append(sectorDestination).
				toString().hashCode();
	}

	/**
	 * @return Returns the companyCode.
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * @return Returns the recepticleIdentifier.
	 */
	public String getRecepticleIdentifier() {
		return recepticleIdentifier;
	}

	/**
	 * @param recepticleIdentifier The recepticleIdentifier to set.
	 */
	public void setRecepticleIdentifier(String recepticleIdentifier) {
		this.recepticleIdentifier = recepticleIdentifier;
	}

	/**
	 * @return Returns the sectorDestination.
	 */
	public String getSectorDestination() {
		return sectorDestination;
	}

	/**
	 * @param sectorDestination The sectorDestination to set.
	 */
	public void setSectorDestination(String sectorDestination) {
		this.sectorDestination = sectorDestination;
	}

	/**
	 * @return Returns the sectorOrigin.
	 */
	public String getSectorOrigin() {
		return sectorOrigin;
	}

	/**
	 * @param sectorOrigin The sectorOrigin to set.
	 */
	public void setSectorOrigin(String sectorOrigin) {
		this.sectorOrigin = sectorOrigin;
	}


	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(128);
		sbul.append("MailInvoicDupRecepPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', recepticleIdentifier '").append(
				this.recepticleIdentifier);
		sbul.append("', sectorDestination '").append(this.sectorDestination);
		sbul.append("', sectorOrigin '").append(this.sectorOrigin);
		sbul.append("' ]");
		return sbul.toString();
	}

	
	

}
