/*
 * MailInvoicErrorPK.java Created on Jul 19, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-2408
 *
 */
@Embeddable
public class MailInvoicErrorPK implements Serializable {
	
	
	private String companyCode;
	
	private int invoicErrorIdentifier;
	
		
	public MailInvoicErrorPK(){
	
	}
	 
   /**
 * @param companyCode
 * @param invoicErrorIdentifier
 */
public MailInvoicErrorPK(String companyCode, int invoicErrorIdentifier) {
       super();
       this.companyCode = companyCode;
       this.invoicErrorIdentifier = invoicErrorIdentifier;
       
   }

   /**
    * @param other
    * @return boolean
    */
	public boolean equals(Object other) {
		if(other != null ){
			return (hashCode() == other.hashCode());
		}else {
			return false;
		}
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(invoicErrorIdentifier).
				toString().hashCode();
	}

	/**
	 * @return Returns the companyCode.
	 */
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the invoicErrorIdentifier.
	 */
	public int getInvoicErrorIdentifier() {
		return invoicErrorIdentifier;
	}
	/**
	 * @param invoicErrorIdentifier The invoicErrorIdentifier to set.
	 */
	public void setInvoicErrorIdentifier(int invoicErrorIdentifier) {
		this.invoicErrorIdentifier = invoicErrorIdentifier;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(73);
		sbul.append("MailInvoicErrorPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', invoicErrorIdentifier '").append(
				this.invoicErrorIdentifier);
		sbul.append("' ]");
		return sbul.toString();
	}

	

}
