/*
 * MailContractDetailPK.java Created on March 30, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * 
 * @author a-2518
 * 
 */
@TableKeyGenerator(name = "ID_GEN", table = "MTKCTRDTLKEY", key = "SEQNUM")
@KeyTable(table = "MTKCTRDTLKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@Embeddable
public class MailContractDetailPK implements Serializable {

	/**
	 * Company code
	 */

	private String companyCode;

	/**
	 * Mail contract reference number
	 */

	private String contractReferenceNumber;

	/**
	 * Serial number
	 */

	private int serialNumber;

	/**
	 * Default constructor
	 */
	public MailContractDetailPK() {
	}

	/**
	 * 
	 * @param companyCode
	 * @param contractReferenceNumber
	 * @param serialNumber
	 */
	public MailContractDetailPK(String companyCode,
			String contractReferenceNumber, int serialNumber) {

		this.companyCode = companyCode;
		this.contractReferenceNumber = contractReferenceNumber;
		this.serialNumber = serialNumber;
	}

	/**
	 * @param object
	 * @return boolean
	 */
	public boolean equals(Object object) {
		boolean isEqual = false;
		if (object != null) {
			isEqual = this.hashCode() == object.hashCode();
		}
		return isEqual;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).append(contractReferenceNumber)
				.append(serialNumber).toString().hashCode();
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * 
	 * @param contractReferenceNumber
	 */
	public void setContractReferenceNumber(java.lang.String contractReferenceNumber) {
		this.contractReferenceNumber=contractReferenceNumber;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "CTRREFNUM")
	public java.lang.String getContractReferenceNumber() {
		return this.contractReferenceNumber;
	}

	/**
	 * 
	 * @param serialNumber
	 */
	public void setSerialNumber(int serialNumber) {
		this.serialNumber=serialNumber;
	}
	/**
	 * 
	 * @return
	 */
	@Key(generator = "ID_GEN", startAt = "1")
	public int getSerialNumber() {
		return this.serialNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(102);
		sbul.append("MailContractDetailPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', contractReferenceNumber '").append(
				this.contractReferenceNumber);
		sbul.append("', serialNumber '").append(this.serialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
