/*
 * MailInvoicProcessLogPK.java Created on Jul 19, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-2408
 *
 */
@Embeddable
public class MailInvoicProcessLogPK implements Serializable {
	
	
	private String companyCode;
	
	private int processIdentifier;
	
		
	public MailInvoicProcessLogPK(){
	
	}
	  /**
    *
    * @param companyCode
    * @param processIdentifier
    */
   public MailInvoicProcessLogPK(String companyCode, int processIdentifier) {
       super();
       this.companyCode = companyCode;
       this.processIdentifier = processIdentifier;
       
   }

   /**
    * @param other
    * @return boolean
    */
	public boolean equals(Object other) {
		if(other != null ){
			return (hashCode() == other.hashCode());
		}else {
			return false;
		}
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(processIdentifier).
				toString().hashCode();
	}

	/**
	 * @return Returns the companyCode.
	 */
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the processIdentifier.
	 */
	public int getProcessIdentifier() {
		return processIdentifier;
	}
	/**
	 * @param processIdentifier The processIdentifier to set.
	 */
	public void setProcessIdentifier(int processIdentifier) {
		this.processIdentifier = processIdentifier;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(74);
		sbul.append("MailInvoicProcessLogPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', processIdentifier '").append(this.processIdentifier);
		sbul.append("' ]");
		return sbul.toString();
	}
	

}
