/*
 * MailInvoicReconcileDtlPK.java Created on Sep 17, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-2408
 *
 */
@Embeddable
public class MailInvoicReconcileDtlPK implements Serializable {
	
	
	private String companyCode;
	
	private String recepticleIdentifier;
	
	private String sectorIdentifier;
	
	public MailInvoicReconcileDtlPK(){
	
	}
	
   
/**
 * @param companyCode
 * @param recepticleIdentifier
 * @param sectorIdentifier
 */
public MailInvoicReconcileDtlPK(String companyCode, String recepticleIdentifier,String sectorIdentifier) {
       super();
       this.companyCode = companyCode;
       this.recepticleIdentifier = recepticleIdentifier;
       this.sectorIdentifier=sectorIdentifier;
   }

   /**
    * @param other
    * @return boolean
    */
	public boolean equals(Object other) {
		if(other != null ){
			return (hashCode() == other.hashCode());
		}else {
			return false;
		}
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(recepticleIdentifier).
				append(sectorIdentifier).
				toString().hashCode();
	}

	/**
	 * @return Returns the companyCode.
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * @return Returns the recepticleIdentifier.
	 */
	public String getRecepticleIdentifier() {
		return recepticleIdentifier;
	}

	/**
	 * @param recepticleIdentifier The recepticleIdentifier to set.
	 */
	public void setRecepticleIdentifier(String recepticleIdentifier) {
		this.recepticleIdentifier = recepticleIdentifier;
	}

	/**
	 * @return Returns the sectorIdentifier.
	 */
	public String getSectorIdentifier() {
		return sectorIdentifier;
	}

	/**
	 * @param sectorIdentifier The sectorIdentifier to set.
	 */
	public void setSectorIdentifier(String sectorIdentifier) {
		this.sectorIdentifier = sectorIdentifier;
	}


	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(107);
		sbul.append("MailInvoicReconcileDtlPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', recepticleIdentifier '").append(
				this.recepticleIdentifier);
		sbul.append("', sectorIdentifier '").append(this.sectorIdentifier);
		sbul.append("' ]");
		return sbul.toString();
	}

	
	

}
