/*
 * MRABillingDetailsHistoryPK.java Created on Nov 7, 2008
 *
 * Copyright 2008 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-3251
 *
 */
@TableKeyGenerator(name = "ID_GEN", table = "MALMRABLGDTLHISKEY", key = "SERNUM")
@KeyTable(table = "MALMRABLGDTLHISKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@Embeddable
public class MRABillingDetailsHistoryPK  implements Serializable{
	
	
	private String companyCode;
	private int serNumber;
	private long mailSeqNumber;
	private int versionNumber;

	/**
	 * @return the serNumber
	 */
	@KeyCondition(column = "SERNUM")
	public int getSerNumber() {
		return serNumber;
	}


	/**
	 * @param serNumber the serNumber to set
	 */
	public void setSerNumber(int serNumber) {
		this.serNumber = serNumber;
	}


	
	public MRABillingDetailsHistoryPK(){}
	

	public MRABillingDetailsHistoryPK(String companyCode,int serNumber,long mailSeqNumber,int versionNumber) {
			
		this.companyCode=companyCode;
		this.serNumber=serNumber;
		this.mailSeqNumber=mailSeqNumber;
		this.versionNumber=versionNumber;
	}
	
	/**
	 * @param object
	 * @return boolean
	 */
	public boolean equals(Object object) {
		if (object != null) {
			return (hashCode() == object.hashCode());
		}
		return false;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuilder()
				.append(companyCode).append(serNumber).append(mailSeqNumber).append(versionNumber).toString().hashCode();
	}


	
	/**
	 * @return Returns the companyCode.
	 */
	@KeyCondition(column = "CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}



	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}



	/**
	 * @return the mailSeqNumber
	 */
	@KeyCondition(column = "MALSEQNUM")
	public long getMailSeqNumber() {
		return mailSeqNumber;
	}


	/**
	 * @param mailSeqNumber the mailSeqNumber to set
	 */
	public void setMailSeqNumber(long mailSeqNumber) {
		this.mailSeqNumber = mailSeqNumber;
	}


	/**
	 * @return the versionNumber
	 */
	@Key(generator = "ID_GEN", startAt = "1")
	public int getVersionNumber() {
		return versionNumber;
	}


	/**
	 * @param versionNumber the versionNumber to set
	 */
	public void setVersionNumber(int versionNumber) {
		this.versionNumber = versionNumber;
	}


	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(189);
		sbul.append("MRABillingDetailsHistoryPK [ ");
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', versionNumber '").append(this.versionNumber);
		sbul.append("', mailSeqNumber '").append(this.mailSeqNumber);
		sbul.append("', serNumber '").append(this.serNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
	
	

}
