/*
 * MRABillingMasterTempPK.java Created on Apr 2, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;
import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
/**
 * @author A-3251
 *
 */
@Embeddable
public class MRABillingMasterTempPK implements Serializable {

	private int csgSequenceNumber;
	private String csgDocumentNumber;
	private String companyCode;
	private String billingBasis;
	private String postalAuthCode;
	
	
	
    /**
	 * @return Returns the postalAuthCode.
	 */
	@KeyCondition(column = "POACOD")
	public String getPostalAuthCode() {
		return postalAuthCode;
	}
	/**
	 * @param postalAuthCode The postalAuthCode to set.
	 */
	public void setPostalAuthCode(String postalAuthCode) {
		this.postalAuthCode = postalAuthCode;
	}
	public MRABillingMasterTempPK() {
    }
    /**
     *
     * @param csgseqNumber
     * @param csgDocNumber
     * @param companyCode
     * @param billingBasis
     * @param postalAuthCode
     * 
     */
    public MRABillingMasterTempPK(int csgseqNumber,String csgDocNumber,String companyCode,
    		String billingBasis,String postalAuthCode) {
    	
    	this.csgSequenceNumber=csgseqNumber;
    	this.csgDocumentNumber=csgDocNumber;
        this.companyCode = companyCode;
        this.billingBasis = billingBasis;
        this.postalAuthCode=postalAuthCode;
        
    }

    /**
     * @param other
     * @return boolean
     */
	public boolean equals(Object other) {
		if(other != null){
			return hashCode() == other.hashCode();
		}
		else {
			return false;
		}

	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(billingBasis).
				append(csgSequenceNumber).
				append(csgDocumentNumber).
				append(postalAuthCode).
				toString().hashCode();
	}

	/**
	 *
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	/**
	 *
	 * @return
	 */
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	

	/**
	 *
	 * @return
	 */
	@KeyCondition(column = "BLGBAS")
	public java.lang.String getBillingBasis() {
		return billingBasis;
	}
	/**
	 *
	 * @param billingBasis
	 */
	public void setBillingBasis(java.lang.String billingBasis) {
		this.billingBasis = billingBasis;
	}
	/**
	 * @return Returns the csgDocumentNumber.
	 */
	@KeyCondition(column = "CSGDOCNUM")
	public String getCsgDocumentNumber() {
		return csgDocumentNumber;
	}
	/**
	 * @param csgDocumentNumber The csgDocumentNumber to set.
	 */
	public void setCsgDocumentNumber(String csgDocumentNumber) {
		this.csgDocumentNumber = csgDocumentNumber;
	}
	/**
	 * @return Returns the csgSequenceNumber.
	 */
	@KeyCondition(column = "CSGSEQNUM")
	public int getCsgSequenceNumber() {
		return csgSequenceNumber;
	}
	/**
	 * @param csgSequenceNumber The csgSequenceNumber to set.
	 */
	public void setCsgSequenceNumber(int csgSequenceNumber) {
		this.csgSequenceNumber = csgSequenceNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(153);
		sbul.append("MRABillingMasterTempPK [ ");
		sbul.append("billingBasis '").append(this.billingBasis);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', csgDocumentNumber '").append(this.csgDocumentNumber);
		sbul.append("', csgSequenceNumber '").append(this.csgSequenceNumber);
		sbul.append("', postalAuthCode '").append(this.postalAuthCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
