/*
 * MRABillingDetailsPK.java Created on July 6, 2008
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;


import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;


/**
 * @author A-2554
 *
 */

@Embeddable
public class MRABillingDetailsPK  implements Serializable{
	
	private long mailSeqNum;
	private int serialNumber;
	private String companyCode;
	
	


	public MRABillingDetailsPK(){}
	

	public MRABillingDetailsPK(long mailSeqNum,int serialNumber,String companyCode) {
		
		this.mailSeqNum=mailSeqNum;
		this.serialNumber=serialNumber;
		this.companyCode=companyCode;
		
	}
	
	/**
	 * @param mailSeqNum
	 * @param companyCode
	 */
	public MRABillingDetailsPK(long mailSeqNum, String companyCode) {
		super();
		this.mailSeqNum = mailSeqNum;
		this.companyCode = companyCode;
	}


	/**
	 * @param object
	 * @return boolean
	 */
	public boolean equals(Object object) {
		if (object != null) {
			return (hashCode() == object.hashCode());
		}
		return false;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuilder()
				.append(mailSeqNum).append(serialNumber).append(companyCode).toString().hashCode();
	}



	/**
	 * @return Returns the companyCode.
	 */
	@KeyCondition(column = "CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}



	/**
	 * @return the mailSeqNum
	 */
	@KeyCondition(column = "MALSEQNUM")
	public long getMailSeqNum() {
		return mailSeqNum;
	}


	/**
	 * @param mailSeqNum the mailSeqNum to set
	 */
	public void setMailSeqNum(long mailSeqNum) {
		this.mailSeqNum = mailSeqNum;
	}

	/**
	 * @return the serialNumber
	 */
	@KeyCondition(column = "SERNUM")
	public int getSerialNumber() {
		return serialNumber;
	}


	/**
	 * @param serialNumber the serialNumber to set
	 */
	public void setSerialNumber(int serialNumber) {
		this.serialNumber = serialNumber;
	}


	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}


	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(161);
		sbul.append("MRABillingDetailsPK [ ");
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', mailSeqNum '").append(this.mailSeqNum);
		sbul.append("', serialNumber '").append(this.serialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
	
	

}
