/*
 * MRABillingDetailsTempPK.java Created on July 6, 2008
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;
import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
/**
 * @author A-3251
 *
 */
@Embeddable
public class MRABillingDetailsTempPK implements Serializable{
	
	private int sequenceNumber;
	private int csgSeqNum;
	private String csgDocumentNumber;
	private String billingBasis;
	private String companyCode;
	private String poaCode;
	
	/**
	 * @return Returns the poaCode.
	 */
	@KeyCondition(column = "POACOD")
	public String getPoaCode() {
		return poaCode;
	}


	/**
	 * @param poaCode The poaCode to set.
	 */
	public void setPoaCode(String poaCode) {
		this.poaCode = poaCode;
	}


	public MRABillingDetailsTempPK(){}
	

	public MRABillingDetailsTempPK(int seqNumber,int csgSeqNum,String csgDocumentNumber,String billingBasis,String companyCode,String poaCode) {
		
		
		this.sequenceNumber=seqNumber;
		this.csgSeqNum=csgSeqNum;
		this.csgDocumentNumber=csgDocumentNumber;
		this.billingBasis=billingBasis;
		this.companyCode=companyCode;
		this.poaCode=poaCode;
		
		
	}
	
	/**
	 * @param object
	 * @return boolean
	 */
	public boolean equals(Object object) {
		if (object != null) {
			return (hashCode() == object.hashCode());
		}
		return false;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuilder().append(sequenceNumber)
				.append(csgSeqNum).append(csgDocumentNumber).append(billingBasis).append(companyCode).append(poaCode).toString().hashCode();
	}


	/**
	 * @return Returns the billingBasis.
	 */
	@KeyCondition(column = "BLGBAS")
	public String getBillingBasis() {
		return billingBasis;
	}


	/**
	 * @return Returns the companyCode.
	 */
	@KeyCondition(column = "CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}


	/**
	 * @return Returns the csgDocumentNumber.
	 */
	@KeyCondition(column = "CSGDOCNUM")
	public String getCsgDocumentNumber() {
		return csgDocumentNumber;
	}


	/**
	 * @return Returns the csgSeqNum.
	 */
	@KeyCondition(column = "CSGSEQNUM")
	public int getCsgSeqNum() {
		return csgSeqNum;
	}
	

	/**
	 * @return Returns the sequenceNumber.
	 */
	@KeyCondition(column = "SERNUM")
	public int getSequenceNumber() {
		return sequenceNumber;
	}


	/**
	 * @param billingBasis The billingBasis to set.
	 */
	public void setBillingBasis(String billingBasis) {
		this.billingBasis = billingBasis;
	}


	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}


	/**
	 * @param csgDocumentNumber The csgDocumentNumber to set.
	 */
	public void setCsgDocumentNumber(String csgDocumentNumber) {
		this.csgDocumentNumber = csgDocumentNumber;
	}


	/**
	 * @param csgSeqNum The csgSeqNum to set.
	 */
	public void setCsgSeqNum(int csgSeqNum) {
		this.csgSeqNum = csgSeqNum;
	}


	/**
	 * @param sequenceNumber The sequenceNumber to set.
	 */
	public void setSequenceNumber(int sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}


	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(165);
		sbul.append("MRABillingDetailsTempPK [ ");
		sbul.append("billingBasis '").append(this.billingBasis);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', csgDocumentNumber '").append(this.csgDocumentNumber);
		sbul.append("', csgSeqNum '").append(this.csgSeqNum);
		sbul.append("', poaCode '").append(this.poaCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
	
	

}
