/*
 * MRAFuelChargeMasterPK.java Created on apr 23,2009
 *
 * Copyright 2009 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-2391
 *
 */


 @KeyTable(table = "MTKMRAFULCHGMSTKEY", keyColumn = "KEYTYP", valueColumn = "SEQNUM")
 @TableKeyGenerator(name = "ID_GEN", table = "MTKMRAFULCHGMSTKEY", key = "FUELCHG_SERNUM")
@Embeddable
public class MRAFuelChargeMasterPK implements Serializable {


	private String companyCode;


	
    private String gpaCode;


    private int seqNum;

    
	/**
	 * 
	 * @return
	 */
	@Key(generator = "ID_GEN", startAt = "1")
	public int getSeqNum() {
		return seqNum;
	}

	/**
	 * @param seqNum The seqNum to set.
	 */
	public void setSeqNum(int seqNum) {
		this.seqNum = seqNum;
	}

	/**
	 * @return Returns the gpaCode.
	 */
	@KeyCondition(column = "POACOD")
	public String getGpaCode() {
		return gpaCode;
	}

	/**
	 * @param gpaCode The gpaCode to set.
	 */
	public void setGpaCode(String gpaCode) {
		this.gpaCode = gpaCode;
	}

	/**
     *
     */
    public MRAFuelChargeMasterPK() {
    }

    public MRAFuelChargeMasterPK(String companyCode, String gpaCode,
            int seqNum) {
        this.companyCode = companyCode;
        this.gpaCode = gpaCode;
        this.seqNum = seqNum;
    }
    /**
     * @param other
     * @return boolean
     */
	public boolean equals(Object other) {
		boolean  isEqual = false;
		if(other != null){			
			isEqual = (hashCode() == other.hashCode());
		}
		return isEqual;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(gpaCode).
				append(seqNum).
				toString().hashCode();
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(81);
		sbul.append("MRAFuelChargeMasterPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', gpaCode '").append(this.gpaCode);
		sbul.append("', seqNum '").append(this.seqNum);
		sbul.append("' ]");
		return sbul.toString();
	}

	
	
}
