/*
 * MRAProrationDetailsPK.java Created on Mar 07, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author a-2518
 * 
 */
@TableKeyGenerator(name = "ID_GEN", table = "MTKPRODTLKEY", key = "SERNUM")
@KeyTable(table = "MTKPRODTLKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@Embeddable
public class MRAProrationDetailsPK implements Serializable {
	/**
	 * company code
	 */

	private String companyCode;

	/**
	 * serial number
	 */

	private int serialNumber;

	/**
	 * billing basis type
	 */

	private String billingBasisNumber;

	/**
	 * default constructor
	 * 
	 */
	public MRAProrationDetailsPK() {
	}

	/**
	 * 
	 * @param companyCode
	 * @param serialNumber
	 * @param billingBasisNumber
	 */
	public MRAProrationDetailsPK(String companyCode, int serialNumber,
			String billingBasisNumber) {
		this.companyCode = companyCode;
		this.serialNumber = serialNumber;
		this.billingBasisNumber = billingBasisNumber;
	}

	/**
	 * @param object
	 * @return boolean
	 */
	public boolean equals(Object object) {
		if (object != null) {
			return (hashCode() == object.hashCode());
		}
		return false;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(serialNumber)
				.append(billingBasisNumber).toString().hashCode();
	}

	/**
	 * 
	 * @param billingBasisNumber
	 */
	public void setBillingBasisNumber(java.lang.String billingBasisNumber) {
		this.billingBasisNumber=billingBasisNumber;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "BLGBASNUM")
	public java.lang.String getBillingBasisNumber() {
		return this.billingBasisNumber;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * 
	 * @param serialNumber
	 */
	public void setSerialNumber(int serialNumber) {
		this.serialNumber=serialNumber;
	}
	/**
	 * 
	 * @return
	 */
	@Key(generator = "ID_GEN", startAt = "1")
	public int getSerialNumber() {
		return this.serialNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(98);
		sbul.append("MRAProrationDetailsPK [ ");
		sbul.append("billingBasisNumber '").append(this.billingBasisNumber);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', serialNumber '").append(this.serialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
