/*
 * MRAProrationFactorPK.java Created on Mar 21, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */

package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author a-2518
 */
@TableKeyGenerator(name = "ID_GEN", table = "MTKPROFCTKEY", key = "SEQNUM")
@KeyTable(table = "MTKPROFCTKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@Embeddable
public class MRAProrationFactorPK implements Serializable {
	/**
	 * Company code
	 */

	private String companyCode;

	/**
	 * From city code
	 */

	private String fromCity;

	/**
	 * To city code
	 */

	private String toCity;

	/**
	 * Sequence Number
	 */

	private int sequenceNumber;

	public MRAProrationFactorPK() {

	}

	public MRAProrationFactorPK(String companyCode, String fromCity,
			String toCity, int sequenceNumber) {
		this.companyCode = companyCode;
		this.fromCity = fromCity;
		this.toCity = toCity;
		this.sequenceNumber = sequenceNumber;
	}

	/**
	 * @param obj
	 * @return boolean
	 */
	@Override
	public boolean equals(Object obj) {
		if (obj != null) {
			return this.hashCode() == obj.hashCode();
		}
		return false;
	}

	/**
	 * @return int
	 */
	@Override
	public int hashCode() {
		return new StringBuffer().append(companyCode).append(fromCity).append(
				toCity).append(sequenceNumber).hashCode();
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * 
	 * @param sequenceNumber
	 */
	public void setSequenceNumber(int sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	/**
	 * 
	 * @return
	 */
	@Key(generator = "ID_GEN", startAt = "1")
	public int getSequenceNumber() {
		return this.sequenceNumber;
	}

	/**
	 * 
	 * @param fromCity
	 */
	public void setFromCity(java.lang.String fromCity) {
		this.fromCity=fromCity;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "FRMCTY")
	public java.lang.String getFromCity() {
		return this.fromCity;
	}

	/**
	 * 
	 * @param toCity
	 */
	public void setToCity(java.lang.String toCity) {
		this.toCity=toCity;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "TOOCTY")
	public java.lang.String getToCity() {
		return this.toCity;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(107);
		sbul.append("MRAProrationFactorPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', fromCity '").append(this.fromCity);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("', toCity '").append(this.toCity);
		sbul.append("' ]");
		return sbul.toString();
	}
}
