/*
 * MRAProrationExceptionsPK.java Created on Sep 03,2008
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.icargo.business.mail.mra.defaults.vo.ProrationExceptionVO;

/**
 * @author a-3108
 *
 */

@Embeddable
public class MRAProrationExceptionsPK implements Serializable{
	
	
	private String companyCode;
	private long mailSequenceNumber;
	private int exceptionSequenceNumber;	
	
   
	public MRAProrationExceptionsPK() {
    }
    /**
     *
     * @param companyCode
     * @param slaId
     */
    public MRAProrationExceptionsPK(ProrationExceptionVO prorationExceptionVO) {
    	
    	this.companyCode = prorationExceptionVO.getCompanyCode();
    	//this.billingBasis = prorationExceptionVO.getMailbagId();    
    	//this.csgDocumentNumber=prorationExceptionVO.getConsDocNo();  
    	//this.mailSequenceNumber=prorationExceptionVO.getConsSeqNo();
        //this.postalAuthCode=prorationExceptionVO.getPoaCode();
    	this.mailSequenceNumber=prorationExceptionVO.getMailSequenceNumber();//added by a-7531 for icrd-253055
        this.exceptionSequenceNumber=prorationExceptionVO.getExceptionSerialNumber();
        
    }

    

	

	/**
	 *
	 * @return
	 */
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	/**
	 *
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	
	/**
	 * @return the mailSequenceNumber
	 */
	@KeyCondition(column = "MALSEQNUM")
	public long getMailSequenceNumber() {
		return mailSequenceNumber;
	}
	/**
	 * @param mailSequenceNumber the mailSequenceNumber to set
	 */
	public void setMailSequenceNumber(long mailSequenceNumber) {
		this.mailSequenceNumber = mailSequenceNumber;
	}
	@KeyCondition(column = "EXPSEQNUM")
	 /**
	 * @return Returns the exceptionSequenceNumber.
	 */
	public int getExceptionSequenceNumber() {
		return exceptionSequenceNumber;
	}
	/**
	 * @param exceptionSequenceNumber 
	 */
	public void setExceptionSequenceNumber(int exceptionSequenceNumber) {
		this.exceptionSequenceNumber = exceptionSequenceNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(190);
		sbul.append("MRAProrationExceptionsPK [ ");
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', mailSequenceNumber '").append(this.mailSequenceNumber);
		sbul.append("', exceptionSequenceNumber '").append(
				this.exceptionSequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
	
	/**
	 * @param other
	 * @param boolean
	 */
	 public boolean equals(Object other) {
	        return (other != null)&& (other instanceof MRAProrationExceptionsPK) && (hashCode() == other.hashCode());
	    }
	 /**
	  * @return int
	  */
	 public int hashCode() {

	        return new StringBuffer(companyCode).append(exceptionSequenceNumber).append(mailSequenceNumber).toString().hashCode();
	    }
	
	
}
