/*
 * MRARateLinePK.java Created on Jan 18, 2007
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1556
 *
 */
 @KeyTable(table = "MALMRARATLINKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
 @TableKeyGenerator(name = "ID_GEN", table = "MALMRARATLINKEY", key = "RATLIN_SERNUM")
@Embeddable
public class MRARateLinePK implements Serializable {


	private String companyCode;


    private String rateCardID;


    private int ratelineSequenceNumber;
    

    /**
     *
     */
    public MRARateLinePK() {
    }

    
    /**
	 * @param companyCode
	 * @param rateCardID
	 * @param ratelineSequenceNumber
	 */
	public MRARateLinePK(String companyCode, String rateCardID,
			int ratelineSequenceNumber) {
		super();
		this.companyCode = companyCode;
		this.rateCardID = rateCardID;
		this.ratelineSequenceNumber = ratelineSequenceNumber;
	}

	/**
     * @param other
     * @return boolean
     */
	public boolean equals(Object other) {
		boolean  isEqual = false;
		if(other != null){			
			isEqual = (hashCode() == other.hashCode());
		}
		return isEqual;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(rateCardID).
				toString().hashCode();
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * 
	 * @param ratelineSequenceNumber
	 */
	public void setRatelineSequenceNumber(int ratelineSequenceNumber) {
		this.ratelineSequenceNumber=ratelineSequenceNumber;
	}
	/**
	 * 
	 * @return
	 */
	@Key(generator = "ID_GEN", startAt = "1")
	public int getRatelineSequenceNumber() {
		return this.ratelineSequenceNumber;
	}

	/**
	 * 
	 * @param rateCardID
	 */
	public void setRateCardID(java.lang.String rateCardID) {
		this.rateCardID=rateCardID;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column = "RATCRDCOD")
	public java.lang.String getRateCardID() {
		return this.rateCardID;
	}

	/**


	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(92);
		sbul.append("MRARateLinePK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', rateCardID '").append(this.rateCardID);
		sbul.append("', ratelineSequenceNumber '").append(
				this.ratelineSequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
