releaseBranches:
  aa-stag:
    tenantId: aa
    releaseTenantId: base
    applicationId: icargo-api
    bomPath: "etc/icargo-api-bom.yml"
    releaseStrategy: build-reduced
  cv-stag:
    tenantId: cv
    releaseTenantId: base
    applicationId: icargo-api
    bomPath: "etc/icargo-api-bom.yml"
    releaseStrategy: build-reduced
  afkl-stag:
    tenantId: afkl
    releaseTenantId: base
    applicationId: icargo-api
    bomPath: "etc/icargo-api-bom.yml"
    releaseStrategy: build-reduced
  as-stag:
    tenantId: as
    releaseTenantId: base
    applicationId: icargo-api
    bomPath: "etc/icargo-api-bom.yml"
    releaseStrategy: build-reduced
  dhl-qa:
    tenantId: dhl
    releaseTenantId: dhl
    applicationId: icargo-neo
    bomPath: "etc/icargo-neo-bom.yml"
    releaseStrategy: build
