databaseChangeLog:
  - logicalFilePath : classpath:/config/changelog/IAN-46178_MSM28514.yml
  - changeSet:
      id: 28514
      author: A-201345
      preConditions:
        - onFail: MARK_RAN
        - tableExists:
            tableName: ccaawb
        - not:
            columnExists:
              tableName: ccaawb
              columnName: expduearl
      changes:
        dbms: h2, oracle
        endDelimiter: \nGO
        splitStatements: false
        sql:
          ALTER TABLE ccaawb ADD COLUMN expduearl numeric(16,4);

          COMMENT ON COLUMN ccaawb.expduearl is 'Net Value Export';