databaseChangeLog:
  - logicalFilePath : classpath:/config/changelog/IAN-4610_MSM28218.yml
  - changeSet:
       id: 28218
       author: A-1945
       preConditions:
         - onFail: MARK_RAN
         - not:
            sequenceExists:
              sequenceName: ccaawbtaxdtl_seq
       changes:
         dbms: h2, oracle
         endDelimiter: \nGO
         splitStatements: false
         sql: CREATE SEQUENCE ccaawbtaxdtl_seq START WITH 1 INCREMENT BY 1  MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;