databaseChangeLog:
  - logicalFilePath: classpath:/config/changelog/IAN-15521_MSM28632.yml
  - changeSet:
      id: 28502
      author: A-10597
      preConditions:
        - tableExists:
            tableName: ccamst
        - not:
            columnExists:
              tableName: ccamst
              columnName: exedat
        - not:
            columnExists:
              tableName: ccamst
              columnName: fstfltdat

      changes:
        dbms: h2, oracle
        endDelimiter: \nGO
        splitStatements: false
        sql:
          ALTER TABLE ccamst ADD COLUMN exedat date;
          ALTER TABLE ccamst ADD COLUMN fstfltdat date;

          COMMENT ON COLUMN ccamst.exedat IS 'Execution date';
          COMMENT ON COLUMN ccamst.fstfltdat IS 'First flight date';