databaseChangeLog:
  - logicalFilePath : classpath:/config/changelog/IAN-35824_MSM27284.yml
  - changeSet:
       id: 27284
       author: A-10597
       preConditions:
         - onFail: MARK_RAN
         - not:
            indexExists:
              indexName: CCAMST_IND2
       changes:
         dbms: h2, oracle
         endDelimiter: \nGO
         splitStatements: false
         sql: CREATE INDEX CCAMST_IND2 ON CCAMST(SHPPFX,MSTDOCNUM);