databaseChangeLog:
  - logicalFilePath : classpath:/config/changelog/IAN-15043_MSM28716.yml
  - changeSet:
      id: 28716
      author: A-201345
      preConditions:
        - onFail: MARK_RAN
        - not:
            sequenceExists:
              sequenceName: ccawrkflwdtl_seq
      changes:
        dbms: h2, oracle
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE SEQUENCE ccawrkflwdtl_seq START WITH 1 INCREMENT BY 1  MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;