databaseChangeLog:
  - logicalFilePath: classpath:/config/changelog/IAN-4605_MSM28502.yml
  - changeSet:
      id: 28502
      author: A-10597
      preConditions:
        - tableExists:
            tableName: ccaawb
        - not:
            columnExists:
              tableName: ccaawb
              columnName: sptratidr
      changes:
        dbms: h2, oracle
        endDelimiter: \nGO
        splitStatements: false
        sql:
          ALTER TABLE ccaawb ADD COLUMN sptratidr varchar(30);
          COMMENT ON COLUMN ccaawb.sptratidr IS 'Spot Rate Id';