
package com.ibsplc.icargo.business.reco.defaults;

import java.io.Serializable;
import javax.persistence.Embeddable;


/**
 * The Class EmbargoGeographicLevelPK.
 */
@Embeddable
public class EmbargoGeographicLevelPK implements Serializable {
	
	/** The company code. */
	private String companyCode;

	/** The embargo reference number. */
	private String embargoReferenceNumber;
	
	/** The embargo version. */
	private int embargoVersion;
	
	/** The geographic level. */
	private String geographicLevel;
	
	/** The geographic level type. */
	private String geographicLevelType;

	/**
	 * Gets the company code.
	 *
	 * @return the company code
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * Sets the company code.
	 *
	 * @param companyCode the new company code
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * Gets the embargo reference number.
	 *
	 * @return the embargo reference number
	 */
	public String getEmbargoReferenceNumber() {
		return embargoReferenceNumber;
	}

	/**
	 * Sets the embargo reference number.
	 *
	 * @param embargoReferenceNumber the new embargo reference number
	 */
	public void setEmbargoReferenceNumber(String embargoReferenceNumber) {
		this.embargoReferenceNumber = embargoReferenceNumber;
	}

	
	
	public int getEmbargoVersion() {
		return embargoVersion;
	}

	public void setEmbargoVersion(int embargoVersion) {
		this.embargoVersion = embargoVersion;
	}
	
	public String getGeographicLevel() {
		return geographicLevel;
	}

	public void setGeographicLevel(String geographicLevel) {
		this.geographicLevel = geographicLevel;
	}
	
	public String getGeographicLevelType() {
		return geographicLevelType;
	}

	public void setGeographicLevelType(String geographicLevelType) {
		this.geographicLevelType = geographicLevelType;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).append(embargoReferenceNumber).append(embargoVersion).append(geographicLevel).append(geographicLevelType)
				.toString().hashCode();
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:12 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(165);
		sbul.append("EmbargoGeographicLevelPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', embargoReferenceNumber '").append(
				this.embargoReferenceNumber);
		sbul.append("', embargoVersion '").append(this.embargoVersion);
		sbul.append("', geographicLevel '").append(this.geographicLevel);
		sbul.append("', geographicLevelType '")
				.append(this.geographicLevelType);
		sbul.append("' ]");
		return sbul.toString();
	}
}
