/*
 * EmbargoParameterPK.java Created on Jul 13, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary 
 * information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.reco.defaults;

import java.io.Serializable;


import javax.persistence.Embeddable;

/**
 * Primary key class of EmbargoParameter
 * 
 * @author A-1358
 * 
 */
@Embeddable
public class EmbargoRulesParameterPK implements Serializable {

	/**
	 * Comapany Code
	 */
	private String companyCode;

	/**
	 * Reference number
	 */
	private String embargoReferenceNumber;

	/**
	 *Parameter Code  
	 */
	private String parameterCode;
	
	private int embargoVersion;

	private String parameterType;

	private String applicableOn;
	

	public String getApplicableOn() {
		return applicableOn;
	}

	public void setApplicableOn(String applicableOn) {
		this.applicableOn = applicableOn;
	}

	public String getParameterType() {
		return parameterType;
	}

	public void setParameterType(String parameterType) {
		this.parameterType = parameterType;
	}

	public int getEmbargoVersion() {
		return embargoVersion;
	}

	public void setEmbargoVersion(int embargoVersion) {
		this.embargoVersion = embargoVersion;
	}

	/**
     * Checks whether to objects are equal 
     *@param other
     *@return boolean 
     *
     */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	 /**
     * Returns HashCode 
     * @return int
     */
	public int hashCode() {
		return new StringBuffer(companyCode).append(embargoReferenceNumber).append(embargoVersion)
				.append(parameterCode).append(parameterType).append(applicableOn).toString().hashCode();
	}


	public void setParameterCode(java.lang.String parameterCode) {
		this.parameterCode=parameterCode;
	}

	public java.lang.String getParameterCode() {
		return this.parameterCode;
	}

	public void setEmbargoReferenceNumber(java.lang.String embargoReferenceNumber) {
		this.embargoReferenceNumber=embargoReferenceNumber;
	}

	public java.lang.String getEmbargoReferenceNumber() {
		return this.embargoReferenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:12 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(180);
		sbul.append("EmbargoRulesParameterPK [ ");
		sbul.append("applicableOn '").append(this.applicableOn);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', embargoReferenceNumber '").append(
				this.embargoReferenceNumber);
		sbul.append("', embargoVersion '").append(this.embargoVersion);
		sbul.append("', parameterCode '").append(this.parameterCode);
		sbul.append("', parameterType '").append(this.parameterType);
		sbul.append("' ]");
		return sbul.toString();
	}
}
