/*
 * EmbargoAuditPK.java Created on Sep 6, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary
 * information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.reco.defaults;

import java.io.Serializable;


import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1358
 * Primary Key class for embargo audit
 *
 */

@Embeddable
@KeyTable(table="RECAUDKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="AUDSEQ_GEN",table="RECAUDKEY",key="RECAUD_SEQ")
public class EmbargoRulesAuditPK implements Serializable{


	/**
	 * Comapany Code
	 */

	private String companyCode;


	/**
	 * Reference Number
	 */

	private String embargoReferenceNumber;

    /**
     * Audit sequence Number
     */

    private long sequenceNumber;


	public EmbargoRulesAuditPK(){

	}
	/**
     * This constructor is called to populate instances of PK.
     * @param companyCode
     * @param embargoReferenceNumber
     */
	public EmbargoRulesAuditPK(String companyCode,String embargoReferenceNumber,long sequenceNumber){
		this.companyCode=companyCode;
		this.embargoReferenceNumber=embargoReferenceNumber;
		this.sequenceNumber = sequenceNumber;
	}

    /**
     * Checks whether to objects are equal
     *@param other
     *@return boolean
     *
     */
      public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}


    /**
     * Returns HashCode
     * @return int
     */
    public int hashCode() {
		return new StringBuffer(companyCode).
			append(embargoReferenceNumber).
			toString().hashCode();
	}
    public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setEmbargoReferenceNumber(java.lang.String embargoReferenceNumber) {
		this.embargoReferenceNumber=embargoReferenceNumber;
	}
	@KeyCondition(column = "REFNUM")
	public java.lang.String getEmbargoReferenceNumber() {
		return this.embargoReferenceNumber;
	}

	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	@Key(generator="AUDSEQ_GEN", startAt="1")
	public long getSequenceNumber() {
		return this.sequenceNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:12 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(102);
		sbul.append("EmbargoRulesAuditPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', embargoReferenceNumber '").append(
				this.embargoReferenceNumber);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
