/*
 * UserParameterPK.java Created on Sep 05, 2013
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.neoicargo.business.admin.user;

import javax.persistence.Embeddable;
import java.io.Serializable;


/**
 * This class represents the primary key elements of the User entity.
 *
 * @author A-1417
 */
@Embeddable
public class UserParameterPK implements Serializable {

    /**
     * The company code corresponding to the user
     */
    private String companyCode;

    /**
     * The user identifier
     */
    private String userCode;

    private String parameterCode;


    /**
     * to check equals
     *
     * @param other
     * @return boolean
     */
    public boolean equals(Object other) {
        return (other != null) && ((hashCode() == other.hashCode()));
    }

    /**
     * to create HashCode
     *
     * @return int
     */
    public int hashCode() {
        return new StringBuffer(companyCode).append(userCode).append(parameterCode).toString()
                .hashCode();
    }

    /**
     * @return the companyCode
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * @param companyCode the companyCode to set
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * @return the userCode
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * @param userCode the userCode to set
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * @return the parameterCode
     */
    public String getParameterCode() {
        return parameterCode;
    }

    /**
     * @param parameterCode the parameterCode to set
     */
    public void setParameterCode(String parameterCode) {
        this.parameterCode = parameterCode;
    }

    /**
     * generated by xibase.tostring plugin at 1 October, 2014 1:13:36 PM IST
     */
    @Override
    public String toString() {
        StringBuilder sbul = new StringBuilder(83);
        sbul.append("UserParameterPK [ ");
        sbul.append("companyCode '").append(this.companyCode);
        sbul.append("', parameterCode '").append(this.parameterCode);
        sbul.append("', userCode '").append(this.userCode);
        sbul.append("' ]");
        return sbul.toString();
    }
}
