/*
 * ProductRestrictionStationPK.java Created on Jun 27, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.products.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-1358
 *
 */
@Embeddable
public class ProductRestrictionStationPK implements Serializable{
	/**
	 * Company Code
	 */
    private String companyCode;
    /**
     * Product Code
     */
    private String productCode;
    /**
     * Station Code
     */
    private String stationCode;
    
    /**
     * Indicates whether the restriction is against Origin or Destination
     */
    private String isOrigin;
	
    /**
	 * @return Returns the companyCode.
	 */
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the isOrigin.
	 */
	public String getIsOrigin() {
		return isOrigin;
	}
	/**
	 * @param isOrigin The isOrigin to set.
	 */
	public void setIsOrigin(String isOrigin) {
		this.isOrigin = isOrigin;
	}
	/**
	 * @return Returns the productCode.
	 */
	public String getProductCode() {
		return productCode;
	}
	/**
	 * @param productCode The productCode to set.
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	/**
	 * @return Returns the stationCode.
	 */
	public String getStationCode() {
		return stationCode;
	}
	/**
	 * @param stationCode The stationCode to set.
	 */
	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}
	/**
	 * Returns the hash code corresponding to a product
	 * @return int
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode)
			.append(productCode).append(stationCode).append(isOrigin).toString().hashCode();
	}
	/**
	 * Compare two products
	 * @param other
	 * @return boolean
	 */
    public boolean equals(Object other) {
	 return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:11 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(116);
		sbul.append("ProductRestrictionStationPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', isOrigin '").append(this.isOrigin);
		sbul.append("', productCode '").append(this.productCode);
		sbul.append("', stationCode '").append(this.stationCode);
		sbul.append("' ]");
		return sbul.toString();
	}

}
