/*
 * ProductFeedbackPK.java Created on Jun 27, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.products.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1883
 *
 */
@KeyTable(table="PRDFEDBCKKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="ID_GEN",table="PRDFEDBCKKEY",key="FEDBCKIDR_SEQ")
@Embeddable
public class ProductFeedbackPK implements Serializable{
	/**
	 * Company Code  
	 */
	private String companyCode ; 
	 /**
	  * Product Code
	  */
	private String productCode ;
	/**
	 * Feed back ID
	 */
	private long feedbackId;
	/**
	 * @return int
	 */
	public int hashCode() {
			return new StringBuilder().append(companyCode)
				.append(productCode).append(feedbackId).toString().hashCode();
	}
	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
			return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * @return Returns the companyCode.
	 */
	@KeyCondition(column="CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the feedbackId.
	 */
	@Key(generator="ID_GEN",startAt= "1")
	public long getFeedbackId() {
		return feedbackId;
	}
	/**
	 * @param feedbackId The feedbackId to set.
	 */
	public void setFeedbackId(long feedbackId) {
		this.feedbackId = feedbackId;
	}
	/**
	 * @return Returns the productCode.
	 */
	@KeyCondition(column="PRDCOD")
	public String getProductCode() {
		return productCode;
	}
	/**
	 * @param productCode The productCode to set.
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:11 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(85);
		sbul.append("ProductFeedbackPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', feedbackId '").append(this.feedbackId);
		sbul.append("', productCode '").append(this.productCode);
		sbul.append("' ]");
		return sbul.toString();
	}
	
	
}
