/*
 * ProductsDefaultsAuditPK.java Created on Aug 23, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.products.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;


/**
 * @author A-1366
 *
 */
 
@KeyTable(table="PRDDEFAUDKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="AUDSEQ_GEN",table="PRDDEFAUDKEY",key="PRDDEFAUD_SEQ")
@Embeddable
public class ProductsDefaultsAuditPK implements Serializable {
    /**
     * Company Code
     */ 
    private String companyCode;
    /**
     * Product Code
     */
    private String productCode;
    
    /**
     * Audit Sequence number  
     *
     */
    private long sequenceNumber;
    
    public ProductsDefaultsAuditPK(){
    	
    }
    /**
     * Constructor used to populate PK
     * @param companyCode
     * @param productCode
     * @param sequenceNumber
     */
    public ProductsDefaultsAuditPK(String companyCode, String productCode,
            long sequenceNumber){
        this.companyCode=companyCode;
        this.productCode=productCode;
        this.sequenceNumber=sequenceNumber;
    }
    
    /**
	 * @return Returns the companyCode.
	 */
    @KeyCondition(column="CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the productCode.
	 */
	@KeyCondition(column="PRDCOD")
	public String getProductCode() {
		return productCode;
	}
	/**
	 * @param productCode The productCode to set.
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	/**
	 * @return Returns the sequenceNumber.
	 */
	@Key(generator="AUDSEQ_GEN",startAt="1")
	public long getSequenceNumber() {
		return sequenceNumber;
	}
	/**
	 * @param sequenceNumber The sequenceNumber to set.
	 */
	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}
	/**
     * This method tests for equality of one instance of this class with
     * the other.
     * @param other - another object to test for equality
     * @return boolean - returns true if equal
     */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	
	/**
	 * This method generates the hashcode of an instance
	 * @return int - returns the hashcode of the instance
	 */
	public int hashCode() {
		return new StringBuilder(companyCode).append(productCode).append(sequenceNumber).toString().hashCode();
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:11 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(95);
		sbul.append("ProductsDefaultsAuditPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', productCode '").append(this.productCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
