/*
 * ProductRestrictionCustomerGroupPK.java Created on Jun 27, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.products.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-1358
 *
 */
@Embeddable
public class ProductRestrictionCustomerGroupPK implements Serializable{
	/**
	 * Company Code
	 */
    private String companyCode;
    /**
     * Product Code
     */
    private String productCode;
    /**
     * Customer Group
     */
    private String customerGroup;
	/**
	 * return the hash code corresponding to a product
	 * @return int
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode)
			.append(productCode).append(customerGroup).toString().hashCode();
	}
	/**
	 * @return Returns the companyCode.
	 */
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the customerGroup.
	 */
	public String getCustomerGroup() {
		return customerGroup;
	}
	/**
	 * @param customerGroup The customerGroup to set.
	 */
	public void setCustomerGroup(String customerGroup) {
		this.customerGroup = customerGroup;
	}
	/**
	 * @return Returns the productCode.
	 */
	public String getProductCode() {
		return productCode;
	}
	/**
	 * @param productCode The productCode to set.
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	/**
	 * Compare two product 
	 * @param other
	 * @return boolean
	 */
    public boolean equals(Object other) {
	 return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:11 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(104);
		sbul.append("ProductRestrictionCustomerGroupPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', customerGroup '").append(this.customerGroup);
		sbul.append("', productCode '").append(this.productCode);
		sbul.append("' ]");
		return sbul.toString();
	}

}
