/*
 * ProductEventPK.java Created on Jun 29, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.products.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-1358
 *
 */
@Embeddable
public class ProductEventPK implements Serializable{

    /**
     * Company code
     */
	private String companyCode;
	/**
	 * Product Code
	 */
    private String productCode;

  /**
   * Event code can be a service code or a milestone code
   */
    private String eventCode;

    /**
     * Indicates whether the event is a service or a milestone
     * Possible values are - S, M
     */
    private String eventType;
   /**
	 * @return Returns the companyCode.
	 */
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the eventCode.
	 */
	public String getEventCode() {
		return eventCode;
	}
	/**
	 * @param eventCode The eventCode to set.
	 */
	public void setEventCode(String eventCode) {
		this.eventCode = eventCode;
	}
	/**
	 * @return Returns the eventType.
	 */
	public String getEventType() {
		return eventType;
	}
	/**
	 * @param eventType The eventType to set.
	 */
	public void setEventType(String eventType) {
		this.eventType = eventType;
	}
	/**
	 * @return Returns the productCode.
	 */
	public String getProductCode() {
		return productCode;
	}
	/**
	 * @param productCode The productCode to set.
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	/**
    * return the hashcode
    * @return int
    */
	public int hashCode() {
			return new StringBuilder().append(companyCode)
				.append(productCode).append(eventCode).append(eventType).toString().hashCode();
	}
	/**
	 * Compare two hashcodes and return a boolean value
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
			return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:11 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(102);
		sbul.append("ProductEventPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', eventCode '").append(this.eventCode);
		sbul.append("', eventType '").append(this.eventType);
		sbul.append("', productCode '").append(this.productCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
