/*
 * SubProductEventPK.java Created on Jun 29, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.products.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-1358
 *
 */
@Embeddable
public class SubProductEventPK implements Serializable{
	 /**
	  * Company Code 
	 */
     private String companyCode;
     /**
      * Product Code
      */
     private String productCode;
     /**
      * SubProduct Code
      */
     private String subProductCode;
     /**
      * Version Number of subProduct
      */
     private int versionNumber;

    /**
     * Event code can be a service code or a milestone code
     */
    private String eventCode;

    /**
     * Indicates whether the event is a service or a milestone
     * Possible values are - S, M
     */
    private String eventType;
    /**
	 * Return the hash code corresponding to a subproduct
	 * @return int
	 */
	 public int hashCode() {
			return new StringBuilder().append(companyCode)
				.append(productCode).append(subProductCode).append(eventCode).append(eventType)
				.append(versionNumber).toString().hashCode();
	 }
	 /**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
			return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * @return Returns the companyCode.
	 */
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the eventCode.
	 */
	public String getEventCode() {
		return eventCode;
	}
	/**
	 * @param eventCode The eventCode to set.
	 */
	public void setEventCode(String eventCode) {
		this.eventCode = eventCode;
	}
	/**
	 * @return Returns the eventType.
	 */
	public String getEventType() {
		return eventType;
	}
	/**
	 * @param eventType The eventType to set.
	 */
	public void setEventType(String eventType) {
		this.eventType = eventType;
	}
	/**
	 * @return Returns the productCode.
	 */
	public String getProductCode() {
		return productCode;
	}
	/**
	 * @param productCode The productCode to set.
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	/**
	 * @return Returns the subProductCode.
	 */
	public String getSubProductCode() {
		return subProductCode;
	}
	/**
	 * @param subProductCode The subProductCode to set.
	 */
	public void setSubProductCode(String subProductCode) {
		this.subProductCode = subProductCode;
	}
	/**
	 * @return Returns the versionNumber.
	 */
	public int getVersionNumber() {
		return versionNumber;
	}
	/**
	 * @param versionNumber The versionNumber to set.
	 */
	public void setVersionNumber(int versionNumber) {
		this.versionNumber = versionNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:11 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(156);
		sbul.append("SubProductEventPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', eventCode '").append(this.eventCode);
		sbul.append("', eventType '").append(this.eventType);
		sbul.append("', productCode '").append(this.productCode);
		sbul.append("', subProductCode '").append(this.subProductCode);
		sbul.append("', versionNumber '").append(this.versionNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
	
	
}
