/*
 * SubProductRestrictionStationPK.java Created on Jun 27, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.products.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-1358
 *
 */
@Embeddable
public class SubProductRestrictionStationPK implements Serializable{

    /**
     * Company Code
     */
	private String companyCode;
	/**
	 * Product Code
	 */
    private String productCode;
    /**
     * SubProduct Code
     */
    private String subProductCode;
    /**
     * Version Number
     */
    private int versionNumber;
    /**
     * Station code
     */
    private String stationCode;    

    /**
     * Indicates whether the restriction is against Origin or Destination
     */
    private String isOrigin;
    /**
     * Default Constructor SubProductRestrictionStationPK
     *
     */
    public SubProductRestrictionStationPK(){
    	
    }
    /**
     * 
     * @param companyCode
     * @param productCode
     * @param subProductCode
     * @param versionNumber
     * @param stationCode
     * @param isOrigin
     */
    public SubProductRestrictionStationPK(String companyCode,String productCode,
    		String subProductCode,int versionNumber,String stationCode,String isOrigin){
    	this.companyCode = companyCode;
    	this.productCode = productCode;
    	this.subProductCode = subProductCode;
    	this.versionNumber = versionNumber;
    	this.stationCode = stationCode;
    	this.isOrigin = isOrigin;
    }
	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode)
			.append(productCode).append(subProductCode).append(versionNumber).append(stationCode).append(isOrigin).toString().hashCode();
	}
	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * @return Returns the companyCode.
	 */
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the isOrigin.
	 */
	public String getIsOrigin() {
		return isOrigin;
	}
	/**
	 * @param isOrigin The isOrigin to set.
	 */
	public void setIsOrigin(String isOrigin) {
		this.isOrigin = isOrigin;
	}
	/**
	 * @return Returns the productCode.
	 */
	public String getProductCode() {
		return productCode;
	}
	/**
	 * @param productCode The productCode to set.
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	/**
	 * @return Returns the stationCode.
	 */
	public String getStationCode() {
		return stationCode;
	}
	/**
	 * @param stationCode The stationCode to set.
	 */
	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}
	/**
	 * @return Returns the subProductCode.
	 */
	public String getSubProductCode() {
		return subProductCode;
	}
	/**
	 * @param subProductCode The subProductCode to set.
	 */
	public void setSubProductCode(String subProductCode) {
		this.subProductCode = subProductCode;
	}
	/**
	 * @return Returns the versionNumber.
	 */
	public int getVersionNumber() {
		return versionNumber;
	}
	/**
	 * @param versionNumber The versionNumber to set.
	 */
	public void setVersionNumber(int versionNumber) {
		this.versionNumber = versionNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:11 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(170);
		sbul.append("SubProductRestrictionStationPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', isOrigin '").append(this.isOrigin);
		sbul.append("', productCode '").append(this.productCode);
		sbul.append("', stationCode '").append(this.stationCode);
		sbul.append("', subProductCode '").append(this.subProductCode);
		sbul.append("', versionNumber '").append(this.versionNumber);
		sbul.append("' ]");
		return sbul.toString();
	}

	
}
