FROM debian:bullseye

RUN apt-get --yes update && apt-get --yes install inotify-tools curl unzip && apt-get clean
RUN cd /tmp && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip -q awscliv2.zip && ./aws/install
