/*
 * ULDSCMReconcilePK.java Created on Aug  01, 2006
 *
 * Copyright 2006 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */

package com.ibsplc.icargo.business.uld.defaults.message;

import java.io.Serializable;
import javax.persistence.Embeddable;
import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-2048
 *
 */
@KeyTable(table = "ULDSCMMSGRECKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "ULDSCMMSGRECKEY", key = "SEQNUM")
@Embeddable
public class ULDSCMReconcilePK implements Serializable{
	
	   
	    
	    
/**
 * 
 */	

	    private String airportCode;
	    /**
	     * 
	     */

	    private String companyCode;
	    /**
	     * 
	     */

	    private int airlineIdentifier;
	    /**
	     * 
	     */

	    private String sequenceNumber;
	    
	   
	   
	    /**
	     * 
	     *
	     */
	    public ULDSCMReconcilePK() {
	    	
	    }
	    /**
	     * 
	     * @param airportCode
	     * @param companyCode
	     * @param sequenceNumber
	     * @param airlineIdentifier
	     */
	    public ULDSCMReconcilePK(String airportCode,
    		                     String companyCode,
    		                     String sequenceNumber,
    		                     int airlineIdentifier) {
	    	
	    	
	    	
	    	this.airportCode = airportCode;
	    	this.companyCode = companyCode;
	    	this.sequenceNumber = sequenceNumber;
	    	this.airlineIdentifier =airlineIdentifier;
	    	
	    }
	    /**
		 * 
		 * @param other 
		 * @return
		 */
		public boolean equals(Object other) {
			return (other != null) && ((hashCode() == other.hashCode()));
		}

		/**
		 * @return
		 */
		public int hashCode() {
			return new StringBuilder().append(airportCode)
			                          .append(companyCode)
			                          .append(sequenceNumber)
			                          .append(airlineIdentifier)
			                          .toString().hashCode();
		}
	    
		/**
		 * @param companyCode The companyCode to set.
		 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	/**
	 * @return Returns the companyCode.
	 */
	    @KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	    /**
		 * @param sequenceNumber The sequenceNumber to set.
		 */
	public void setSequenceNumber(java.lang.String sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	/**
	 * @return Returns the sequenceNumber.
	 */
	    @Key(generator = "ID_GEN", startAt = "1")
	public java.lang.String getSequenceNumber() {
		return this.sequenceNumber;
	}
	    /**
		 * @param airportCode The airportCode to set.
		 */
	public void setAirportCode(java.lang.String airportCode) {
		this.airportCode=airportCode;
	}
	/**
	 * @return Returns the airportCode.
	 */
	    @KeyCondition(column = "ARPCOD")
	public java.lang.String getAirportCode() {
		return this.airportCode;
	}
	    /**
		 * @param airlineIdentifier The airlineIdentifier to set.
		 */
	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier=airlineIdentifier;
	}
	/**
	 * @return Returns the airlineIdentifier.
	 */
	    @KeyCondition(column = "ARLIDR")
	public int getAirlineIdentifier() {
		return this.airlineIdentifier;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:17 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(118);
		sbul.append("ULDSCMReconcilePK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', airportCode '").append(this.airportCode);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
