/*
 * UCMExceptionFlightPK.java Created on Jan 5, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */

package com.ibsplc.icargo.business.uld.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * 
 * @author A-1936
 * 
 * 
 * 
 */
@Embeddable
public class UCMExceptionFlightPK implements Serializable {

	/**
	 * The companyCode
	 */
	private String companyCode;

	/**
	 * The carrierId
	 */
	private int carrierId;

	/**
	 * The flightNumber
	 */
	private String flightNumber;

	/**
	 * The legSerialNumber
	 */
	private int legSerialNumber;

	/**
	 * The flightSequenceNumber
	 */
	private long flightSequenceNumber;

	/**
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return This method returns the HashCode tat is used to check the Equals
	 *         of the Entity
	 * 
	 */
	public int hashCode() {

		return new StringBuffer(companyCode).append(carrierId).append(
				flightNumber).append(legSerialNumber).append(
				flightSequenceNumber).toString().hashCode();
	}


	public void setFlightNumber(java.lang.String flightNumber) {
		this.flightNumber=flightNumber;
	}

	public java.lang.String getFlightNumber() {
		return this.flightNumber;
	}

	public void setCarrierId(int carrierId) {
		this.carrierId=carrierId;
	}

	public int getCarrierId() {
		return this.carrierId;
	}

	public void setLegSerialNumber(int legSerialNumber) {
		this.legSerialNumber=legSerialNumber;
	}

	public int getLegSerialNumber() {
		return this.legSerialNumber;
	}

	public void setFlightSequenceNumber(long flightSequenceNumber) {
		this.flightSequenceNumber=flightSequenceNumber;
	}

	public long getFlightSequenceNumber() {
		return this.flightSequenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:18 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(147);
		sbul.append("UCMExceptionFlightPK [ ");
		sbul.append("carrierId '").append(this.carrierId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', flightNumber '").append(this.flightNumber);
		sbul.append("', flightSequenceNumber '").append(
				this.flightSequenceNumber);
		sbul.append("', legSerialNumber '").append(this.legSerialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
