/*
 * ULDConfigAuditPK.java Created on Aug 1, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject tos license terms.
 */
/**
 *
 */
package com.ibsplc.icargo.business.uld.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1950
 *
 */
@KeyTable(table="ULDCFGAUDKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="AUDSEQ_GEN",table="ULDCFGAUDKEY",key="ULDCFGAUD_SEQNUM")
@Embeddable
public class ULDConfigAuditPK implements Serializable {
    /**
     * Company Code
     */

    private String companyCode;

    /**
     * Audit Sequence number
     */

    private long sequenceNumber;
    /**
     * Constructor
     */
    public ULDConfigAuditPK(){
    }
    /**
     * Constructor
     * @param companyCode
     * @param sequenceNumber
     */
    public ULDConfigAuditPK(String companyCode , long sequenceNumber){
		this.companyCode = companyCode;
        this.sequenceNumber = sequenceNumber;
    }
    /**
     * This method tests for equality of one instance of this class with
     * the other.
     * @param other - another object to test for equality
     * @return boolean - returns true if equal
     */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * This method generates the hashcode of an instance
	 * @return int - returns the hashcode of the instance
	 */
	public int hashCode() {
		return new StringBuilder(companyCode)
					.append(sequenceNumber)
					.toString().hashCode();
	}

	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
    @Key(generator="AUDSEQ_GEN",startAt="1")
	public long getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
    @KeyCondition(column="CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:18 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(65);
		sbul.append("ULDConfigAuditPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
