databaseChangeLog:
  - changeSet:
       id: 1688713995003-39
       author: a-2257
       preConditions:
         - onFail: MARK_RAN
         - tableExists:
              tableName: malevt
       changes:
         dbms: h2, oracle
         endDelimiter: \nGO
         splitStatements: false
         sql: alter table
                malevt
              add
                column if not exists lstupdtim timestamp(3) null;
              comment on column "malevt"."lstupdtim" is '<columnaccount>base</columnaccount>
              < columnname > lstupdtim < / columnname >
              < columndescription > last updated time < / columndescription > ';
  - changeSet:
       id: 1688713995003-40
       author: a-2257
       preConditions:
         - onFail: MARK_RAN
         - tableExists:
              tableName: malevt
       changes:
         dbms: h2, oracle
         endDelimiter: \nGO
         splitStatements: false
         sql: alter table
                malevt
              add
                column if not exists lstupdusr varchar(50) null;
              comment on column "malevt"."lstupdusr" is '<columnaccount>base</columnaccount>
              < columnname > lstupdusr < / columnname >
              < columndescription > last updated user < / columndescription > ';
