databaseChangeLog:
- changeSet:
    id: 1689080931429-1
    author: A-2257 (generated)
    changes:
    - createSequence:
        cacheSize: 1
        cycle: false
        dataType: bigint
        incrementBy: 1
        maxValue: 999999999999
        minValue: 1
        sequenceName: malcalmst_seq
        startValue: 1
- changeSet:
    id: 1689080931429-2
    author: A-2257 (generated)
    changes:
    - createSequence:
        cacheSize: 1
        cycle: false
        dataType: bigint
        incrementBy: 1
        maxValue: 999999999999
        minValue: 1
        sequenceName: malctsarp_seq
        startValue: 1
- changeSet:
    id: 1689080931429-3
    author: A-2257 (generated)
    changes:
    - createSequence:
        cacheSize: 1
        cycle: false
        dataType: bigint
        incrementBy: 1
        maxValue: 9999999999
        minValue: 1
        sequenceName: malgpactr_seq
        startValue: 1
- changeSet:
    id: 1689080931429-4
    author: A-2257 (generated)
    changes:
    - createSequence:
        cacheSize: 1
        cycle: false
        dataType: bigint
        incrementBy: 1
        maxValue: 999999999999
        minValue: 1
        sequenceName: malhndtim_seq
        startValue: 1
- changeSet:
    id: 1689080931429-5
    author: A-2257 (generated)
    changes:
    - createSequence:
        cacheSize: 1
        cycle: false
        dataType: bigint
        incrementBy: 1
        maxValue: 9223372036854775807
        minValue: 1
        sequenceName: malmrainccfg_seq
        startValue: 1
- changeSet:
    id: 1689080931429-6
    author: A-2257 (generated)
    changes:
    - createSequence:
        cacheSize: 1
        cycle: false
        dataType: bigint
        incrementBy: 1
        maxValue: 9223372036854775807
        minValue: 1
        sequenceName: malmrainccfgdtl_seq
        startValue: 1
- changeSet:
    id: 1689080931429-7
    author: A-2257 (generated)
    changes:
    - createSequence:
        cacheSize: 1
        cycle: false
        dataType: bigint
        incrementBy: 1
        maxValue: 9999999999999999
        minValue: 1
        sequenceName: malmsgcfg_seq
        startValue: 1
- changeSet:
    id: 1689080931429-8
    author: A-2257 (generated)
    changes:
    - createSequence:
        cacheSize: 1
        cycle: false
        dataType: bigint
        incrementBy: 1
        maxValue: 999999999
        minValue: 1
        sequenceName: malrdtreqdlvtim_seq
        startValue: 1

