/*
 * GPAReportingDetailsPK.java Created on Dec 19, 2018
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.gpareporting;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;


/**
 * @author A-8527
 *
 */
@Embeddable
public class GPAInvoicMasterPK implements Serializable {

	/**
	 * companyCode
	 */

	private String companyCode;

	/**
	 * invoicRefNum
	 */

	private String invoicRefNum;

	/**
	 * sequenceNumber
	 */

	private long sequenceNumber;


	
	
	

	/**
	 * Default constructor
	 *
	 */
	public GPAInvoicMasterPK() {
	}

	/**
	 * 
	 * @param companyCode
	 * @param poaCode
	 * @param invoicRefNo
	 * @param sequenceNumber
	 */
	public GPAInvoicMasterPK(String companyCode, String poaCode,
			String invoicRefNo,int sequenceNumber) {
		this.companyCode = companyCode;
		this.invoicRefNum = invoicRefNo;
		this.sequenceNumber = sequenceNumber;
	}

	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		boolean isEqual = false;
		if(other != null){
			isEqual = this.hashCode() == other.hashCode();
		}
		return isEqual;
	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return this.toString().hashCode();
	}

	/**
	 * 
	 * @param sequenceNumber
	 */
	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	/**
	 * 
	 * @return long
	 */
	@KeyCondition(column =  "SERNUM")
	public long getSequenceNumber() {
		return this.sequenceNumber;
	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	/**
	 * 
	 * @return
	 */
	@KeyCondition(column =  "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	@KeyCondition(column =  "INVREFNUM")
	public String getInvoicRefNum() {
		return invoicRefNum;
	}

	public void setInvoicRefNum(String invoicRefNum) {
		this.invoicRefNum = invoicRefNum;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(142);
		sbul.append("GPAInvoicMasterPK [ ");
		sbul.append("invoicRefNum '").append(this.invoicRefNum);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
