/*
 * GPAReportingBillingPK.java Created on SEP 29,2008
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.mail.mra.gpareporting;


/**
 * @author A-3447
 * 
 */
import java.io.Serializable;
import javax.persistence.Embeddable;

/**
 * @author a-3447
 */

@Embeddable
public class GPAReportingBillingPK implements Serializable {

	private String companyCode;

	private String billingIdentifier;
	
	private String poaCode;

	

	

	/**
	 * @return the billingIdentifier
	 */
	public String getBillingIdentifier() {
		return billingIdentifier;
	}

	/**
	 * @param billingIdentifier the billingIdentifier to set
	 */
	public void setBillingIdentifier(String billingIdentifier) {
		this.billingIdentifier = billingIdentifier;
	}

	/**
	 * @return the poaCode
	 */
	public String getPoaCode() {
		return poaCode;
	}

	/**
	 * @param poaCode the poaCode to set
	 */
	public void setPoaCode(String poaCode) {
		this.poaCode = poaCode;
	}

	/**
	 * constructor
	 * 
	 */
	public GPAReportingBillingPK() {
	}

	/**
	 * 
	 * @param companyCode
	 * @param billingBasis
	 * @param serialNumber
	 * @param ccaRefNumber
	 *  @author a-3447
	 * 
	 */
	public GPAReportingBillingPK(String companyCode, String billingIdentifier,
			String poaCode) {

		this.companyCode = companyCode;
		this.billingIdentifier = billingIdentifier;
		this. poaCode =  poaCode;
		
	}

	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		if (other != null) {
			return hashCode() == other.hashCode();
		} else {
			return false;
		}

	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).append(billingIdentifier).append(poaCode).toString().hashCode();

	}

	/**
	 * 
	 * @param companyCode
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * 
	 * @return
	 */
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:54 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(92);
		sbul.append("GPAReportingBillingPK [ ");
		sbul.append("billingIdentifier '").append(this.billingIdentifier);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', poaCode '").append(this.poaCode);
		sbul.append("' ]");
		return sbul.toString();
	}

	

	
}
