databaseChangeLog:
  - include:
      file: changelog/neo-mailmaster.changelog-master-1.0.yaml
      relativeToChangelogFile: true
  - include:
      file: changelog/neo-mailmaster.changelog-seq-1.0.yaml
      relativeToChangelogFile: true
  - include:
      file: changelog/neo-mailmaster.changelog-alters-1.0.yaml
      relativeToChangelogFile: true
  - include:
      file: changelog/neo-mailmaster.changelog-altersmalevt-1.0.yaml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-76549_MSM32101.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-81232_MSM32441.yml
      relativeToChangelogFile: true