//common
export const LIST_DETAILS_FLIGHT = 'LIST_DETAILS_FLIGHT';
export const LIST_DETAILS_CARRIER = 'LIST_DETAILS_CARRIER';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const LIST_CONTAINER = 'LIST_CONTAINER';
export const LIST_MAILBAGS = 'LIST_MAILBAGS';
export const ADD_CONTAINER = 'ADD_CONTAINER';
export const MODIFY = 'MODIFY';
export const ATTACH_AWB = 'ATTACH_AWB';
export const GROUP_VIEW = 'GROUP_VIEW';
export const SET_WARNING_MAP = 'SET_WARNING_MAP';
export const ATTACH_ROUTING = 'ATTACH_ROUTING';
export const ATTACHROUTING = 'ATTACH ROUTING';
export const LIST_NEW_CONTAINER_SUCESS = 'LIST_NEW_CONTAINER_SUCESS';
export const SCREENLOAD_ADD_MODIFY_CONTAINER = 'SCREENLOAD_ADD_MODIFY_CONTAINER';
export const CLEAR_TABLE = 'CLEAR_TABLE';
export const CLEAR_FLIGHT_TABLE_DATA = 'CLEAR_FLIGHT_TABLE_DATA';
export const DETACH_AWB = 'DETACH_AWB';

//listflightreducer
export const SAVE_SELECTED = 'SAVE_SELECTED';
export const SAVE_INDEX_FORPRINT = 'SAVE_INDEX_FORPRINT';
export const LIST_FLIGHT_FILTER = 'LIST_FLIGHT_FILTER';
export const LIST_CARRIER_FILTER = 'LIST_CARRIER_FILTER';
export const CLEAR_FLIGHT_FILTER = 'CLEAR_FLIGHT_FILTER';
export const CLEAR_CARRIER_FILTER = 'CLEAR_CARRIER_FILTER';
export const UPDATE_FLIGHT_SORT_VARIABLE = 'UPDATE_FLIGHT_SORT_VARIABLE';
export const CLEAR_SELECTED_FLIGHTS = 'CLEAR_SELECTED_FLIGHTS';
export const PREADVICE_POPUP = 'PREADVICE_POPUP';
export const PREADVICE_OK = 'PREADVICE_OK';
export const UPDATE_CARRIER_SORT_VARIABLE = 'UPDATE_CARRIER_SORT_VARIABLE';
export const SAVE_INITIAL_FLIGHT_FILTER = 'SAVE_INITIAL_FLIGHT_FILTER'

//filterreducer
export const LIST_CAPACITY_FLIGHT = 'LIST_CAPACITY_FLIGHT';
export const LIST_VOLUME_FLIGHT = 'LIST_VOLUME_FLIGHT';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const FETCH_CAPACITY = 'FETCH_CAPACITY';
export const FETCH_PREADVICE ='FETCH_PREADVICE';
export const LIST_PREADVICE_FLIGHT = 'LIST_PREADVICE_FLIGHT';
export const FETCH_VOLUME = 'FETCH_VOLUME';
//commonreducer
export const SCREENLOAD_SUCCESS = 'SCREENLOAD_SUCCESS';
export const CHOOSE_FILTER = 'CHOOSE_FILTER';
export const TOGGLE_FLIGHT_PANEL = 'TOGGLE_FLIGHT_PANEL';
export const TOGGLE_CARDIT_VIEW = 'TOGGLE_CARDIT_VIEW';
export const CHANGE_CARDITLYINGLIST_TAB = 'CHANGE_CARDITLYINGLIST_TAB';


//containerreducer
export const LIST_CONTAINER_CARRIER = 'LIST_CONTAINER_CARRIER';
export const SAVE_SELECTED_CONTAINER_INDEX = 'SAVE_SELECTED_CONTAINER_INDEX';
export const LIST_CONTAINER_FILTER = 'LIST_CONTAINER_FILTER';
export const CLEAR_CONTAINER_FILTER = 'CLEAR_CONTAINER_FILTER';
export const ADD_CONTAINER_POPUPCLOSE = 'ADD_CONTAINER_POPUPCLOSE';
export const POPULATE_MAILBAGS = 'POPULATE_MAILBAGS';
export const ADDCONTAINER_LOADED = 'ADDCONTAINER_LOADED';
export const PABUILT_FLAG = 'PABUILT_FLAG';
export const REASSIGN_SUCCESS = 'REASSIGN_SUCCESS';
export const UNASSIGN_SUCCESS = 'UNASSIGN_SUCCESS';
export const ATTACH_AWB_LIST = 'ATTACH_AWB_LIST';
export const ATTACH_AWB_SAVE = 'ATTACH_AWB_SAVE';
export const ATTACH_AWB_CLOSE = 'ATTACH_AWB_CLOSE';
export const ATTACH_ROUTING_LIST = 'ATTACH_ROUTING_LIST';
export const ATTACH_ROUTING_SAVE = 'ATTACH_ROUTING_SAVE';
export const ATTACH_ROUTING_CLOSE = 'ATTACH_ROUTING_CLOSE';
export const REASSIGN_CLOSE = 'REASSIGN_CLOSE';
export const VALIDATECONTAINER_SUCCESS = 'VALIDATECONTAINER_SUCCESS';
export const VALIDATE_CONTAINER_REASSIGN_FLIGHT_SUCCESS = 'VALIDATE_CONTAINER_REASSIGN_FLIGHT_SUCCESS';
export const UPDATE_CONTAINER_SORT_VARIABLE = 'UPDATE_CONTAINER_SORT_VARIABLE';
export const CLEAR_AWB = 'CLEAR_AWB';
export const CLEAR_ATTACH_ROUTING = 'CLEAR_ATTACH_ROUTING';
export const LIST_DISABLE = 'LIST_DISABLE';
export const APPLY_CONTAINER_SORT = 'APPLY_CONTAINER_SORT';
export const APPLY_CONTAINER_FILTER = 'APPLY_CONTAINER_FILTER';
export const LIST_DETAILS_REASSIGN_FLIGHT = 'LIST_DETAILS_REASSIGN_FLIGHT';
export const LIST_CAPACITY_REASSIGN_FLIGHT = 'LIST_CAPACITY_REASSIGN_FLIGHT';
export const SAVE_SELECTED_FLIGHT_INDEX = 'SAVE_SELECTED_FLIGHT_INDEX';
export const CLEAR_REASSIGN_FLIGHT_PANEL = 'CLEAR_REASSIGN_FLIGHT_PANEL';
export const CONTAINER_MODIFY ='CONTAINER_MODIFY';
export const BARROW_CHECK ='BARROW_CHECK';
export const VALIDATEFORTRANSFER_SUCCESS='VALIDATEFORTRANSFER_SUCCESS'
export const TRANSFER_CLOSE='TRANSFER_CLOSE';
export const TRANSFERSAVE_SUCCESS='TRANSFERSAVE_SUCCESS';
export const TRANSFER_FLIGHT='TRANSFER_FLIGHT';
export const VALIDATE_CONTAINER_TRANSFER_FLIGHT_SUCCESS='VALIDATE_CONTAINER_TRANSFER_FLIGHT_SUCCESS';
//mailbagreducer

export const LIST_MAILBAGS_DSN = 'LIST_MAILBAGS_DSN';
export const CHANGE_MAILBAG_TAB = 'CHANGE_MAILBAG_TAB';
export const SAVE_SELECTED_MAILBAGS_INDEX = 'SAVE_SELECTED_MAILBAGS_INDEX';
export const CHANGE_ADD_MAILBAG_TAB = 'CHANGE_ADD_MAILBAG_TAB';
export const ADD_MAILBAG_POPUPCLOSE = 'ADD_MAILBAG_POPUPCLOSE';
export const SCREENLOAD_ADD_MODIFY_MAILBAG = 'SCREENLOAD_ADD_MODIFY_MAILBAG';
export const ADD_MAILBAG_SUCCESS = 'ADD_MAILBAG_SUCCESS';
export const UPDATE_MAILBAGS_IN_ADD_POPUP = 'UPDATE_MAILBAGS_IN_ADD_POPUP';
export const SHOW_IMPORT_POPUP = 'SHOW_IMPORT_POPUP';
export const CLOSE_IMPORT_POPUP = 'CLOSE_IMPORT_POPUP';
export const IMPORT_MAILBAGS = 'IMPORT_MAILBAGS';
export const REMARKS_POPUP_OPEN = 'REMARKS_POPUP_OPEN';
export const REMARKS_CLOSE = 'REMARKS_CLOSE';
export const SCAN_TIME_POPUP_OPEN = 'SCAN_TIME_POPUP_OPEN';
export const SCAN_TIME_CLOSE = 'SCAN_TIME_CLOSE';
//same popup will be used to capture scan time while assign mails bags from cardit section
export const ASSIGN_SCAN_TIME_POPUP_OPEN = 'ASSIGN_SCAN_TIME_POPUP_OPEN';
export const ASSIGN_SCAN_TIME_CLOSE = 'ASSIGN_SCAN_TIME_CLOSE';
export const CHECK_MODIFIED_MAIL='CHECK_MODIFIED_MAIL';

export const DELETE_MAILBAGS = 'DELETE_MAILBAGS';
export const FLIGHT_SUCCESS = 'FLIGHT_SUCCESS';
export const LIST_REASSIGN_CONTAINER = 'LIST_REASSIGN_CONTAINER';
export const REASSIGN_POPUP_OPEN = 'REASSIGN_POPUP_OPEN';
export const CONTAINER_REASSIGN_SUCCESS = 'CONTAINER_REASSIGN_SUCCESS';
export const CLOSE_POP_UP = 'CLOSE_POP_UP';
export const VALIDATE_FLIGHT = 'VALIDATE_FLIGHT';
export const MAILBAG_RETURN_OPEN = 'MAILBAG_RETURN_OPEN';
export const RETURN_POPUP_CLOSE = 'RETURN_POPUP_CLOSE';
export const RETURN_CLOSE = 'RETURN_CLOSE';
export const LIST_FILTER = 'LIST_FILTER';
export const CLEAR_TABLE_FILTER = 'CLEAR_TABLE_FILTER';
export const EXISTING_MAILBAG_POPUP_OPEN = 'EXISTING_MAILBAG_POPUP_OPEN';
export const EXISTING_MAILBAG_POPUP_CLOSE = 'EXISTING_MAILBAG_POPUP_CLOSE';
export const RETURN = 'RETURN';
export const DAMAGE_CAPTURE = 'DAMAGE_CAPTURE';
export const ADD_MAILBAG = 'ADD_MAILBAG';
export const MODIFY_MAILBAG = 'MODIFY_MAILBAG';
export const APPLY_MAILBAG_SORT = 'APPLY_MAILBAG_SORT';
export const APPLY_MAILBAG_FILTER = 'APPLY_MAILBAG_FILTER';
export const CLEAR_REASSIGN_FORM = 'CLEAR_REASSIGN_FORM';
export const MAIL_CLEAR = 'MAIL_CLEAR';
export const APPLY_MAILBAG_DSN_FILTER='APPLY_MAILBAG_DSN_FILTER'
export const TRANSFER_POPUP_OPEN = 'TRANSFER_POPUP_OPEN';
export const TRANSFER='TRANSFER';
export const LIST_CONTAINERS_POPUP='LIST_CONTAINERS_POPUP';
export const TRANSFER_POPUP_CLEAR='TRANSFER_POPUP_CLEAR';
export const CLEAR_TRANSFER_FORM= 'CLEAR_TRANSFER_FORM';
export const  TRANSFER_SAVE='TRANSFER_SAVE';
export const LIST_TRANSFER='LIST_TRANSFER';

//carditreducer
export const CHANGE_CARDITS_TAB = 'CHANGE_CARDITS_TAB';
export const CARDIT_LIST_VIEW = 'CARDIT_LIST_VIEW';
export const CARDIT_GROUP_VIEW = 'CARDIT_GROUP_VIEW';
export const SAVE_CARDIT_LIST_FILTER = 'SAVE_CARDIT_LIST_FILTER';
export const SAVE_CARDIT_GROUP_FILTER = 'SAVE_CARDIT_GROUP_FILTER';
export const CARDIT_FILTER_APPLIED = 'CARDIT_FILTER_APPLIED';
export const CLEAR_FILTER_APPLIED = 'CLEAR_FILTER_APPLIED';
export const CARDIT_MAIL_SELECTED = 'CARDIT_MAIL_SELECTED';


//lyinglistreducer
export const CHANGE_LYING_TAB = 'CHANGE_LYING_TAB';
export const LYING_LIST_VIEW = 'LYING_LIST_VIEW';
export const LYING_GROUP_VIEW = 'LYING_GROUP_VIEW';
export const LYING_FILTER_APPLIED = 'LYING_FILTER_APPLIED';
export const LYING_MAIL_SELECTED = 'LYING_MAIL_SELECTED';
export const CLEAR_LYINGLIST_FILTER = 'CLEAR_LYINGLIST_FILTER';

//deviationlistreducer
export const CHANGE_DEVIATION_TAB = 'CHANGE_DEVIATION_TAB'
export const DEVIATION_LIST_VIEW = 'DEVIATION_LIST_VIEW'
export const DEVIATION_GROUP_VIEW = 'DEVIATION_GROUP_VIEW'
export const DEVIATION_FILTER_APPLIED = 'DEVIATION_FILTER_APPLIED'
export const CLEAR_DEVIATIONLIST_FILTER = 'CLEAR_DEVIATIONLIST_FILTER'
export const DEVIATION_MAIL_SELECTED = 'DEVIATION_MAIL_SELECTED'
export const LIST_NO_RECORDS = 'LIST_NO_RECORDS'

//carditaction
export const LIST_VIEW = 'LIST_VIEW';

//carrierlistaction

//commonaction
export const OUTBOUND_FILTER = 'outboundFilter';
export const CARDIT_LIST = 'CARDIT_LIST';
export const DELEGATE_WARNING_ONOK = '__DELEGATE_WARNING_ONOK';
export const DELEGATE_WARNING_ONCANCEL = '__DELEGATE_WARNING_ONCANCEL';


//containeractions
export const CHECK_CLOSE_FLIGHT = 'CHECK_CLOSE_FLIGHT';
export const REASSIGN = 'REASSIGN';
export const REASSIGN_FLIGHT = 'REASSIGN_FLIGHT';
export const UNASSIGN = 'UNASSIGN';
export const LIST_NEW_CONTAINER = 'LIST_NEW_CONTAINER';
export const ATTACH_ROUTING_ERROR = 'ATTACH_ROUTING_ERROR';
export const ADD_CONTAINER_FORM = 'addcontainerForm';
export const SELECT_CONTAINER = 'SELECT_CONTAINER';
export const ERROR_SHOW = 'ERROR_SHOW';
export const ADD_MAILBAGS_CLOSE = 'ADD_MAILBAGS_CLOSE';
export const DO_RETURN = 'DO_RETURN';
export const REASSIGN_EXISTING_MAILBAGS = 'REASSIGN_EXISTING_MAILBAGS';
export const ULD_MARK_FULL = 'ULD_MARK_FULL';
export const ULD_UNMARK_FULL = 'ULD_UNMARK_FULL';
export const PRINT_ULD_TAG = 'PRINT_ULD_TAG'
// flightlistactions
export const CLOSE_FLIGHT = 'CLOSE_FLIGHT';
export const REOPEN_FLIGHT = 'REOPEN_FLIGHT';
export const AUTO_ATTACH_AWB = 'AUTO_ATTACH_AWB';
export const MANIFEST_POPUP_CLOSE = 'MANIFEST_POPUP_CLOSE';
export const ULD_ANNOUNCE = 'ULD_ANNOUNCE'
//mailbagactions
export const DSN_VIEW = 'DSN_VIEW';
export const MAIL_VIEW = 'MAIL_VIEW';
export const SCREENLOAD_ADDMODIFY_MAILBAG = 'SCREENLOAD_ADDMODIFY_MAILBAG';
export const NEW_MAILBAGS_TABLE = 'newMailbagsTable';
export const NOMINATION_ID_NOT_FOUND = 'NOMINATION_ID_NOT_FOUND';
export const SCREENLOAD_ADD_MAILBAG = 'SCREENLOAD_ADD_MAILBAG';
export const DELETE = 'DELETE';
export const VIEW_DAMAGE = 'VIEW_DAMAGE';
export const DELIVER_MAIL = 'DELIVER_MAIL';
export const REMARKS = 'REMARKS';
export const ON_ROW_SELECT = 'ON_ROW_SELECT';
export const DAMAGE_SUCCESS = 'DAMAGE_SUCCESS';
export const DELIVER_SUCCESS = 'DELIVER_SUCCESS';
export const LIST_SUCCESS = 'LIST_SUCCESS';
export const NO_DAMAGE = 'NO_DAMAGE';
export const NO_CONTAINER = 'NO_CONTAINER';
export const NO_DATA = 'NO_DATA';
export const DO_REASSIGN = 'DO_REASSIGN';
export const DO_TRANSFER = 'DO_TRANSFER';
export const DSN_ATTACH_AWB = 'DSN_ATTACH_AWB';
export const DSN_ATTACH_ROUTING = 'DSN_ATTACH_ROUTING';
export const DSN_DETACH_AWB = 'DSN_DETACH_AWB';
export const SAVE_REASSIGN = 'SAVE_REASSIGN';
//containertablecontainer
export const OFFLOAD = 'OFFLOAD';
export const ATTACH_ROUT = 'ATTACH_ROUT';
//mailbagtablecontainer
export const CANCEL_REASSIGN = 'CANCEL_REASSIGN';
export const DELETE_CONTAINER = 'DELETE_CONTAINER';
export const BULK_CONVERSION = 'BULK_CONVERSION';
export const ULD_CONVERSION = 'ULD_CONVERSION';
export const CONTAINER_CONVERSION ='CONTAINER_CONVERSION';
export const APPLY_DSN_FILTER = 'APPLY_DSN_FILTER';
export const DSN_FILTER = 'dsnFilter';
export const APPLY_CARRIER_SORT='APPLY_CARRIER_SORT';
export const UPDATE_POPUP_HANDLER='UPDATE_POPUP_HANDLER';