package com.ibsplc.icargo.business.addons.mail.operations;


import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.SequenceKeyGenerator;

/**
 *	Java file	: 	.MailBookingDetailPK.java
 *
 *	Created by	:	a-7779
 *	Created on	:	22-Aug-2017
 *
 *  Copyright 2017 Copyright 2007 IBS Software Services (P) Ltd. All Rights Reserved. Ltd. All Rights Reserved.
 *
 * 	This software is the proprietary information of Copyright 2007 IBS Software Services (P) Ltd. All Rights Reserved.  Ltd.
 * 	Use is subject to license terms.
 */

/**
 *	Java file	: 	.MailBookingDetailPK.java
 *	Version		:	Name	:	Date			:	Updation
 * ---------------------------------------------------
 *		0.1		:	a-7779	:	22-Aug-2017	:	Draft
 */
@SequenceKeyGenerator(name = "ID_GEN", sequence = "MALBKGFLTDTL_SEQ")
@Embeddable
public class MailBookingDetailPK implements Serializable {

	private String companyCode;
	private String flightNumber;
	private int flightCarrierId;
	private long flightSequenceNumber;
	private long mailSequenceNumber;
	private int serialNumber;
	private int segementserialNumber;



	 /**
     * This method tests for equality of one instance of this class with
     * the other.
     * @param other - another object to test for equality
     * @return boolean - returns true if equal
     */
	public boolean equals(Object other) {
		return (other != null) && (hashCode() == other.hashCode());
	}
	/**
	 * This method generates the hashcode of an instance
	 * @return int - returns the hashcode of the instance
	 */
	public int hashCode() {
		return new StringBuilder(companyCode).append(flightNumber).append(flightCarrierId)
				.append(flightSequenceNumber).append(mailSequenceNumber).append(segementserialNumber).append(serialNumber).toString().hashCode();
	}
	@KeyCondition(column = "CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	//@KeyCondition(column = "FLTNUM")
	public String getFlightNumber() {
		return flightNumber;
	}

	public void setFlightNumber(String flightNumber) {
		this.flightNumber = flightNumber;
	}
	//@KeyCondition(column = "FLTCARIDR")
	public int getFlightCarrierId() {
		return flightCarrierId;
	}

	public void setFlightCarrierId(int flightCarrierId) {
		this.flightCarrierId = flightCarrierId;
	}
	//@KeyCondition(column = "FLTSEQNUM")
	public long getFlightSequenceNumber() {
		return flightSequenceNumber;
	}

	public void setFlightSequenceNumber(long flightSequenceNumber) {
		this.flightSequenceNumber = flightSequenceNumber;
	}
	//@KeyCondition(column = "MALSEQNUM")
	public long getMailSequenceNumber() {
		return mailSequenceNumber;
	}

	public void setMailSequenceNumber(long mailSequenceNumber) {
		this.mailSequenceNumber = mailSequenceNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public int getSerialNumber() {
		return serialNumber;
	}

	public void setSerialNumber(int serialNumber) {
		this.serialNumber = serialNumber;
	}
	//@KeyCondition(column = "SEGSERNUM")
	public int getSegementserialNumber() {
		return segementserialNumber;
	}

	public void setSegementserialNumber(int segementserialNumber) {
		this.segementserialNumber = segementserialNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:38 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(83);
		sbul.append("MailBookingDetailPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', serialNumber '").append(this.serialNumber);
		sbul.append("', flightNumber '").append(this.flightNumber);
		sbul.append("', flightCarrierId '").append(this.flightCarrierId);
		sbul.append("', flightSequenceNumber '").append(this.flightSequenceNumber);
		sbul.append("', mailSequenceNumber '").append(this.mailSequenceNumber);
		sbul.append("', segementserialNumber '").append(this.segementserialNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}

