/*
 * AccessoryTransactionPK.java Created on Jan 6, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.transaction;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1496
 *
 */
@Embeddable
@KeyTable(table = "ULDACCTXNKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "ULDACCTXNKEY", key = "MAX_SERNUM")
public class AccessoryTransactionPK  implements Serializable { 
	
	/**
	 * 
	 */

      private String companyCode;
	
	/**
	 * 
	 */

       private String accessoryCode;
	
	/**
	 * 
	 */

    private int transactionRefNumber;
    
    /**
     * Default constructor
     */
	public AccessoryTransactionPK() {
	}

	/**
	 * 
	 * @param companyCode
	 * @param accessoryCode
	 * @param transactionRefNumber
	 */
    public AccessoryTransactionPK(
    	String companyCode, 
    	String accessoryCode,
    	int transactionRefNumber) {
    	this.companyCode = companyCode;
    	this.accessoryCode = accessoryCode;
    	this.transactionRefNumber = transactionRefNumber; 
	}
    /**
     * This method tests for equality of one instance of this class with
     * the other.
     * @param other - another object to test for equality
     * @return boolean - returns true if equal
     */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * This method generates the hashcode of an instance
	 * @return int - returns the hashcode of the instance
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
				append(accessoryCode).
				append(transactionRefNumber).
				toString().hashCode();
	}



	public void setAccessoryCode(java.lang.String accessoryCode) {
		this.accessoryCode=accessoryCode;
	}
	@KeyCondition(column = "ACCCOD")   
	public java.lang.String getAccessoryCode() {
		return this.accessoryCode;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")   
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setTransactionRefNumber(int transactionRefNumber) {
		this.transactionRefNumber=transactionRefNumber;
	}
	 @Key(generator = "ID_GEN", startAt = "1")    
	public int getTransactionRefNumber() {
		return this.transactionRefNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:18 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(102);
		sbul.append("AccessoryTransactionPK [ ");
		sbul.append("accessoryCode '").append(this.accessoryCode);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', transactionRefNumber '").append(
				this.transactionRefNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
