/*
 * RangePK.java Created on Sep 3, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.stockcontrol.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1366
 * *
 */
@KeyTable(table="STKRNGKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="STKRNG_GEN",table="STKRNGKEY",key="STKRNGKEY_SEQ")
@Embeddable
public class RangePK implements Serializable {

    /**
     * Company Code
     *
     */

    private String companyCode;

	/**
	 *
	 */

	private int airlineIdentifier;
    /**
	 * Stock holder code
	 */

    private String stockHolderCode;
    /**
	 * Stock holder code
	 */

    private String documentType;
    /**
	 * Stock holder code
	*/

    private String documentSubType;
    /**
     * Request Reference Number
     *
     */

    private String rangeSequenceNumber;

    /**
	 * return the hashcode corresponding to that product
	 * @return int
	 */
	 public int hashCode() {
		return new StringBuilder().append(companyCode)
			.append(airlineIdentifier)
			.append(stockHolderCode)
			.append(documentType)
			.append(documentSubType)
			.append(rangeSequenceNumber)
			.toString().hashCode();
	}
	 /**
	  * Compare two object and return boolean
	  * @param other
	  * @return boolean
	  */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * @return Returns the airlineIdentifier.
	 */
	@KeyCondition(column="ARLIDR")
	public int getAirlineIdentifier() {
		return airlineIdentifier;
	}
	/**
	 * @param airlineIdentifier The airlineIdentifier to set.
	 */
	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier = airlineIdentifier;
	}
	/**
	 * @return Returns the companyCode.
	 */
	@KeyCondition(column="CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the documentSubType.
	 */
	 @KeyCondition(column="DOCSUBTYP")
	public String getDocumentSubType() {
		return documentSubType;
	}
	/**
	 * @param documentSubType The documentSubType to set.
	 */
	public void setDocumentSubType(String documentSubType) {
		this.documentSubType = documentSubType;
	}
	/**
	 * @return Returns the documentType.
	 */
	@KeyCondition(column="DOCTYP")
	public String getDocumentType() {
		return documentType;
	}
	/**
	 * @param documentType The documentType to set.
	 */
	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}
	/**
	 * @return Returns the rangeSequenceNumber.
	 */
	 @Key(generator="STKRNG_GEN",startAt="1")
	public String getRangeSequenceNumber() {
		return rangeSequenceNumber;
	}
	/**
	 * @param rangeSequenceNumber The rangeSequenceNumber to set.
	 */
	public void setRangeSequenceNumber(String rangeSequenceNumber) {
		this.rangeSequenceNumber = rangeSequenceNumber;
	}
	/**
	 * @return Returns the stockHolderCode.
	 */
	@KeyCondition(column="STKHLDCOD")
	public String getStockHolderCode() {
		return stockHolderCode;
	}
	/**
	 * @param stockHolderCode The stockHolderCode to set.
	 */
	public void setStockHolderCode(String stockHolderCode) {
		this.stockHolderCode = stockHolderCode;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:15 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(168);
		sbul.append("RangePK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', documentSubType '").append(this.documentSubType);
		sbul.append("', documentType '").append(this.documentType);
		sbul.append("', rangeSequenceNumber '")
				.append(this.rangeSequenceNumber);
		sbul.append("', stockHolderCode '").append(this.stockHolderCode);
		sbul.append("' ]");
		return sbul.toString();
	}

}
