/*
 * StockRangeUtilisationLogPK.java Created on Dec 01, 2009
 *
 * Copyright 2007 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of
 * IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.stockcontrol.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * 
 * @author A-3155
 *
 */
@Embeddable
public class StockRangeUtilisationLogPK implements Serializable{

	/**
     * Company Code
     *
     */
       
    private String companyCode;

	/**
	 *
	 */

	private int airlineIdentifier;
    /**
	 * documentNumber
	 */

    private String documentNumber;
    
    private String documentType;

    private String documentSubType;
    
	public String getDocumentType() {
		return documentType;
	}
	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}
	public String getDocumentSubType() {
		return documentSubType;
	}
	public void setDocumentSubType(String documentSubType) {
		this.documentSubType = documentSubType;
	}
    
	/**
	 * Default constructor
	 */
	public StockRangeUtilisationLogPK() {

	}

	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode)
				.append(airlineIdentifier).append(documentNumber).toString()
				.hashCode();
	}

	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return the companyCode
	 */
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode the companyCode to set
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return the airlineIdentifier
	 */
	public int getAirlineIdentifier() {
		return airlineIdentifier;
	}
	/**
	 * @param airlineIdentifier the airlineIdentifier to set
	 */
	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier = airlineIdentifier;
	}
	/**
	 * @return the documentNumber 
	 */
	public String getDocumentNumber() {
		return documentNumber;
	}
	/**
	 * @param documentNumber the documentNumber to set
	 */
	public void setDocumentNumber(String documentNumber) {
		this.documentNumber = documentNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:15 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(104);
		sbul.append("StockRangeUtilisationLogPK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', documentNumber '").append(this.documentNumber);
		sbul.append("', documentType '").append(this.documentType);
		sbul.append("', documentSubType '").append(this.documentSubType);
		sbul.append("' ]");
		return sbul.toString();
	}
}
