/*
 * StockRequestAuditPK.java Created on Sep 7, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.stockcontrol.defaults;

import java.io.Serializable;


import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1366
 */
@KeyTable(table="STKREQAUDKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="STKAUDSEQ_GEN",table="STKREQAUDKEY",key="STKAUDSEQ_SEQ")
@Embeddable

public class StockRequestAuditPK implements Serializable {
	/**
	 * Company Code
	 */

	private String companyCode;
	/**
	 * Request Reference Number
	 */

	private String requestRefNumber;

	/**
	 * Audit sequence number
	 */

	private long sequenceNumber;
	/**
	 * Constructor
	 *
	 */
	public StockRequestAuditPK(){
	}
	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * @return int
	 *
	 */
	public int hashCode() {
		return new StringBuffer(companyCode)
		.append(requestRefNumber).append(sequenceNumber).
		toString().hashCode();
	}
	/**
	 * @return Returns the companyCode.
	 */
	@KeyCondition(column="CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the requestRefNumber.
	 */
	@KeyCondition(column="REQREFNUM")
	public String getRequestRefNumber() {
		return requestRefNumber;
	}
	/**
	 * @param requestRefNumber The requestRefNumber to set.
	 */
	public void setRequestRefNumber(String requestRefNumber) {
		this.requestRefNumber = requestRefNumber;
	}
	/**
	 * @return Returns the sequenceNumber.
	 */
	@Key(generator="STKAUDSEQ_GEN",startAt="1")
	public long getSequenceNumber() {
		return sequenceNumber;
	}
	/**
	 * @param sequenceNumber The sequenceNumber to set.
	 */
	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:15 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(96);
		sbul.append("StockRequestAuditPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', requestRefNumber '").append(this.requestRefNumber);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}

}
