/*
 * StockAuditPK.java Created on Jul 20, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.stockcontrol.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;


import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1358
 *
 */

@KeyTable(table="STKAUDKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="AUDSEQ_GEN",table="STKAUDKEY",key="STKAUD_SEQ")
@Embeddable
public class StockAuditPK implements Serializable {

	/**
	 *
	 */

    private String companyCode;

    /**
     *
     */

    private String documentType;


    /**
     *
     */

	private String documentSubType;

	//To be reviewed
	/**
	 *
	 */

	private int airlineIdentifier;



    /*
     * Audit sequence number
     */
	/**
	 *
	 */

    private long sequenceNumber;

	public StockAuditPK(){

	}
	public StockAuditPK(String companyCode,String stockHolderCode,String docType,
	String docSubType,int airlineId,long sequenceNumber){
		this.companyCode=companyCode;
        this.documentType = docType;
        this.documentSubType = docSubType;
        this.airlineIdentifier = airlineId;
        this.sequenceNumber=sequenceNumber;
	}
    /**
     * @param other
     * @return
     */
    public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).append(documentType).
		append(documentSubType).append(airlineIdentifier).append(sequenceNumber).
			toString().hashCode();
	}
	/**
	 * @return Returns the airlineIdentifier.
	 */
	@KeyCondition(column="ARLIDR")
	public int getAirlineIdentifier() {
		return airlineIdentifier;
	}
	/**
	 * @param airlineIdentifier The airlineIdentifier to set.
	 */
	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier = airlineIdentifier;
	}
	/**
	 * @return Returns the companyCode.
	 */
	@KeyCondition(column="CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the documentSubType.
	 */
	 @KeyCondition(column="DOCSUBTYP")
	public String getDocumentSubType() {
		return documentSubType;
	}
	/**
	 * @param documentSubType The documentSubType to set.
	 */
	public void setDocumentSubType(String documentSubType) {
		this.documentSubType = documentSubType;
	}
	/**
	 * @return Returns the documentType.
	 */
	 @KeyCondition(column="DOCTYP")
	public String getDocumentType() {
		return documentType;
	}
	/**
	 * @param documentType The documentType to set.
	 */
	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}
	/**
	 * @return Returns the sequenceNumber.
	 */
	@Key(generator="AUDSEQ_GEN",startAt="1")
	public long getSequenceNumber() {
		return sequenceNumber;
	}
	/**
	 * @param sequenceNumber The sequenceNumber to set.
	 */
	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:15 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(141);
		sbul.append("StockAuditPK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', documentSubType '").append(this.documentSubType);
		sbul.append("', documentType '").append(this.documentType);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
