/*
 * StockAirlineAuditPK.java Created on Oct 12, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.stockcontrol.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;


import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1954
 *
 */

@KeyTable(table="STKARLAUDKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="AUDSEQ_GEN",table="STKARLAUDKEY",key="STKARLAUD_SEQ")
@Embeddable
public class StockAirlineAuditPK implements Serializable {
	
	/**
	 * 
	 */
	
    private String companyCode;
	
	/**
	 * 
	 */
	
	private int airlineId;
	
	/**
	 * 
	 */
	
    private String stockHolderCode;

	/**
	 * 
	 */
	
	private String documentType;
	
	/**
	 * 
	 */
	
	private String documentSubType;

    /*
     * Audit sequence number
     */
	/**
	 * 
	 */
	
    private long sequenceNumber;

	/**
	 * 
	 */
	public StockAirlineAuditPK(){
		
	}
	
    /**
     * @param other
     * @return
     */
    public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).append(airlineId)
											.append(stockHolderCode)
											.append(documentType)
											.append(documentSubType)
											.append(sequenceNumber)
											.toString().hashCode();
	}

	/**
	 * @return Returns the airlineId.
	 */
	@KeyCondition(column="ARLIDR")
	public int getAirlineId() {
		return airlineId;
	}

	/**
	 * @param airlineId The airlineId to set.
	 */
	public void setAirlineId(int airlineId) {
		this.airlineId = airlineId;
	}

	/**
	 * @return Returns the companyCode.
	 */
	@KeyCondition(column="CMPCOD")
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * @return Returns the documentSubType.
	 */
	@KeyCondition(column="DOCSUBTYP")
	public String getDocumentSubType() {
		return documentSubType;
	}

	/**
	 * @param documentSubType The documentSubType to set.
	 */
	public void setDocumentSubType(String documentSubType) {
		this.documentSubType = documentSubType;
	}

	/**
	 * @return Returns the documentType.
	 */
	@KeyCondition(column="DOCTYP")
	public String getDocumentType() {
		return documentType;
	}

	/**
	 * @param documentType The documentType to set.
	 */
	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	/**
	 * @return Returns the sequenceNumber.
	 */
	@Key(generator="AUDSEQ_GEN",startAt="1")
	public long getSequenceNumber() {
		return sequenceNumber;
	}

	/**
	 * @param sequenceNumber The sequenceNumber to set.
	 */
	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	/**
	 * @return Returns the stockHolderCode.
	 */
	@KeyCondition(column="STKHLDCOD")
	public String getStockHolderCode() {
		return stockHolderCode;
	}

	/**
	 * @param stockHolderCode The stockHolderCode to set.
	 */
	public void setStockHolderCode(String stockHolderCode) {
		this.stockHolderCode = stockHolderCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:15 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(167);
		sbul.append("StockAirlineAuditPK [ ");
		sbul.append("airlineId '").append(this.airlineId);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', documentSubType '").append(this.documentSubType);
		sbul.append("', documentType '").append(this.documentType);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("', stockHolderCode '").append(this.stockHolderCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
