/*
 * StockRequestPK.java Created on Aug 25, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.stockcontrol.defaults;

import java.io.Serializable;


import javax.persistence.Embeddable;


/**
 * PK class for the StockRequest entity
 * @author A-1366
 */
 @Embeddable
public class StockRequestPK implements Serializable {

    /**
     * Company Code
     */
	// @KeyCondition(column="CMPCOD")
    private String companyCode;
    /**
     * Request Reference Number
     */
	// @KeyCondition(column="REQREFNUM")
    private String requestRefNumber;
    
    /**
     * Added by A-2589
     * for #102543
     */
    private Integer airlineIdentifier;

    /**
	 * return the hashcode corresponding to that product
	 * @return int
	 */
	 public int hashCode() {
		return new StringBuilder().append(companyCode)
			.append(requestRefNumber).append(airlineIdentifier).toString().hashCode();
	}
	 /**
	  * Compare two object and return boolean
	  * @param other
	  * @return boolean
	  */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * @return Returns the companyCode.
	 */
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the requestRefNumber.
	 */
	public String getRequestRefNumber() {
		return requestRefNumber;
	}
	/**
	 * @param requestRefNumber The requestRefNumber to set.
	 */
	public void setRequestRefNumber(String requestRefNumber) {
		this.requestRefNumber = requestRefNumber;
	}
	/**
	 * @return the airlineIdentifier
	 */
	public Integer getAirlineIdentifier() {
		return airlineIdentifier;
	}
	/**
	 * @param airlineIdentifier the airlineIdentifier to set
	 */
	public void setAirlineIdentifier(Integer airlineIdentifier) {
		this.airlineIdentifier = airlineIdentifier;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:15 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(94);
		sbul.append("StockRequestPK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', requestRefNumber '").append(this.requestRefNumber);
		sbul.append("' ]");
		return sbul.toString();
	}

}
