/*
 * BlackListStockPK.java Created on Sep 13, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of
 * IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.stockcontrol.defaults;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-4443
 *
 */

@KeyTable(table="STKTRSRNGKEY",keyColumn="KEYTYP",valueColumn="MAXSEQNUM")
@TableKeyGenerator(name="STKTRSRNG_GEN",table="STKTRSRNGKEY",key="STKTRSRNGKEY_SEQ")
@Embeddable
public class TransitStockPK implements Serializable {
    /**
     * company code
     */
    private String companyCode;
    /**
     *
     */
    private int airlineIdentifier;
    /**
     * document type
     */
    private String documentType;
    /**
     * document sub type
     */
    private String documentSubType;
    /**
     * Recepient Stock holder code
     */
    private String stockHolderCode;
    /**
     * 
     */
    private int sequenceNumber; 
    
    
    /**
     * Constructor
     *
     */
    public TransitStockPK(){

    }
    /**
     * @param other
     * @return
     */
    public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
    /**
     * @return int
     */
	public int hashCode() {
		return new StringBuffer(companyCode).append(documentType).
		append(documentSubType).append(stockHolderCode).append(sequenceNumber).
		append(airlineIdentifier).toString().hashCode();
	}
	/**
	 * @return Returns the airlineIdentifier.
	 */
	@KeyCondition(column="ARLIDR")
	public int getAirlineIdentifier() {
		return airlineIdentifier;
	}
	/**
	 * @param airlineIdentifier The airlineIdentifier to set.
	 */
	public void setAirlineIdentifier(int airlineIdentifier) {
		this.airlineIdentifier = airlineIdentifier;
	}
	/**
	 * @return Returns the companyCode.
	 */
	@KeyCondition(column="CMPCOD")
	public String getCompanyCode() {
		return companyCode;   
	}
	/**
	 * @param companyCode The companyCode to set.
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return Returns the documentSubType.
	 */
	@KeyCondition(column="DOCSUBTYP")
	public String getDocumentSubType() {
		return documentSubType;
	}
	/**
	 * @param documentSubType The documentSubType to set.
	 */
	public void setDocumentSubType(String documentSubType) {
		this.documentSubType = documentSubType;
	}
	/**
	 * @return Returns the documentType.
	 */
	@KeyCondition(column="DOCTYP")
	public String getDocumentType() {
		return documentType;
	}
	/**
	 * @param documentType The documentType to set.
	 */
	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}
	/**
	 * @return the sequenceNumber
	 */
	 @Key(generator="STKTRSRNG_GEN",startAt="1")
	public int getSequenceNumber() {
		return sequenceNumber;
	}
	/**
	 * @param sequenceNumber the sequenceNumber to set
	 */
	public void setSequenceNumber(int sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}
	/**
	 * @return the stockHolderCode
	 */
	@KeyCondition(column="STKHLDCOD")
	public String getStockHolderCode() {
		return stockHolderCode;
	}
	/**
	 * @param stockHolderCode the stockHolderCode to set
	 */
	public void setStockHolderCode(String stockHolderCode) {
		this.stockHolderCode = stockHolderCode;
	}
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:15 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(170);
		sbul.append("TransitStockPK [ ");
		sbul.append("airlineIdentifier '").append(this.airlineIdentifier);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', documentSubType '").append(this.documentSubType);
		sbul.append("', documentType '").append(this.documentType);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("', stockHolderCode '").append(this.stockHolderCode);
		sbul.append("' ]");
		return sbul.toString();
	}
	
}
