APP: 
  - 
    JAVA_HOME: /usr/lib/jvm/java-11-amazon-corretto
    M2: /opt/apache-maven-3.6.2/bin
    M2_HOME: /opt/apache-maven-3.6.2
    repo: "http://Icargo-release@bitbucket.ibsplc.com/scm/icneo/icargo-neo-devops-support.git"
    token: "f60d9763-39f7-4e73-8467-258d60f1d7f6"
    project_name: "neo-datamonitor"   
    service_name: neo-datamonitor
    release_url: http://10.250.3.242:5000/release-manager-service/rest/api/release/
