/*
 * CustomerServicesPK.java Created on jun 06, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.customermanagement.defaults.loyalty;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-2048
 */
@Embeddable
public class CustomerServicesPK implements Serializable{
	
	/**
	 *  company Code
	 */
	private String companyCode;
	/**
	 * serviceCode
	 */
	private String serviceCode;
	
	/**
	 * Default constructor
	 */
	public CustomerServicesPK() {
	}
	
	/**
	 * Contructor
	 *
	 * @param companyCode
	 * @param serviceCode
	 */
	public CustomerServicesPK(String companyCode, String serviceCode) {
		this.companyCode = companyCode;
		this.serviceCode = serviceCode;
	}
	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
		append(serviceCode).
		toString().hashCode();
	}
	
	

	public void setServiceCode(java.lang.String serviceCode) {
		this.serviceCode=serviceCode;
	}

	public java.lang.String getServiceCode() {
		return this.serviceCode;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:49 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(64);
		sbul.append("CustomerServicesPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', serviceCode '").append(this.serviceCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
