/*
 * LoyaltyProgrammePK.java Created on Aug 1, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.customermanagement.defaults.loyalty;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-1496
 */
@Embeddable
public class LoyaltyProgrammePK implements Serializable{
	
	/**
	 *  company Code
	 */
	private String companyCode;
	/**
	 * Loyalty Programme Code
	 */
	private String loyaltyProgrammeCode;
	
	/**
	 * Default constructor
	 */
	public LoyaltyProgrammePK() {
	}
	
	/**
	 * Contructor
	 *
	 * @param companyCode
	 * @param loyaltyProgrammeCode
	 * @param sequenceNumber
	 */
	public LoyaltyProgrammePK(String companyCode, String loyaltyProgrammeCode) {
		this.companyCode = companyCode;
		this.loyaltyProgrammeCode = loyaltyProgrammeCode;
	}
	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
		append(loyaltyProgrammeCode).
		toString().hashCode();
	}
	
	

	public void setLoyaltyProgrammeCode(java.lang.String loyaltyProgrammeCode) {
		this.loyaltyProgrammeCode=loyaltyProgrammeCode;
	}

	public java.lang.String getLoyaltyProgrammeCode() {
		return this.loyaltyProgrammeCode;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:49 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(73);
		sbul.append("LoyaltyProgrammePK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', loyaltyProgrammeCode '").append(
				this.loyaltyProgrammeCode);
		sbul.append("' ]");
		return sbul.toString();
	}
}
