/*
 * LoyaltyParameterPK.java Created on Aug 1, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.customermanagement.defaults.loyalty;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1496
 */
@Embeddable
@KeyTable(table = "CUSLTYPARMSTKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "CUSLTYPARMSTKEY", key = "MAX_SERNUM")
public class LoyaltyParameterPK implements Serializable {
	/**
	 * company code
	 */

	private String companyCode;
	/**
	 * loyalty Programme Code
	 */

	private String loyaltyProgrammeCode;
	/**
	 * parameter Code
	 */

	private String parameterCode;
	//Sequence to be generated based on above combination
	/**
	 * Sequence Number
	 */

	private String sequenceNumber;
	
	/**
	 * Default constructor
	 */
	public LoyaltyParameterPK() {
	}
	
/**
 * 
 * @param companyCode
 * @param loyaltyProgrammeCode
 * @param parameterCode
 * @param sequenceNumber
 */
	public LoyaltyParameterPK(String companyCode, String loyaltyProgrammeCode,
			String parameterCode, String sequenceNumber) {
		this.companyCode = companyCode;
		this.loyaltyProgrammeCode = loyaltyProgrammeCode;
		this.parameterCode = parameterCode;
		this.sequenceNumber = sequenceNumber;
		
	}
	/**
	 * @param other
	 * @return boolean
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
	/**
	 * @return int
	 */
	public int hashCode() {
		return new StringBuffer(companyCode).
		append(loyaltyProgrammeCode).
		append(parameterCode).
		append(sequenceNumber).
		toString().hashCode();
	}
	
	

	public void setSequenceNumber(java.lang.String sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public java.lang.String getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")   
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setLoyaltyProgrammeCode(java.lang.String loyaltyProgrammeCode) {
		this.loyaltyProgrammeCode=loyaltyProgrammeCode;
	}
	@KeyCondition(column = "LTYPRGCOD")   
	public java.lang.String getLoyaltyProgrammeCode() {
		return this.loyaltyProgrammeCode;
	}

	public void setParameterCode(java.lang.String parameterCode) {
		this.parameterCode=parameterCode;
	}
	@KeyCondition(column = "LTYPRGPAR")   
	public java.lang.String getParameterCode() {
		return this.parameterCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:13:49 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(124);
		sbul.append("LoyaltyParameterPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', loyaltyProgrammeCode '").append(
				this.loyaltyProgrammeCode);
		sbul.append("', parameterCode '").append(this.parameterCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
