awbParameters:

-   parameterCode :  EXGRATBAS
    parameterValue : F # 30D - 30 Days Average , 3M - 3 Months Average , F - Five Day Rate
    description : Exchange Rate Basis
-   parameterCode :  EXGRATDATBAS
    parameterValue : A # Flight Date (FL),AWB Execution Date( A)
    description : Exchange Rate date Basis