APP: 
  - 
    JAVA_HOME: /usr/lib/jvm/java-11-amazon-corretto
    M2: /opt/apache-maven-3.6.2/bin
    M2_HOME: /opt/apache-maven-3.6.2
    repo: "http://Icargo-release@bitbucket.ibsplc.com/scm/icneo/icargo-neo-mail.git"
    token: "f60d9763-39f7-4e73-8467-258d60f1d7f6"
    project_name: "icargo-neo-mail"
    sonar_host_url: "http://10.250.3.242:9000"
    sonar_projectkey_dev: "com.ibsplc.icargo:icargo-neo-mail-dev"
    sonar_projectkey_master: "com.ibsplc.icargo:icargo-neo-mail"
    sonar_password: "admin"
    sonar_user: "admin"
    sonar_project_name_dev: "icargo-neo-mail-dev"
    sonar_project_name_master: "icargo-neo-mailr"
    stop_script: "icargoadm@10.250.3.192 /home/icargoadm/deploy/deployMail/stop.sh"
    copy_script: "mail-business/target/neo-mail*.jar icargoadm@10.250.3.192:/home/icargoadm/deploy/deployMail"
    start_script: "icargoadm@10.250.3.192 /home/icargoadm/deploy/deployMail/start.sh"
    sonar_project_name_integrationtest: "icago-neo-mail-integrationTest"
    sonar_project_name_integrationtest_dev: "icago-neo-mail-integrationTest-Dev"
    sonar_projectkey_integrationtest: "com.ibsplc.icargo:icargo-neo-mail-integrationTest"
    sonar_projectkey_integrationtest_dev: "com.ibsplc.icargo:icargo-neo-mail-integrationTest-dev"
    integration_test_stage: false
    deploy_stage: true
    service_name: neo-mail-business
    release_url: http://10.250.3.242:5000/release-manager-service/rest/api/release/
