spring:
  cloud:
    config:
      import-check:
        enabled: false
  profiles: dev
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: '500'