EBL_URL: http://10.250.3.67:9052/bookings/v1/
EBL_URL_NBRIDGE: http://k8s-nginxalp-icargong-ed546127d1-89f64463d339106d.elb.ap-south-1.amazonaws.com/ebl-nbridge/v1/
QUALITY_AUDIT_URL: http://k8s-nginxalp-icargong-ed546127d1-89f64463d339106d.elb.ap-south-1.amazonaws.com/awb-qualityaudit/
EBL_LOGIN_URL: http://10.250.3.67:9050/v1/auth/token
LB_URL: k8s-nginxalp-icargong-ed546127d1-89f64463d339106d.elb.ap-south-1.amazonaws.com

NEO_KAFKA_URL: localhost:9092
NEO_REDIS_URL: 10.246.12.39:6379
NEO_OLTP_DB_URL: 10.246.13.8:5432

NEO_DATABASE: ico_neo_av_dev
NEO_DB_SCHEMA: ico_av_usr
NEO_DB_USERNAME: ico_av_usr
NEO_DB_PASSWORD: ico_av_usr

debug: true
logging:
  level:
    com.ibsplc: INFO
    com.ibsplc.neoicargo.cca: DEBUG
    com.ibsplc.neoicargo.framework.tenant.jaxrs.cxf: WARN
    liquibase: INFO
    org.hibernate: INFO
    org.mybatis: INFO
    com.zaxxer.hikari: INFO
    io.swagger: INFO
    org.apache.kafka.clients: WARN
server:
  port: 6090
  servlet:
    context-path: /cca

# Neo
neo:
  component-scan:
    basePackages: "com.ibsplc.neoicargo.masters,com.ibsplc.neoicargo.booking,com.ibsplc.neoicargo.cca,com.ibsplc.neoicargo.pricing,com.ibsplc.neoicargo.businessrules,com.ibsplc.neoicargo.framework.cqrs, org.springframework.boot.autoconfigure.mustache"
  defaults:
    oltp:
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 1800000
      connection-timeout: 30000
      idle-timeout: 600000
      leak-detection-threshold: 30000
  logging:
    root-level: DEBUG
    appenders: console
  security:
    token-service:
      token-validity-hours: 10
    system:
      authtype: ebl
      ebl:
        grant_type: password
        password: weblogic
        username: ICOADMIN
  jaxrs.client.service-bindings:
    - name: auth-service
      address: http://${LB_URL}/auth
      basePath: /private
    - name: neo-masters-business
      address: http://${LB_URL}/masters
      basePath: /private
    - name: neo-masters-api
      address: http://${LB_URL}/masters
      basePath: /private
    - name: pricing-service
      address: http://${LB_URL}/pricing
      basepath: /private
    - name: neo-admin-business
      address: http://${LB_URL}/admin
      basePath: /private
    - name: neo-booking-business
      address: http://${LB_URL}/awb-booking
      basepath: /private
    - name: neo-businessrules-business
      address: http://${LB_URL}/businessrules
      basePath: /private
  reports:
    report-bindings:
      - report-id: CCA001
        report-name: Cargo Charge Correction
        report-category: JASPERREPORT
        report-jrxml-file: config/reports/CCAPrint.jrxml
  cqrs:
    component-scan:
      basePackages: "com.ibsplc.neoicargo.bookingcqrs,com.ibsplc.neoicargo.awbcqrs"
    streams-application-id: ${com.ibsplc.neoicargo.tenant}-${spring.application.name}
    kafka-bootstrap-servers: ${NEO_KAFKA_URL}
    hierarchical-aggregation: true
    suppression-window: 2000
    dummy-event-worker-to-force-suppression-enabled: true
    dummy-event-worker-frequency: 2000
    server-name: icargoneo
    schema-name: ${NEO_DB_SCHEMA}
    jpa:
      database: postgresql
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc.lob.non_contextual_creation: true
          format_sql: true
    liquibase:
      enabled: true
      change-log: classpath:/config/db.changelog-cqrs.yaml
    datasource:
      name: ${NEO_DATABASE}_cqrs
      platform: postgres
      password: ${NEO_DB_PASSWORD}
      username: ${NEO_DB_USERNAME}
      url: jdbc:postgresql://${NEO_OLTP_DB_URL}/${NEO_DATABASE}_cqrs
      type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: ${neo.defaults.oltp.maximum-pool-size}
      minimum-idle: ${neo.defaults.oltp.minimum-idle}
      max-lifetime: ${neo.defaults.oltp.max-lifetime}
      connection-timeout: ${neo.defaults.oltp.connection-timeout}
      idle-timeout: ${neo.defaults.oltp.idle-timeout}
      leak-detection-threshold: ${neo.defaults.oltp.leak-detection-threshold}
    mybatis:
      config-location: classpath:config/cqrs-mybatis/MyBatis_Configuration.xml
      mapper-locations: classpath:config/cqrs-mybatis/mappers/*.xml

# Spring
spring:
  application:
    name: "neo-cca-business"

  main:
    allow-bean-definition-overriding: true

  cloud:
    service-registry:
      auto-registration:
        enabled: false
    stream:
      bindings:
        AWB_EVENT_CHANNEL_IN:
          destination: ${com.ibsplc.neoicargo.tenant}-awb-domain-events
          content-type: application/json
        CCA_EVENT_CHANNEL_OUT:
          destination: ${com.ibsplc.neoicargo.tenant}-cca-domain-events
          content-type: application/json
      kafka:
        binder:
          brokers: ${NEO_KAFKA_URL}
          headers: messageType
        bindings:
          CCA_EVENT_CHANNEL_OUT:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
          AWB_EVENT_CHANNEL_IN:
            consumer:
              configuration:
                key:
                  deserialiser: org.apache.kafka.common.serialization.StringDeserializer

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/config/db.changelog-master.yaml
  datasource:
    platform: postgres
    username: ${NEO_DB_USERNAME}
    password: ${NEO_DB_PASSWORD}
    url: jdbc:postgresql://${NEO_OLTP_DB_URL}/${NEO_DATABASE}_cca?currentSchema=${NEO_DB_SCHEMA}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: ${neo.defaults.oltp.maximum-pool-size}
      minimum-idle: ${neo.defaults.oltp.minimum-idle}
      max-lifetime: ${neo.defaults.oltp.max-lifetime}
      connection-timeout: ${neo.defaults.oltp.connection-timeout}
      idle-timeout: ${neo.defaults.oltp.idle-timeout}
      leak-detection-threshold: ${neo.defaults.oltp.leak-detection-threshold}

mybatis:
  config-location: classpath:config/mybatis/MyBatis_Configuration.xml
  mapper-locations: classpath:config/mybatis/mappers/*.xml

pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  offset-as-page-num: true

management:
  endpoints:
    web:
      exposure:
        include: '*'