databaseChangeLog:
  - include:
      file: changelog/IAN-35824_MSM27192.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-35824_MSM27193.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-35824_MSM27194.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-35824_MSM27195.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-35824_MSM27196.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-35824_MSM27197.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-35824_MSM27198.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-35824_MSM27199.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-35824_MSM27200.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-35824_MSM27283.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-35824_MSM27284.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-36807_MSM27337.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-36807_MSM27338.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-4645_MSM27900.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-15360_MSM27915.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-39612_MSM27954.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-41063_MSM28021.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-17150_MSM28052.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-17150_MSM28051.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-40939_MSM28105.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-4661_MSM28223.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-4610_MSM28217.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-4610_MSM28218.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-44352_MSM28316.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-44968_MSM28403.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-44968_MSM28404.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-44968_MSM28410.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-4605_MSM28447.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-4605_MSM28448.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-4605_MSM28449.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-4605_MSM28502.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-4605_MSM28503.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-46178_MSM28514.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-46178_MSM28515.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-46178_MSM28516.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-46178_MSM28517.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-46312_MSM28521.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-46677_MSM28577.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-46677_MSM28578.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-15521_MSM28632.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN_15521_MSM28656.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-47076_MSM28709.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-15043_MSM28674.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-15043_MSM28716.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-15043_MSM28721.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-49435_MSM28997.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-54559_MSM29615.yaml
      relativeToChangelogFile: true