server:
  port: 6090
  servlet:
    context-path: /mail
neo:
  component-scan:
    basePackages: "com.ibsplc.neoicargo.mail,com.ibsplc.neoicargo.masters,com.ibsplc.neoicargo.mailmasters,com.ibsplc.neoicargo.awb"
  security:
    system:
      authtype: ebl
      ebl:
        grant_type: password
        password: weblogic
        username: ICOADMIN
    tokenService:
      tokenValidityHours: 10
  logging:
    appenders: console # comma separated list of appenders to be added, supported values are console,tcp,udp
    root-level: INFO       # root logger level
    udp:
      host: 10.250.3.92    # the hostname of the logstash server
      port: 3000           # udp port

  jaxrs:
    client:
      serviceBindings:
        - name: neo-masters-business
          address: >-
            http://k8s-k8snginx-k8snginx-6eb453cc8e-96c04f4af40467c9.elb.ap-south-1.amazonaws.com/masters
          basePath: /private
        - name: auth-service
          address: >-
            http://k8s-k8snginx-k8snginx-6eb453cc8e-96c04f4af40467c9.elb.ap-south-1.amazonaws.com/auth
          basePath: /private
        - name: neo-mailmasters-business
          address: >-
            http://k8s-k8snginx-k8snginx-6eb453cc8e-96c04f4af40467c9.elb.ap-south-1.amazonaws.com/mailmasters
          basePath: /private
        - name: neo-awb-business
          address: >-
            http://k8s-k8snginx-k8snginx-6eb453cc8e-96c04f4af40467c9.elb.ap-south-1.amazonaws.com/awb
          basePath: /private

EBL_URL: 'http://10.250.3.67:9052/bookings/v1/'
EBL_URL_NBRIDGE: 'http://k8s-nginxalp-icargong-ed546127d1-89f64463d339106d.elb.ap-south-1.amazonaws.com/ebl-nbridge/v1/'
EBL_LOGIN_URL: 'http://10.250.3.67:9050/v1/auth/token'

debug: true
logging:
  level:
    liquibase: INFO
spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    stream:
      bindings:
        MAIL_EVENT_CHANNEL_IN:
          destination: ${com.ibsplc.neoicargo.tenant}-mail-domain-events
          content-type: application/json
        MAIL_EVENT_CHANNEL_OUT:
          destination: ${com.ibsplc.neoicargo.tenant}-mail-domain-events
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
          headers: messageType
        bindings:
          MAIL_EVENT_CHANNEL_OUT:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
          MAIL_EVENT_CHANNEL_IN:
            consumer:
              configuration:
                key:
                  deserialiser: org.apache.kafka.common.serialization.StringDeserializer

  application:
    name: "icargo-neo-mail-business"
  jpa:
    database: POSTGRESQL
    hibernate:
      naming:
        implicit-strategy: >-
          org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    enabled: false
    change-log: classpath:/config/changelog/db.changelog-mail.yaml
  datasource:
    password: ico_ibs_usr
    platform: postgres
    url: 'jdbc:postgresql://10.246.13.21:5432/ico_ibs_alpha'
    username: ico_ibs_usr
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      leakDetectionThreshold: 800000
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 1
databaseChangeLog:
  - preConditions:
      - runningAs:
          username: sa
management:
  endpoints:
    web:
      exposure:
        include: '*'
icargo:
  persistence:
    mail.operations:
      queryXml: classpath:/config/mail-operations-query.xml
      daoClass: com.ibsplc.neoicargo.mail.dao.MailOperationsSqlDAO
      objectDaoClass: com.ibsplc.neoicargo.mail.component.MailOperationsObjectDAO
  companyCode: IBS
  dummyauth: false
  http:
    host: localhost
    port: 7001
    contextPath: icargo
    webserviceRoot: webservices
    eblWebContextPath: icargo-ebl
  webservice:
    auth:
      username: SYSADMIN
      password: weblogic
      anonymousSessionId: >-
        aWNTZXNzaW9uSWQ6SFhQZnVnJTJCUU1INWRwUFV4OWJ6dVZDdkNtbzAlMkZXRzBVOGdsbFNLN2F6YzhhTXhaUVNmYWhabFZ2TXUyaEZhRkZNTm8yOUJIZ3lUbmUlMEQlMEFhenVVRXk2MHBRJTNEJTNE
  jndi:
    providerURL: null
    user: null
    password: null