databaseChangeLog:
  - include:
      file: changelog/IAN-73313_MSM32513.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-73241_MSM32526.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-73246_MSM32515.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-77702_MSM32527.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-73246_MSM32510.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-73246_MSM32516.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-77702_MSM32511.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-76204_MSM32499.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-76204_MSM32503.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-73313_MSM32519.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-73313_MSM32520.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-73313_MSM32521.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-74329_MSM32514.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-76204_MSM32541.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-73263_MSM32573.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-73263_MSM32524.yml
      relativeToChangelogFile: true
  - include:
      file: changelog/IAN-76204_MSM32643.yml
      relativeToChangelogFile: true