databaseChangeLog:
  - logicalFilePath: classpath:/config/changelog/IAN-54749_MSM011.yml
  - changeSet:
      id: STK_020
      author: 201132
      preConditions:
        - onFail: MARK_RAN
        - not:
            sequenceExists:
              sequenceName: STKREQMST_SEQ
      changes:
        dbms: postgres
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE SEQUENCE STKREQMST_SEQ
          START WITH 1
          INCREMENT BY 1
          MINVALUE 1
          MAXVALUE 9223372036854775807
          CACHE 1;

  - changeSet:
      id: STK_021
      author: 201132
      preConditions:
        - onFail: MARK_RAN
        - not:
            tableExists:
              tableName: STKREQMST
      changes:
        dbms: postgres
        endDelimiter: \nGO
        splitStatements: false
        sql: CREATE TABLE STKREQMST(
                  STKREQMSTSERNUM BIGINT,
                  CMPCOD VARCHAR(6) NOT NULL,
                  REQREFNUM VARCHAR(20) NOT NULL,
                  STKHLDCOD VARCHAR(15) NOT NULL,
                  REQDAT DATE NOT NULL,
                  DOCTYP VARCHAR(10) NOT NULL,
                  DOCSUBTYP VARCHAR(15) NOT NULL,
                  MNLSTKFLG VARCHAR(1) DEFAULT 'N',
                  REQSTKQTY NUMERIC,
                  APRSTKQTY NUMERIC,
                  ALCSTKQTY NUMERIC,
                  REQRMK VARCHAR(250),
                  APRREJREM VARCHAR(250),
                  REQSTA VARCHAR(1) NOT NULL,
                  LSTUPDTIM TIMESTAMP NOT NULL,
                  LSTUPDUSR VARCHAR(50) NOT NULL,
                  ARLIDR NUMERIC,
                  TAGIDX NUMERIC(1,0) DEFAULT 0 NOT NULL,
                  REQCRTUSR VARCHAR(50),
                  CONSTRAINT "stkreqmst_pk" PRIMARY KEY (STKREQMSTSERNUM),
                  CONSTRAINT "stkreqmst_cmpcod_reqrefnum" UNIQUE (CMPCOD, REQREFNUM));

                  COMMENT ON COLUMN STKREQMST.STKREQMSTSERNUM IS 'Serial number';
                  COMMENT ON COLUMN STKREQMST.CMPCOD IS 'Company Code.The company code that uniquely identifies the company for which the application is hosted';
                  COMMENT ON COLUMN STKREQMST.REQREFNUM IS 'Request reference number';
                  COMMENT ON COLUMN STKREQMST.STKHLDCOD IS 'stock holder code';
                  COMMENT ON COLUMN STKREQMST.REQDAT IS 'Request Date';
                  COMMENT ON COLUMN STKREQMST.DOCTYP IS 'Document type';
                  COMMENT ON COLUMN STKREQMST.DOCSUBTYP IS 'Document sub type';
                  COMMENT ON COLUMN STKREQMST.MNLSTKFLG IS 'Manual stock flag';
                  COMMENT ON COLUMN STKREQMST.REQSTKQTY IS 'Requested stock';
                  COMMENT ON COLUMN STKREQMST.APRSTKQTY IS 'Approved stock quantity';
                  COMMENT ON COLUMN STKREQMST.ALCSTKQTY IS 'Allocated stock quantity';
                  COMMENT ON COLUMN STKREQMST.REQRMK IS 'request remarks';
                  COMMENT ON COLUMN STKREQMST.APRREJREM IS 'approval reject remarks';
                  COMMENT ON COLUMN STKREQMST.REQSTA IS 'request status';
                  COMMENT ON COLUMN STKREQMST.LSTUPDTIM IS 'The date and time at which record was last updated';
                  COMMENT ON COLUMN STKREQMST.LSTUPDUSR IS 'Last Update User.The application user code who performed the operation on the record';
                  COMMENT ON COLUMN STKREQMST.ARLIDR IS 'Airline to which stock belongs';
                  COMMENT ON COLUMN STKREQMST.TAGIDX IS 'This column will be used as workaround for the tag setting feature of CDC in its low cost replacement. The value 1 indicate that the records are tagged and will not transferred to the target in a CDC environment';
                  COMMENT ON COLUMN STKREQMST.REQCRTUSR IS 'User who requested for stock request';
                  COMMENT ON TABLE STKREQMST  IS 'Stock request master';
                  
