/*
 * ULDAirportLocationPK.java Created on jul 13, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information 
 * of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.misc;

import java.io.Serializable;
import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-2048
 * 
 */
@KeyTable(table = "ULDARPLOCKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "ULDARPLOCKEY", key = "SEQNUM")
@Embeddable
public class ULDAirportLocationPK implements Serializable {
	/**
	 * companyCode
	 */

	private String companyCode;

	/**
	 * movementSequenceNumber
	 */

	private String airportCode;
	/**
	 * 
	 */

	private String facilityType;
	/**
	 * 
	 */

	private String sequenceNumber;

	

	/**
	 * Constructor
	 * 
	 */
	public ULDAirportLocationPK() {

	}

	/**
	 * 
	 * @param companyCode
	 * @param airportCode
	 * @param facilityType
	 * @param sequenceNumber
	 */
	public ULDAirportLocationPK(String companyCode,
			String airportCode,
			String facilityType,
			String sequenceNumber) {
		this.companyCode = companyCode;
		this.airportCode = airportCode;
		this.facilityType = facilityType;
		this.sequenceNumber = sequenceNumber;
		
	}

	/**
	 * 
	 * @param other 
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode)
		                          .append(airportCode)
		                          .append(facilityType)
		                          .append(sequenceNumber)
		                          .toString().hashCode();
	}

	public void setSequenceNumber(java.lang.String sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public java.lang.String getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setFacilityType(java.lang.String facilityType) {
		this.facilityType=facilityType;
	}
	@KeyCondition(column = "FACTYP")
	public java.lang.String getFacilityType() {
		return this.facilityType;
	}

	public void setAirportCode(java.lang.String airportCode) {
		this.airportCode=airportCode;
	}
	@KeyCondition(column = "ARPCOD")
	public java.lang.String getAirportCode() {
		return this.airportCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:17 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(116);
		sbul.append("ULDAirportLocationPK [ ");
		sbul.append("airportCode '").append(this.airportCode);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', facilityType '").append(this.facilityType);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
