/*
 * ULDAgreementDetailsPK.java Created on Aug 1, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.misc;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * 
 * 
 * @author A-1496
 *
 */
@KeyTable(table = "ULDAGRMNTDTLKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "ULDAGRMNTDTLKEY", key = "MAX_SERNUM")
@Embeddable
public class ULDAgreementDetailsPK implements Serializable {
    /**
     * Company Code
     */

    private String companyCode;
	/**
	 * Agreement Number
	 */

    private String agreementNumber;
	/**
	 * Sequence Number
	 */

    private int sequenceNumber;
    
    /**
     * Default constructor
     */
	public ULDAgreementDetailsPK() {
	}

	/**
	 * Contructor
	 * 
	 * @param companyCode
	 * @param agreementNumber
	 * @param sequenceNumber
	 */
    public ULDAgreementDetailsPK(
    	String companyCode, String agreementNumber,
    	int sequenceNumber) {
    	this.companyCode = companyCode;
    	this.agreementNumber = agreementNumber;
    	this.sequenceNumber = sequenceNumber;
	}
    /**
     * @param other
     * @return boolean 
     */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
/**
 * @return int
 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).
				append(agreementNumber).
				append(sequenceNumber).
				toString().hashCode();
	}    



	public void setSequenceNumber(int sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public int getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setAgreementNumber(java.lang.String agreementNumber) {
		this.agreementNumber=agreementNumber;
	}
	@KeyCondition(column = "AGRMNTNUM")    
	public java.lang.String getAgreementNumber() {
		return this.agreementNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")    
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:17 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(97);
		sbul.append("ULDAgreementDetailsPK [ ");
		sbul.append("agreementNumber '").append(this.agreementNumber);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
