/*
 * ULDDiscrepancyPK.java Created on Dec 21, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.misc;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1347
 * 
 */
@KeyTable(table = "ULDDISNUMKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "ULDDISNUMKEY", key = "MAX_SERNUM")
@Embeddable
public class ULDDiscrepancyPK implements Serializable {
	
	/**
	 *  
	 */
	private String companyCode;

	/**
	 * 
	 */
	private String uldNumber;
	
	
	
	private long sequenceNumber;
	
	
	
	
	
	

	/**
	 * 
	 * Constructor
	 */
	public ULDDiscrepancyPK() {
	}

	/**
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(uldNumber).append(sequenceNumber)
				.toString().hashCode();
	}
	
	@KeyCondition(column = "CMPCOD")     
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	
	
	@KeyCondition(column = "ULDNUM") 
	public java.lang.String getUldNumber() {
		return this.uldNumber;
	}
	public void setUldNumber(java.lang.String uldNumber) {
		this.uldNumber=uldNumber;
	}

	
	@Key(generator = "ID_GEN", startAt = "1")
	public long getSequenceNumber() {
		return sequenceNumber;
	}
	public void setSequenceNumber(long sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:17 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(86);
		sbul.append("ULDDiscrepancyPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("', uldNumber '").append(this.uldNumber);
		sbul.append("' ]");
		return sbul.toString();
	}

	
}
