/*
 * ULDDamageChecklistMasterPK.java Created on May 5, 2008
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.misc;

import java.io.Serializable;
import javax.persistence.Embeddable;
import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-3459
 *
 */
@KeyTable(table = "ULDDMGCHKLSTKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "ULDDMGCHKLSTKEY", key = "ULDDMGCHKLSTSEQNUM")
@Embeddable
public class ULDDamageChecklistMasterPK implements Serializable{
	
	/**
	 * 
	 */

    private String companyCode;
	
	/**
	 * 
	 */

	private String section;
	
	/**
	 * 
	 */

    private String sequenceNumber;
    
    /**
     * Default constructor
     */
	public ULDDamageChecklistMasterPK() {
		
	}

	/**
	 * 
	 * @param companyCode
	 * @param section
	 * @param sequenceNumber
	 */
    public ULDDamageChecklistMasterPK(
    	String companyCode,
    	String section,
    	String sequenceNumber) {
    	this.companyCode = companyCode;
    	this.section =section;
    	this.sequenceNumber = sequenceNumber;
	}
	
    /**
     * @param other 
     * @return 
     * 
     */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
    /**
     * @return 
     * 
     */
	public int hashCode() {
		return new StringBuilder().append(companyCode).
				append(section).
				append(sequenceNumber).
				toString().hashCode();
	}  
	/**
	 * @param sequenceNumber the sequenceNumber to set
	 */
	public void setSequenceNumber(String sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	/**
	 * @return the sequenceNumber
	 */
	@Key(generator = "ID_GEN", startAt = "1")
	public String getSequenceNumber() {
		return this.sequenceNumber;
	}

	/**
	 * @return the companyCode
	 */
	@KeyCondition(column = "CMPCOD")   
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * @param companyCode the companyCode to set
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * @return the section
	 */
	@KeyCondition(column = "SEC")  
	public String getSection() {
		return section;
	}

	/**
	 * @param section the section to set
	 */
	public void setSection(String section) {
		this.section = section;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:17 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(94);
		sbul.append("ULDDamageChecklistMasterPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', section '").append(this.section);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
	
}
