/*
 * ULDMovementDetailPK.java Created on Dec 21, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information 
 * of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.misc;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-1347
 * 
 */
@KeyTable(table = "ULDMVTKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "ULDMVTKEY", key = "MVTSEQNUM")
@Embeddable
public class ULDMovementDetailPK implements Serializable {
	/**
	 * companyCode
	 */

	private String companyCode;

	/**
	 * movementSequenceNumber
	 */

	private long movementSequenceNumber;

	/**
	 * uldNumber
	 */

	private String uldNumber;

	
	/**
	 * movementSerialNumber
	 */

	private long movementSerialNumber;

	/**
	 * Constructor
	 * 
	 */
	public ULDMovementDetailPK() {

	}

	/**
	 * 
	 * @param companyCode
	 * @param movementSequenceNumber
	 */
	public ULDMovementDetailPK(String companyCode, long movementSequenceNumber,String uldNumber) {
		this.companyCode = companyCode;
		this.movementSequenceNumber = movementSequenceNumber;
		this.uldNumber=uldNumber;
	}

	/**
	 * 
	 * @param other 
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(
				movementSequenceNumber).append(uldNumber).append(movementSerialNumber).toString()
				.hashCode();
	}

	public void setMovementSequenceNumber(long movementSequenceNumber) {
		this.movementSequenceNumber=movementSequenceNumber;
	}
	@KeyCondition(column = "MVTSEQNUM")
	public long getMovementSequenceNumber() {
		return this.movementSequenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setMovementSerialNumber(long movementSerialNumber) {
		this.movementSerialNumber=movementSerialNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public long getMovementSerialNumber() {
		return this.movementSerialNumber;
	}

	public java.lang.String getUldNumber() {
		return uldNumber;
	}

	public void setUldNumber(java.lang.String uldNumber) {
		this.uldNumber = uldNumber;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:17 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(129);
		sbul.append("ULDMovementDetailPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', movementSequenceNumber '").append(
				this.movementSequenceNumber);
		sbul.append("', movementSerialNumber '").append(
				this.movementSerialNumber);
		sbul.append("', uldNumber '").append(this.uldNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
