/*
 * ULDMovementPK.java Created on Dec 21, 2005
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.misc;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * @author A-1347
 * 
 */
@Embeddable
public class ULDMovementPK implements Serializable {
	/**
	 * The companyCode
	 */
	private String companyCode;

	/**
	 * ULDNumber
	 */
	private String uldNumber;

	/**
	 * movementsequenceNumber
	 */
	private long movementSequenceNumber;

	/**
	 * 
	 * Constructor
	 */
	public ULDMovementPK() {

	}

	/***************************************************************************
	 * 
	 * @param companyCode
	 * @param uldNumber
	 * @param movementSequenceNumber
	 */
	public ULDMovementPK(String companyCode, String uldNumber,
			long movementSequenceNumber) {
		this.companyCode = companyCode;
		this.uldNumber = uldNumber;
		this.movementSequenceNumber = movementSequenceNumber;
	}

	/**
	 * @param other
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).append(uldNumber)
				.append(movementSequenceNumber).toString().hashCode();
	}


	public void setMovementSequenceNumber(long movementSequenceNumber) {
		this.movementSequenceNumber=movementSequenceNumber;
	}

	public long getMovementSequenceNumber() {
		return this.movementSequenceNumber;
	}

	public void setUldNumber(java.lang.String uldNumber) {
		this.uldNumber=uldNumber;
	}

	public java.lang.String getUldNumber() {
		return this.uldNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:18 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(91);
		sbul.append("ULDMovementPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', movementSequenceNumber '").append(
				this.movementSequenceNumber);
		sbul.append("', uldNumber '").append(this.uldNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
