/*
 * ULDPoolOwnerDetailsPK.java Created on AUG 11,2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.misc;

import java.io.Serializable;
import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * 
 * 
 * @author A-1496
 *
 */
@KeyTable(table = "ULDPOLOWNDTLKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "ULDPOLOWNDTLKEY", key = "MAX_POLSEQNUM")
@Embeddable
public class ULDPoolOwnerDetailsPK implements Serializable {
    /**
     * Company Code
     */

    private String companyCode;
	/**
	 * 
	 */

	private int flightCarrierIdentifier;
	
	/**
	 * 
	 */

    private String sequenceNumber;
	/**
	 * polSequence Number
	 */

    private String polSequenceNumber;
    
    /**
     * Default constructor
     */
	public ULDPoolOwnerDetailsPK() {
	}

	/**
	 * 
	 * @param companyCode
	 * @param flightCarrierIdentifier
	 * @param sequenceNumber
	 * @param polSsequenceNumber
	 */
    public ULDPoolOwnerDetailsPK(
    	String companyCode,int flightCarrierIdentifier,
    	String sequenceNumber,
    	String polSequenceNumber) {
    	this.companyCode = companyCode;
    	this.flightCarrierIdentifier = flightCarrierIdentifier;
    	this.sequenceNumber = sequenceNumber;
    	this.polSequenceNumber = polSequenceNumber;
	}
    /**
     * @param other
     * @return boolean 
     */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
/**
 * @return int
 */
	public int hashCode() {
		return new StringBuilder().append(companyCode).
				append(flightCarrierIdentifier).
				append(sequenceNumber).
				append(polSequenceNumber).				
				toString().hashCode();
	}    



	public void setFlightCarrierIdentifier(int flightCarrierIdentifier) {
		this.flightCarrierIdentifier=flightCarrierIdentifier;
	}
	@KeyCondition(column = "FLTCARIDR")    
	public int getFlightCarrierIdentifier() {
		return this.flightCarrierIdentifier;
	}

	public void setSequenceNumber(java.lang.String sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	@KeyCondition(column = "SEQNUM")    
	public java.lang.String getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setPolSequenceNumber(java.lang.String polSequenceNumber) {
		this.polSequenceNumber=polSequenceNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public java.lang.String getPolSequenceNumber() {
		return this.polSequenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")    
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:18 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(134);
		sbul.append("ULDPoolOwnerDetailsPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', flightCarrierIdentifier '").append(
				this.flightCarrierIdentifier);
		sbul.append("', polSequenceNumber '").append(this.polSequenceNumber);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
