/*
 * ULDPoolOwnerPK.java Created on Aug 11, 2006
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.misc;

import java.io.Serializable;

import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * 
 * 
 * @author A-1496
 *
 */

@KeyTable(table = "ULDPOLOWNKEY", keyColumn = "KEYTYP", valueColumn = "SERNUM")
@TableKeyGenerator(name = "ID_GEN", table = "ULDPOLOWNKEY", key = "ULDPOLOWNSERNUM")
@Embeddable
public class ULDPoolOwnerPK implements Serializable {
    
	/**
	 * company code
	 */

    private String companyCode;
	
	/**
	 * airlineIdentifierOne
	 */

	private int airlineIdentifierOne;
	
	/**
	 * airlineIdentifierTwo
	 */

    private int airlineIdentifierTwo;
    
    
    private long serialNumber;   
    /**
	 * airport
	 */

    //private String airport;
    /**
     * Default constructor
     */
	/*public ULDPoolOwnerPK() {
	}*/

	/**
	 * 
	 * @param companyCode
	 * @param airlineIdentifierOne
	 * @param airlineIdentifierTwo
	 * @param airport
	 */
   /* public ULDPoolOwnerPK(
    	String companyCode,
    	int airlineIdentifierOne,
    	int airlineIdentifierTwo,String airport) {
    	this.companyCode = companyCode;
    	this.airlineIdentifierOne =airlineIdentifierOne;
    	this.airlineIdentifierTwo =airlineIdentifierTwo;
    	
    	//this.airport =airport;
    }*/
    /**
     * @param other 
     * @return 
     * 
     */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}
    /**
     * @return 
     * 
     */
	public int hashCode() {
		return new StringBuilder().append(companyCode).
				append(airlineIdentifierTwo).
				append(airlineIdentifierTwo).
				//append(airport).
				append(serialNumber).
				toString().hashCode();
	}  

	/**
	 * @param companyCode the companyCode to set
	 */
	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	/**
	 * @return the companyCode
	 */
	
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}
	/**
	 * @return the airport
	 */
	//@KeyCondition(column = "ARPCOD")
/*	public String getAirport() {
		return airport;
	}
*/
	/**
	 * @param airport the airport to set
	 */
	/*public void setAirport(String airport) {
		this.airport = airport;
	}*/
	
	public void setSerialNumber(long serialNumber) {
		this.serialNumber=serialNumber;
	}
	
    @Key(generator = "ID_GEN", startAt = "1")
	public long getSerialNumber() {
		return this.serialNumber;
	}

	/**
	 * @return the airlineIdentifierOne
	 */
	@KeyCondition(column = "ARLONE")
	public int getAirlineIdentifierOne() {
		return airlineIdentifierOne;
	}

	/**
	 * @param airlineIdentifierOne the airlineIdentifierOne to set
	 */
	public void setAirlineIdentifierOne(int airlineIdentifierOne) {
		this.airlineIdentifierOne = airlineIdentifierOne;
	}

	/**
	 * @return the airlineIdentifierTwo
	 */
	@KeyCondition(column = "ARLTWO")
	public int getAirlineIdentifierTwo() {
		return airlineIdentifierTwo;
	}

	/**
	 * @param airlineIdentifierTwo the airlineIdentifierTwo to set
	 */
	public void setAirlineIdentifierTwo(int airlineIdentifierTwo) {
		this.airlineIdentifierTwo = airlineIdentifierTwo;
	}

	
	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:18 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(120);
		sbul.append("ULDPoolOwnerPK [ ");
		sbul.append("airlineIdentifierOne '").append(this.airlineIdentifierOne);
		sbul.append("', airlineIdentifierTwo '").append(
				this.airlineIdentifierTwo);
		//sbul.append("', airport '").append(this.airport);
		sbul.append("', serialNumber '").append(this.serialNumber);
		sbul.append("', companyCode '").append(this.companyCode);
		sbul.append("' ]");
		return sbul.toString();
	}

}
