/*
 * ULDAirportLocationPK.java Created on Sep 01, 2010
 *
 * Copyright 2005 IBS Software Services (P) Ltd. All Rights Reserved.
 *
 * This software is the proprietary information 
 * of IBS Software Services (P) Ltd.
 * Use is subject to license terms.
 */
package com.ibsplc.icargo.business.uld.defaults.misc;

import java.io.Serializable;
import javax.persistence.Embeddable;

import com.ibsplc.xibase.server.framework.persistence.keygen.Key;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyCondition;
import com.ibsplc.xibase.server.framework.persistence.keygen.KeyTable;
import com.ibsplc.xibase.server.framework.persistence.keygen.TableKeyGenerator;

/**
 * @author A-2048
 * 
 */
@KeyTable(table = "ULDSRVMSTKEY", keyColumn = "KEYTYP", valueColumn = "MAXSEQNUM")
@TableKeyGenerator(name = "ID_GEN", table = "ULDSRVMSTKEY", key = "SEQNUM")
@Embeddable
public class ULDServiceabilityPK implements Serializable {
	/**
	 * companyCode
	 */

	private String companyCode;

	/**
	 * 
	 */

	private String partyType;
	/**
	 * 
	 */

	private String sequenceNumber;

	

	/**
	 * Constructor
	 * 
	 */
	public ULDServiceabilityPK() {

	}

	/**
	 * 
	 * @param companyCode
	 * @param partyType
	 * @param sequenceNumber
	 */
	public ULDServiceabilityPK(String companyCode,			
			String partyType,
			String sequenceNumber) {
		this.companyCode = companyCode;
		this.partyType = partyType;
		this.sequenceNumber = sequenceNumber;		
	}

	/**
	 * 
	 * @param other 
	 * @return
	 */
	public boolean equals(Object other) {
		return (other != null) && ((hashCode() == other.hashCode()));
	}

	/**
	 * @return
	 */
	public int hashCode() {
		return new StringBuilder().append(companyCode)
		                          .append(partyType)
		                          .append(sequenceNumber)
		                          .toString().hashCode();
	}

	public void setSequenceNumber(java.lang.String sequenceNumber) {
		this.sequenceNumber=sequenceNumber;
	}
	@Key(generator = "ID_GEN", startAt = "1")
	public java.lang.String getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode=companyCode;
	}
	@KeyCondition(column = "CMPCOD")
	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setPartyType(java.lang.String partyType) {
		this.partyType=partyType;
	}
	@KeyCondition(column = "PTYTYP")
	public java.lang.String getPartyType() {
		return this.partyType;
	}

	/**
	 * generated by xibase.tostring plugin at 1 October, 2014 1:14:18 PM IST
	 */
	@Override
	public String toString() {
		StringBuilder sbul = new StringBuilder(89);
		sbul.append("ULDServiceabilityPK [ ");
		sbul.append("companyCode '").append(this.companyCode);
		sbul.append("', partyType '").append(this.partyType);
		sbul.append("', sequenceNumber '").append(this.sequenceNumber);
		sbul.append("' ]");
		return sbul.toString();
	}
}
